#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <Geom_Line.hxx>
#include <Geom_Axis1Placement.hxx>
#include <Geom_Axis2Placement.hxx>
#include <Prs3d_LineAspect.hxx>
#include <Geom_Plane.hxx>
#include <AIS_InteractiveContext.hxx>
#include <Prs3d_BasicAspect.hxx>
#include <SelectMgr_EntityOwner.hxx>
#include <Geom_Curve.hxx>
#include <Geom_Plane.hxx>
#include <Geom_Surface.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Vertex.hxx>
#include <Graphic3d_Camera.hxx>
#include <V3d_View.hxx>
#include <Geom_Plane.hxx>
#include <Graphic3d_ArrayOfSegments.hxx>
#include <Graphic3d_ArrayOfTriangles.hxx>
#include <SelectMgr_EntityOwner.hxx>
#include <SelectMgr_SelectionManager.hxx>
#include <V3d_Viewer.hxx>
#include <SelectMgr_OrFilter.hxx>
#include <V3d_View.hxx>
#include <Prs3d_LineAspect.hxx>
#include <Prs3d_BasicAspect.hxx>
#include <TopoDS_Shape.hxx>
#include <Geom_Curve.hxx>
#include <Geom_Plane.hxx>
#include <Geom_Surface.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Vertex.hxx>
#include <Geom_Plane.hxx>
#include <AIS_AnimationCamera.hxx>
#include <AIS_InteractiveObject.hxx>
#include <AIS_InteractiveContext.hxx>
#include <AIS_Point.hxx>
#include <AIS_RubberBand.hxx>
#include <V3d_View.hxx>
#include <SelectMgr_EntityOwner.hxx>
#include <AIS_AnimationCamera.hxx>
#include <Graphic3d_ArrayOfTriangles.hxx>
#include <V3d_View.hxx>
#include <AIS_Line.hxx>
#include <AIS_Point.hxx>
#include <Geom_Plane.hxx>
#include <Geom_Plane.hxx>
#include <SelectMgr_EntityOwner.hxx>
#include <TopoDS_Edge.hxx>
#include <Geom_Axis2Placement.hxx>
#include <AIS_Axis.hxx>
#include <AIS_Point.hxx>
#include <AIS_Plane.hxx>
#include <Geom_Plane.hxx>
#include <Geom_Circle.hxx>
#include <Geom_OffsetCurve.hxx>
#include <Geom_Surface.hxx>
#include <Geom_Plane.hxx>
#include <Geom_Axis2Placement.hxx>
#include <MeshVS_TwoColors.hxx>
#include <StdSelect_BRepOwner.hxx>
#include <SelectMgr_EntityOwner.hxx>
#include <SelectMgr_EntityOwner.hxx>
#include <Poly_Triangulation.hxx>
#include <Geom_Point.hxx>
#include <TopoDS_Vertex.hxx>
#include <Geom_Plane.hxx>
#include <gp_Circ.hxx>
#include <gp_Elips.hxx>
#include <Geom_Line.hxx>
#include <Geom_Point.hxx>
#include <Geom_Plane.hxx>
#include <Geom_Line.hxx>
#include <Geom_Circle.hxx>
#include <Geom_Ellipse.hxx>
#include <TopoDS_Wire.hxx>
#include <TopoDS_Vertex.hxx>
#include <TColStd_HPackedMapOfInteger.hxx>

// module includes
#include <AIS_GlobalStatus.hxx>
#include <AIS_TexturedShape.hxx>
#include <AIS_Axis.hxx>
#include <AIS_FixRelation.hxx>
#include <AIS_SymmetricRelation.hxx>
#include <AIS_Chamf3dDimension.hxx>
#include <AIS_InteractiveObject.hxx>
#include <AIS_MapIteratorOfMapOfInteractive.hxx>
#include <AIS_AttributeFilter.hxx>
#include <AIS_Relation.hxx>
#include <AIS_MediaPlayer.hxx>
#include <AIS_ConnectStatus.hxx>
#include <AIS_DisplayMode.hxx>
#include <AIS_DiameterDimension.hxx>
#include <AIS_ParallelRelation.hxx>
#include <AIS_DisplaySpecialSymbol.hxx>
#include <AIS_AnimationCamera.hxx>
#include <AIS_KindOfSurface.hxx>
#include <AIS_EqualRadiusRelation.hxx>
#include <AIS_ConnectedInteractive.hxx>
#include <AIS_OffsetDimension.hxx>
#include <AIS_SelectionModesConcurrency.hxx>
#include <AIS_MaxRadiusDimension.hxx>
#include <AIS_ManipulatorMode.hxx>
#include <AIS_CameraFrustum.hxx>
#include <AIS_C0RegularityFilter.hxx>
#include <AIS_InteractiveContext.hxx>
#include <AIS_Animation.hxx>
#include <AIS.hxx>
#include <AIS_ViewInputBuffer.hxx>
#include <AIS_Selection.hxx>
#include <AIS_Chamf2dDimension.hxx>
#include <AIS_ViewController.hxx>
#include <AIS_ClearMode.hxx>
#include <AIS_MultipleConnectedInteractive.hxx>
#include <AIS_AnimationObject.hxx>
#include <AIS_AngleDimension.hxx>
#include <AIS_TrihedronSelectionMode.hxx>
#include <AIS_TextLabel.hxx>
#include <AIS_StatusOfDetection.hxx>
#include <AIS_SignatureFilter.hxx>
#include <AIS_TangentRelation.hxx>
#include <AIS_MouseGesture.hxx>
#include <AIS_KindOfDimension.hxx>
#include <AIS_ColorScale.hxx>
#include <AIS_ViewCube.hxx>
#include <AIS_PlaneTrihedron.hxx>
#include <AIS_TypeOfIso.hxx>
#include <AIS_TypeOfAxis.hxx>
#include <AIS_ConcentricRelation.hxx>
#include <AIS_BadEdgeFilter.hxx>
#include <AIS_LengthDimension.hxx>
#include <AIS_Trihedron.hxx>
#include <AIS_Dimension.hxx>
#include <AIS_RadiusDimension.hxx>
#include <AIS_DimensionSelectionMode.hxx>
#include <AIS_EqualDistanceRelation.hxx>
#include <AIS_Circle.hxx>
#include <AIS_RubberBand.hxx>
#include <AIS_ListIteratorOfListOfInteractive.hxx>
#include <AIS_EllipseRadiusDimension.hxx>
#include <AIS_Plane.hxx>
#include <AIS_Manipulator.hxx>
#include <AIS_MinRadiusDimension.hxx>
#include <AIS_StatusOfPick.hxx>
#include <AIS_DimensionOwner.hxx>
#include <AIS_DisplayStatus.hxx>
#include <AIS_MapOfInteractive.hxx>
#include <AIS_RotationMode.hxx>
#include <AIS_TypeOfDist.hxx>
#include <AIS_TypeOfPlane.hxx>
#include <AIS_TypeOfAngleArrowVisibility.hxx>
#include <AIS_StandardDatum.hxx>
#include <AIS_TrihedronOwner.hxx>
#include <AIS_DataMapofIntegerListOfinteractive.hxx>
#include <AIS_DragAction.hxx>
#include <AIS_ColoredShape.hxx>
#include <AIS_KindOfInteractive.hxx>
#include <AIS_AnimationTimer.hxx>
#include <AIS_TypeOfAttribute.hxx>
#include <AIS_DataMapOfIOStatus.hxx>
#include <AIS_Shape.hxx>
#include <AIS_TypeFilter.hxx>
#include <AIS_ExclusionFilter.hxx>
#include <AIS_Triangulation.hxx>
#include <AIS_NListOfEntityOwner.hxx>
#include <AIS_NavigationMode.hxx>
#include <AIS_ListOfInteractive.hxx>
#include <AIS_GraphicTool.hxx>
#include <AIS_ColoredDrawer.hxx>
#include <AIS_ManipulatorOwner.hxx>
#include <AIS_Point.hxx>
#include <AIS_DataMapOfShapeDrawer.hxx>
#include <AIS_WalkDelta.hxx>
#include <AIS_TypeOfAngle.hxx>
#include <AIS_PerpendicularRelation.hxx>
#include <AIS_MidPointRelation.hxx>
#include <AIS_Line.hxx>
#include <AIS_SequenceOfInteractive.hxx>
#include <AIS_KindOfUnit.hxx>
#include <AIS_IdenticRelation.hxx>
#include <AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive.hxx>
#include <AIS_PointCloud.hxx>
#include <AIS_SequenceOfDimension.hxx>
#include <AIS_KindOfRelation.hxx>
#include <AIS_SelectStatus.hxx>
#include <AIS_DataMapIteratorOfDataMapOfIOStatus.hxx>
#include <AIS_IndexedDataMapOfOwnerPrs.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/AIS_GlobalStatus.hxx
// ./opencascade/AIS_TexturedShape.hxx
// ./opencascade/AIS_Axis.hxx
// ./opencascade/AIS_FixRelation.hxx
// ./opencascade/AIS_SymmetricRelation.hxx
// ./opencascade/AIS_Chamf3dDimension.hxx
// ./opencascade/AIS_InteractiveObject.hxx
// ./opencascade/AIS_MapIteratorOfMapOfInteractive.hxx
// ./opencascade/AIS_AttributeFilter.hxx
// ./opencascade/AIS_Relation.hxx
// ./opencascade/AIS_MediaPlayer.hxx
// ./opencascade/AIS_ConnectStatus.hxx
// ./opencascade/AIS_DisplayMode.hxx
// ./opencascade/AIS_DiameterDimension.hxx
// ./opencascade/AIS_ParallelRelation.hxx
// ./opencascade/AIS_DisplaySpecialSymbol.hxx
// ./opencascade/AIS_AnimationCamera.hxx
// ./opencascade/AIS_KindOfSurface.hxx
// ./opencascade/AIS_EqualRadiusRelation.hxx
// ./opencascade/AIS_ConnectedInteractive.hxx
// ./opencascade/AIS_OffsetDimension.hxx
// ./opencascade/AIS_SelectionModesConcurrency.hxx
// ./opencascade/AIS_MaxRadiusDimension.hxx
// ./opencascade/AIS_ManipulatorMode.hxx
// ./opencascade/AIS_CameraFrustum.hxx
// ./opencascade/AIS_C0RegularityFilter.hxx
// ./opencascade/AIS_InteractiveContext.hxx
// ./opencascade/AIS_Animation.hxx
// ./opencascade/AIS.hxx
// ./opencascade/AIS_ViewInputBuffer.hxx
// ./opencascade/AIS_Selection.hxx
// ./opencascade/AIS_Chamf2dDimension.hxx
// ./opencascade/AIS_ViewController.hxx
// ./opencascade/AIS_ClearMode.hxx
// ./opencascade/AIS_MultipleConnectedInteractive.hxx
// ./opencascade/AIS_AnimationObject.hxx
// ./opencascade/AIS_AngleDimension.hxx
// ./opencascade/AIS_TrihedronSelectionMode.hxx
// ./opencascade/AIS_TextLabel.hxx
// ./opencascade/AIS_StatusOfDetection.hxx
// ./opencascade/AIS_SignatureFilter.hxx
// ./opencascade/AIS_TangentRelation.hxx
// ./opencascade/AIS_MouseGesture.hxx
// ./opencascade/AIS_KindOfDimension.hxx
// ./opencascade/AIS_ColorScale.hxx
// ./opencascade/AIS_ViewCube.hxx
// ./opencascade/AIS_PlaneTrihedron.hxx
// ./opencascade/AIS_TypeOfIso.hxx
// ./opencascade/AIS_TypeOfAxis.hxx
// ./opencascade/AIS_ConcentricRelation.hxx
// ./opencascade/AIS_BadEdgeFilter.hxx
// ./opencascade/AIS_LengthDimension.hxx
// ./opencascade/AIS_Trihedron.hxx
// ./opencascade/AIS_Dimension.hxx
// ./opencascade/AIS_RadiusDimension.hxx
// ./opencascade/AIS_DimensionSelectionMode.hxx
// ./opencascade/AIS_EqualDistanceRelation.hxx
// ./opencascade/AIS_Circle.hxx
// ./opencascade/AIS_RubberBand.hxx
// ./opencascade/AIS_ListIteratorOfListOfInteractive.hxx
// ./opencascade/AIS_EllipseRadiusDimension.hxx
// ./opencascade/AIS_Plane.hxx
// ./opencascade/AIS_Manipulator.hxx
// ./opencascade/AIS_MinRadiusDimension.hxx
// ./opencascade/AIS_StatusOfPick.hxx
// ./opencascade/AIS_DimensionOwner.hxx
// ./opencascade/AIS_DisplayStatus.hxx
// ./opencascade/AIS_MapOfInteractive.hxx
// ./opencascade/AIS_RotationMode.hxx
// ./opencascade/AIS_TypeOfDist.hxx
// ./opencascade/AIS_TypeOfPlane.hxx
// ./opencascade/AIS_TypeOfAngleArrowVisibility.hxx
// ./opencascade/AIS_StandardDatum.hxx
// ./opencascade/AIS_TrihedronOwner.hxx
// ./opencascade/AIS_DataMapofIntegerListOfinteractive.hxx
// ./opencascade/AIS_DragAction.hxx
// ./opencascade/AIS_ColoredShape.hxx
// ./opencascade/AIS_KindOfInteractive.hxx
// ./opencascade/AIS_AnimationTimer.hxx
// ./opencascade/AIS_TypeOfAttribute.hxx
// ./opencascade/AIS_DataMapOfIOStatus.hxx
// ./opencascade/AIS_Shape.hxx
// ./opencascade/AIS_TypeFilter.hxx
// ./opencascade/AIS_ExclusionFilter.hxx
// ./opencascade/AIS_Triangulation.hxx
// ./opencascade/AIS_NListOfEntityOwner.hxx
// ./opencascade/AIS_NavigationMode.hxx
// ./opencascade/AIS_ListOfInteractive.hxx
// ./opencascade/AIS_GraphicTool.hxx
// ./opencascade/AIS_ColoredDrawer.hxx
// ./opencascade/AIS_ManipulatorOwner.hxx
// ./opencascade/AIS_Point.hxx
// ./opencascade/AIS_DataMapOfShapeDrawer.hxx
// ./opencascade/AIS_WalkDelta.hxx
// ./opencascade/AIS_TypeOfAngle.hxx
// ./opencascade/AIS_PerpendicularRelation.hxx
// ./opencascade/AIS_MidPointRelation.hxx
// ./opencascade/AIS_Line.hxx
// ./opencascade/AIS_SequenceOfInteractive.hxx
// ./opencascade/AIS_KindOfUnit.hxx
// ./opencascade/AIS_IdenticRelation.hxx
// ./opencascade/AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive.hxx
// ./opencascade/AIS_PointCloud.hxx
// ./opencascade/AIS_SequenceOfDimension.hxx
// ./opencascade/AIS_KindOfRelation.hxx
// ./opencascade/AIS_SelectStatus.hxx
// ./opencascade/AIS_DataMapIteratorOfDataMapOfIOStatus.hxx
// ./opencascade/AIS_IndexedDataMapOfOwnerPrs.hxx

// user-defined post
