#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <Standard_OutOfRange.hxx>
#include <TCollection_HAsciiString.hxx>
#include <Interface_ParamSet.hxx>
#include <Interface_Check.hxx>
#include <gp_XYZ.hxx>
#include <Interface_UndefinedContent.hxx>
#include <IGESData_IGESReaderData.hxx>
#include <IGESData_DirPart.hxx>
#include <Interface_Check.hxx>
#include <IGESData_ParamReader.hxx>
#include <IGESData_IGESWriter.hxx>
#include <IGESData_IGESModel.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_IGESEntity.hxx>
#include <gp_GTrsf.hxx>
#include <gp_Trsf.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_IGESModel.hxx>
#include <IGESData_IGESEntity.hxx>
#include <Interface_InterfaceError.hxx>
#include <TCollection_HAsciiString.hxx>
#include <IGESData_IGESWriter.hxx>
#include <TCollection_HAsciiString.hxx>
#include <Interface_InterfaceError.hxx>
#include <IGESData_ReadWriteModule.hxx>
#include <IGESData_GeneralModule.hxx>
#include <IGESData_IGESReaderTool.hxx>
#include <IGESData_DirChecker.hxx>
#include <IGESData_IGESType.hxx>
#include <IGESData_LineFontEntity.hxx>
#include <IGESData_LevelListEntity.hxx>
#include <IGESData_ViewKindEntity.hxx>
#include <IGESData_TransfEntity.hxx>
#include <IGESData_LabelDisplayEntity.hxx>
#include <IGESData_ColorEntity.hxx>
#include <gp_GTrsf.hxx>
#include <Interface_EntityIterator.hxx>
#include <IGESData_NodeOfSpecificLib.hxx>
#include <Standard_NoSuchObject.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_SpecificModule.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_GlobalNodeOfSpecificLib.hxx>
#include <IGESData_ReadWriteModule.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_WriterLib.hxx>
#include <IGESData_NodeOfWriterLib.hxx>
#include <Interface_ParamList.hxx>
#include <Interface_Check.hxx>
#include <Interface_InterfaceError.hxx>
#include <IGESData_IGESReaderData.hxx>
#include <IGESData_ParamCursor.hxx>
#include <Message_Msg.hxx>
#include <gp_XY.hxx>
#include <gp_XYZ.hxx>
#include <Interface_ParamList.hxx>
#include <IGESData_FileRecognizer.hxx>
#include <Interface_Check.hxx>
#include <IGESData_IGESReaderData.hxx>
#include <IGESData_Protocol.hxx>
#include <Interface_InterfaceModel.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_DirPart.hxx>
#include <IGESData_ParamReader.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_IGESModel.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_LineFontEntity.hxx>
#include <IGESData_LevelListEntity.hxx>
#include <IGESData_TransfEntity.hxx>
#include <IGESData_ViewKindEntity.hxx>
#include <IGESData_LabelDisplayEntity.hxx>
#include <IGESData_ColorEntity.hxx>
#include <IGESData_NameEntity.hxx>
#include <IGESData_SingleParentEntity.hxx>
#include <IGESData_UndefinedEntity.hxx>
#include <IGESData_FreeFormatEntity.hxx>
#include <IGESData_GlobalSection.hxx>
#include <IGESData_DefSwitch.hxx>
#include <IGESData_DirChecker.hxx>
#include <IGESData_IGESReaderData.hxx>
#include <IGESData_IGESReaderTool.hxx>
#include <IGESData_ParamReader.hxx>
#include <IGESData_ParamCursor.hxx>
#include <IGESData_DirPart.hxx>
#include <IGESData_IGESType.hxx>
#include <IGESData_FileRecognizer.hxx>
#include <IGESData_IGESWriter.hxx>
#include <IGESData_IGESDumper.hxx>
#include <IGESData_BasicEditor.hxx>
#include <IGESData_ToolLocation.hxx>
#include <IGESData_GeneralModule.hxx>
#include <IGESData_DefaultGeneral.hxx>
#include <IGESData_ReadWriteModule.hxx>
#include <IGESData_SpecificModule.hxx>
#include <IGESData_DefaultSpecific.hxx>
#include <IGESData_FileProtocol.hxx>
#include <IGESData_WriterLib.hxx>
#include <IGESData_SpecificLib.hxx>
#include <IGESData_GlobalNodeOfWriterLib.hxx>
#include <IGESData_NodeOfWriterLib.hxx>
#include <IGESData_GlobalNodeOfSpecificLib.hxx>
#include <IGESData_NodeOfSpecificLib.hxx>
#include <Standard_DomainError.hxx>
#include <Interface_FileReaderData.hxx>
#include <Interface_Check.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_IGESReaderData.hxx>
#include <IGESData_ParamReader.hxx>
#include <IGESData_IGESWriter.hxx>
#include <IGESData_GlobalNodeOfWriterLib.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_ReadWriteModule.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_WriterLib.hxx>
#include <IGESData_IGESModel.hxx>
#include <Interface_InterfaceMismatch.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_GlobalSection.hxx>
#include <IGESData_IGESEntity.hxx>
#include <gp_XY.hxx>
#include <gp_XYZ.hxx>
#include <Standard_OutOfRange.hxx>
#include <IGESData_SpecificModule.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_SpecificLib.hxx>
#include <IGESData_NodeOfSpecificLib.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_IGESDumper.hxx>
#include <Message_Messenger.hxx>
#include <Interface_Check.hxx>
#include <IGESData_IGESEntity.hxx>
#include <Standard_OutOfRange.hxx>
#include <Interface_EntityIterator.hxx>
#include <IGESData_IGESEntity.hxx>
#include <Interface_ShareTool.hxx>
#include <Interface_Check.hxx>
#include <IGESData_DirChecker.hxx>
#include <Interface_CopyTool.hxx>
#include <TCollection_HAsciiString.hxx>
#include <IGESData_IGESEntity.hxx>
#include <Interface_EntityIterator.hxx>
#include <IGESData_DirChecker.hxx>
#include <Interface_ShareTool.hxx>
#include <Interface_Check.hxx>
#include <Interface_CopyTool.hxx>
#include <IGESData_IGESType.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_InterfaceModel.hxx>
#include <IGESData_IGESEntity.hxx>
#include <Standard_NoSuchObject.hxx>
#include <IGESData_IGESType.hxx>
#include <IGESData_IGESModel.hxx>
#include <Interface_InterfaceError.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_IGESEntity.hxx>
#include <Message_Messenger.hxx>
#include <gp_GTrsf.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_IGESDumper.hxx>
#include <Message_Messenger.hxx>
#include <IGESData_GlobalNodeOfSpecificLib.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_SpecificModule.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_SpecificLib.hxx>
#include <TCollection_HAsciiString.hxx>
#include <Interface_InterfaceError.hxx>
#include <Message_Messenger.hxx>
#include <IGESData_IGESEntity.hxx>
#include <Interface_Check.hxx>
#include <IGESData_NodeOfWriterLib.hxx>
#include <Standard_NoSuchObject.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_ReadWriteModule.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_GlobalNodeOfWriterLib.hxx>
#include <Interface_ParamSet.hxx>
#include <Interface_Check.hxx>

// module includes
#include <IGESData_LevelListEntity.hxx>
#include <IGESData_ReadStage.hxx>
#include <IGESData_GlobalSection.hxx>
#include <IGESData_Array1OfDirPart.hxx>
#include <IGESData_DefSwitch.hxx>
#include <IGESData_UndefinedEntity.hxx>
#include <IGESData_ToolLocation.hxx>
#include <IGESData_BasicEditor.hxx>
#include <IGESData_FileProtocol.hxx>
#include <IGESData_FreeFormatEntity.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_Status.hxx>
#include <IGESData_SpecificLib.hxx>
#include <IGESData_GlobalNodeOfWriterLib.hxx>
#include <IGESData_ParamReader.hxx>
#include <IGESData_DefType.hxx>
#include <IGESData_LineFontEntity.hxx>
#include <IGESData_DefList.hxx>
#include <IGESData_IGESReaderTool.hxx>
#include <IGESData.hxx>
#include <IGESData_Array1OfIGESEntity.hxx>
#include <IGESData_IGESType.hxx>
#include <IGESData_ReadWriteModule.hxx>
#include <IGESData_Dump.hxx>
#include <IGESData_NodeOfWriterLib.hxx>
#include <IGESData_LabelDisplayEntity.hxx>
#include <IGESData_IGESWriter.hxx>
#include <IGESData_SingleParentEntity.hxx>
#include <IGESData_GlobalNodeOfSpecificLib.hxx>
#include <IGESData_DefaultSpecific.hxx>
#include <IGESData_DirChecker.hxx>
#include <IGESData_ViewKindEntity.hxx>
#include <IGESData_GeneralModule.hxx>
#include <IGESData_DefaultGeneral.hxx>
#include <IGESData_DirPart.hxx>
#include <IGESData_ParamCursor.hxx>
#include <IGESData_Protocol.hxx>
#include <IGESData_FileRecognizer.hxx>
#include <IGESData_IGESDumper.hxx>
#include <IGESData_TransfEntity.hxx>
#include <IGESData_SpecificModule.hxx>
#include <IGESData_NodeOfSpecificLib.hxx>
#include <IGESData_NameEntity.hxx>
#include <IGESData_ColorEntity.hxx>
#include <IGESData_IGESModel.hxx>
#include <IGESData_HArray1OfIGESEntity.hxx>
#include <IGESData_WriterLib.hxx>
#include <IGESData_IGESReaderData.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/IGESData_LevelListEntity.hxx
// ./opencascade/IGESData_ReadStage.hxx
// ./opencascade/IGESData_GlobalSection.hxx
// ./opencascade/IGESData_Array1OfDirPart.hxx
// ./opencascade/IGESData_DefSwitch.hxx
// ./opencascade/IGESData_UndefinedEntity.hxx
// ./opencascade/IGESData_ToolLocation.hxx
// ./opencascade/IGESData_BasicEditor.hxx
// ./opencascade/IGESData_FileProtocol.hxx
// ./opencascade/IGESData_FreeFormatEntity.hxx
// ./opencascade/IGESData_IGESEntity.hxx
// ./opencascade/IGESData_Status.hxx
// ./opencascade/IGESData_SpecificLib.hxx
// ./opencascade/IGESData_GlobalNodeOfWriterLib.hxx
// ./opencascade/IGESData_ParamReader.hxx
// ./opencascade/IGESData_DefType.hxx
// ./opencascade/IGESData_LineFontEntity.hxx
// ./opencascade/IGESData_DefList.hxx
// ./opencascade/IGESData_IGESReaderTool.hxx
// ./opencascade/IGESData.hxx
// ./opencascade/IGESData_Array1OfIGESEntity.hxx
// ./opencascade/IGESData_IGESType.hxx
// ./opencascade/IGESData_ReadWriteModule.hxx
// ./opencascade/IGESData_Dump.hxx
// ./opencascade/IGESData_NodeOfWriterLib.hxx
// ./opencascade/IGESData_LabelDisplayEntity.hxx
// ./opencascade/IGESData_IGESWriter.hxx
// ./opencascade/IGESData_SingleParentEntity.hxx
// ./opencascade/IGESData_GlobalNodeOfSpecificLib.hxx
// ./opencascade/IGESData_DefaultSpecific.hxx
// ./opencascade/IGESData_DirChecker.hxx
// ./opencascade/IGESData_ViewKindEntity.hxx
// ./opencascade/IGESData_GeneralModule.hxx
// ./opencascade/IGESData_DefaultGeneral.hxx
// ./opencascade/IGESData_DirPart.hxx
// ./opencascade/IGESData_ParamCursor.hxx
// ./opencascade/IGESData_Protocol.hxx
// ./opencascade/IGESData_FileRecognizer.hxx
// ./opencascade/IGESData_IGESDumper.hxx
// ./opencascade/IGESData_TransfEntity.hxx
// ./opencascade/IGESData_SpecificModule.hxx
// ./opencascade/IGESData_NodeOfSpecificLib.hxx
// ./opencascade/IGESData_NameEntity.hxx
// ./opencascade/IGESData_ColorEntity.hxx
// ./opencascade/IGESData_IGESModel.hxx
// ./opencascade/IGESData_HArray1OfIGESEntity.hxx
// ./opencascade/IGESData_WriterLib.hxx
// ./opencascade/IGESData_IGESReaderData.hxx

// user-defined post
