#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <Transfer_Finder.hxx>
#include <Transfer_TransientProcess.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Standard_NoSuchObject.hxx>
#include <Transfer_TransferFailure.hxx>
#include <Transfer_ActorOfTransientProcess.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_Graph.hxx>
#include <Interface_EntityIterator.hxx>
#include <Transfer_TransferFailure.hxx>
#include <Message_Messenger.hxx>
#include <Transfer_ActorOfProcessForFinder.hxx>
#include <Message_ProgressIndicator.hxx>
#include <Interface_InterfaceError.hxx>
#include <Transfer_TransferFailure.hxx>
#include <Transfer_IteratorOfProcessForFinder.hxx>
#include <Message_Msg.hxx>
#include <Interface_Check.hxx>
#include <Interface_CheckIterator.hxx>
#include <Transfer_Binder.hxx>
#include <Interface_Check.hxx>
#include <Transfer_TransientProcess.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_HGraph.hxx>
#include <Interface_Graph.hxx>
#include <Message_Messenger.hxx>
#include <Interface_EntityIterator.hxx>
#include <Transfer_ProcessForTransient.hxx>
#include <Transfer_TransientProcess.hxx>
#include <Transfer_TransferFailure.hxx>
#include <Transfer_ProcessForFinder.hxx>
#include <Transfer_ActorOfProcessForFinder.hxx>
#include <Transfer_TransientMapper.hxx>
#include <Message_Messenger.hxx>
#include <Interface_Check.hxx>
#include <Transfer_ProcessForFinder.hxx>
#include <Transfer_IteratorOfProcessForFinder.hxx>
#include <Transfer_SimpleBinderOfTransient.hxx>
#include <Interface_Check.hxx>
#include <Transfer_TransferFailure.hxx>
#include <Standard_TypeMismatch.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Protocol.hxx>
#include <Transfer_TransientProcess.hxx>
#include <Transfer_ProcessForTransient.hxx>
#include <Transfer_ActorOfProcessForTransient.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Protocol.hxx>
#include <Transfer_TransientProcess.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Transfer_ResultFromTransient.hxx>
#include <Transfer_TransientProcess.hxx>
#include <Interface_CheckIterator.hxx>
#include <Message_Messenger.hxx>
#include <Transfer_ActorOfProcessForTransient.hxx>
#include <Message_ProgressIndicator.hxx>
#include <Interface_InterfaceError.hxx>
#include <Transfer_TransferFailure.hxx>
#include <Transfer_IteratorOfProcessForTransient.hxx>
#include <Message_Msg.hxx>
#include <Interface_Check.hxx>
#include <Interface_CheckIterator.hxx>
#include <Transfer_TransferFailure.hxx>
#include <Interface_EntityIterator.hxx>
#include <Transfer_TransferIterator.hxx>
#include <Transfer_TransientProcess.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Protocol.hxx>
#include <Transfer_FinderProcess.hxx>
#include <Transfer_ProcessForTransient.hxx>
#include <Transfer_IteratorOfProcessForTransient.hxx>
#include <Transfer_SimpleBinderOfTransient.hxx>
#include <Transfer_TransientProcess.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_InterfaceError.hxx>
#include <Transfer_ProcessForFinder.hxx>
#include <Transfer_FinderProcess.hxx>
#include <Transfer_DataInfo.hxx>

// module includes
#include <Transfer_VoidBinder.hxx>
#include <Transfer_Finder.hxx>
#include <Transfer_FindHasher.hxx>
#include <Transfer_TransferOutput.hxx>
#include <Transfer_MultipleBinder.hxx>
#include <Transfer_HSequenceOfBinder.hxx>
#include <Transfer_ProcessForFinder.hxx>
#include <Transfer_ResultFromTransient.hxx>
#include <Transfer_TransientProcess.hxx>
#include <Transfer_SequenceOfBinder.hxx>
#include <Transfer_TransferMapOfProcessForTransient.hxx>
#include <Transfer_ActorOfTransientProcess.hxx>
#include <Transfer_SimpleBinderOfTransient.hxx>
#include <Transfer_BinderOfTransientInteger.hxx>
#include <Transfer_IteratorOfProcessForFinder.hxx>
#include <Transfer_StatusExec.hxx>
#include <Transfer_FinderProcess.hxx>
#include <Transfer_UndefMode.hxx>
#include <Transfer_MapContainer.hxx>
#include <Transfer_TransferIterator.hxx>
#include <Transfer_ActorOfProcessForFinder.hxx>
#include <Transfer_Binder.hxx>
#include <Transfer_TransientListBinder.hxx>
#include <Transfer_TransferDispatch.hxx>
#include <Transfer_IteratorOfProcessForTransient.hxx>
#include <Transfer_TransferMapOfProcessForFinder.hxx>
#include <Transfer_ActorDispatch.hxx>
#include <Transfer_HSequenceOfFinder.hxx>
#include <Transfer_SequenceOfFinder.hxx>
#include <Transfer_ResultFromModel.hxx>
#include <Transfer_StatusResult.hxx>
#include <Transfer_TransferDeadLoop.hxx>
#include <Transfer_ProcessForTransient.hxx>
#include <Transfer_TransferInput.hxx>
#include <Transfer_TransferFailure.hxx>
#include <Transfer_DataInfo.hxx>
#include <Transfer_ActorOfProcessForTransient.hxx>
#include <Transfer_DispatchControl.hxx>
#include <Transfer_ActorOfFinderProcess.hxx>
#include <Transfer_TransientMapper.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/Transfer_VoidBinder.hxx
// ./opencascade/Transfer_Finder.hxx
// ./opencascade/Transfer_FindHasher.hxx
// ./opencascade/Transfer_TransferOutput.hxx
// ./opencascade/Transfer_MultipleBinder.hxx
// ./opencascade/Transfer_HSequenceOfBinder.hxx
// ./opencascade/Transfer_ProcessForFinder.hxx
// ./opencascade/Transfer_ResultFromTransient.hxx
// ./opencascade/Transfer_TransientProcess.hxx
// ./opencascade/Transfer_SequenceOfBinder.hxx
// ./opencascade/Transfer_TransferMapOfProcessForTransient.hxx
// ./opencascade/Transfer_ActorOfTransientProcess.hxx
// ./opencascade/Transfer_SimpleBinderOfTransient.hxx
// ./opencascade/Transfer_BinderOfTransientInteger.hxx
// ./opencascade/Transfer_IteratorOfProcessForFinder.hxx
// ./opencascade/Transfer_StatusExec.hxx
// ./opencascade/Transfer_FinderProcess.hxx
// ./opencascade/Transfer_UndefMode.hxx
// ./opencascade/Transfer_MapContainer.hxx
// ./opencascade/Transfer_TransferIterator.hxx
// ./opencascade/Transfer_ActorOfProcessForFinder.hxx
// ./opencascade/Transfer_Binder.hxx
// ./opencascade/Transfer_TransientListBinder.hxx
// ./opencascade/Transfer_TransferDispatch.hxx
// ./opencascade/Transfer_IteratorOfProcessForTransient.hxx
// ./opencascade/Transfer_TransferMapOfProcessForFinder.hxx
// ./opencascade/Transfer_ActorDispatch.hxx
// ./opencascade/Transfer_HSequenceOfFinder.hxx
// ./opencascade/Transfer_SequenceOfFinder.hxx
// ./opencascade/Transfer_ResultFromModel.hxx
// ./opencascade/Transfer_StatusResult.hxx
// ./opencascade/Transfer_TransferDeadLoop.hxx
// ./opencascade/Transfer_ProcessForTransient.hxx
// ./opencascade/Transfer_TransferInput.hxx
// ./opencascade/Transfer_TransferFailure.hxx
// ./opencascade/Transfer_DataInfo.hxx
// ./opencascade/Transfer_ActorOfProcessForTransient.hxx
// ./opencascade/Transfer_DispatchControl.hxx
// ./opencascade/Transfer_ActorOfFinderProcess.hxx
// ./opencascade/Transfer_TransientMapper.hxx

// user-defined post
