#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <TColStd_HPackedMapOfInteger.hxx>
#include <MeshVS_DataSource.hxx>
#include <MeshVS_Drawer.hxx>
#include <Bnd_Box.hxx>
#include <MeshVS_Mesh.hxx>
#include <TColStd_HPackedMapOfInteger.hxx>
#include <Bnd_Box2d.hxx>
#include <MeshVS_DataSource.hxx>
#include <MeshVS_Drawer.hxx>
#include <MeshVS_Mesh.hxx>
#include <Select3D_SensitiveEntity.hxx>
#include <SelectMgr_EntityOwner.hxx>
#include <MeshVS_Mesh.hxx>
#include <MeshVS_DataSource.hxx>
#include <Graphic3d_Texture2D.hxx>
#include <Graphic3d_ArrayOfPrimitives.hxx>
#include <MeshVS_DataSource.hxx>
#include <TColStd_HPackedMapOfInteger.hxx>
#include <Graphic3d_AspectFillArea3d.hxx>
#include <MeshVS_Drawer.hxx>
#include <Graphic3d_MaterialAspect.hxx>
#include <Graphic3d_AspectLine3d.hxx>
#include <Graphic3d_AspectMarker3d.hxx>
#include <Graphic3d_AspectText3d.hxx>
#include <gp_Vec.hxx>
#include <MeshVS_Mesh.hxx>
#include <MeshVS_DataSource.hxx>
#include <Graphic3d_ArrayOfPrimitives.hxx>
#include <MeshVS_Mesh.hxx>
#include <MeshVS_DataSource.hxx>
#include <Bnd_Box2d.hxx>
#include <MeshVS_Mesh.hxx>
#include <MeshVS_DataSource.hxx>
#include <MeshVS_Mesh.hxx>
#include <MeshVS_Mesh.hxx>
#include <MeshVS_DataSource.hxx>
#include <Graphic3d_ArrayOfSegments.hxx>
#include <Graphic3d_ArrayOfTriangles.hxx>
#include <Graphic3d_ArrayOfPrimitives.hxx>

// module includes
#include <MeshVS_DeformedDataSource.hxx>
#include <MeshVS_DataMapOfTwoColorsMapOfInteger.hxx>
#include <MeshVS_TwoColors.hxx>
#include <MeshVS_DataMapOfIntegerBoolean.hxx>
#include <MeshVS_Drawer.hxx>
#include <MeshVS_Mesh.hxx>
#include <MeshVS_DataMapOfIntegerVector.hxx>
#include <MeshVS_DummySensitiveEntity.hxx>
#include <MeshVS_DataSource.hxx>
#include <MeshVS_TwoNodesHasher.hxx>
#include <MeshVS_DataMapOfColorMapOfInteger.hxx>
#include <MeshVS_MeshEntityOwner.hxx>
#include <MeshVS_PrsBuilder.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfIntegerOwner.hxx>
#include <MeshVS_DataMapOfIntegerMaterial.hxx>
#include <MeshVS_NodalColorPrsBuilder.hxx>
#include <MeshVS_SequenceOfPrsBuilder.hxx>
#include <MeshVS_MeshOwner.hxx>
#include <MeshVS_Tool.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfColorMapOfInteger.hxx>
#include <MeshVS_CommonSensitiveEntity.hxx>
#include <MeshVS_MapIteratorOfMapOfTwoNodes.hxx>
#include <MeshVS_Array1OfSequenceOfInteger.hxx>
#include <MeshVS_DataSource3D.hxx>
#include <MeshVS_DisplayModeFlags.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfIntegerAsciiString.hxx>
#include <MeshVS_HArray1OfSequenceOfInteger.hxx>
#include <MeshVS_SymmetricPairHasher.hxx>
#include <MeshVS_SensitiveSegment.hxx>
#include <MeshVS_TwoNodes.hxx>
#include <MeshVS_DataMapOfIntegerTwoColors.hxx>
#include <MeshVS_SensitiveQuad.hxx>
#include <MeshVS_ColorHasher.hxx>
#include <MeshVS_VectorPrsBuilder.hxx>
#include <MeshVS_DataMapOfIntegerColor.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfIntegerMaterial.hxx>
#include <MeshVS_TextPrsBuilder.hxx>
#include <MeshVS_SensitivePolyhedron.hxx>
#include <MeshVS_SensitiveFace.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfIntegerColor.hxx>
#include <MeshVS_ElementalColorPrsBuilder.hxx>
#include <MeshVS_MeshSelectionMethod.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfIntegerBoolean.hxx>
#include <MeshVS_SensitiveMesh.hxx>
#include <MeshVS_BuilderPriority.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfIntegerVector.hxx>
#include <MeshVS_DataMapOfIntegerOwner.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfTwoColorsMapOfInteger.hxx>
#include <MeshVS_MeshPtr.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfIntegerTwoColors.hxx>
#include <MeshVS_EntityType.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfIntegerMeshEntityOwner.hxx>
#include <MeshVS_DrawerAttribute.hxx>
#include <MeshVS_DataMapOfHArray1OfSequenceOfInteger.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfHArray1OfSequenceOfInteger.hxx>
#include <MeshVS_DataMapOfIntegerMeshEntityOwner.hxx>
#include <MeshVS_TwoColorsHasher.hxx>
#include <MeshVS_DataMapOfIntegerAsciiString.hxx>
#include <MeshVS_SelectionModeFlags.hxx>
#include <MeshVS_MapOfTwoNodes.hxx>
#include <MeshVS_MeshPrsBuilder.hxx>
#include <MeshVS_Buffer.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/MeshVS_DeformedDataSource.hxx
// ./opencascade/MeshVS_DataMapOfTwoColorsMapOfInteger.hxx
// ./opencascade/MeshVS_TwoColors.hxx
// ./opencascade/MeshVS_DataMapOfIntegerBoolean.hxx
// ./opencascade/MeshVS_Drawer.hxx
// ./opencascade/MeshVS_Mesh.hxx
// ./opencascade/MeshVS_DataMapOfIntegerVector.hxx
// ./opencascade/MeshVS_DummySensitiveEntity.hxx
// ./opencascade/MeshVS_DataSource.hxx
// ./opencascade/MeshVS_TwoNodesHasher.hxx
// ./opencascade/MeshVS_DataMapOfColorMapOfInteger.hxx
// ./opencascade/MeshVS_MeshEntityOwner.hxx
// ./opencascade/MeshVS_PrsBuilder.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfIntegerOwner.hxx
// ./opencascade/MeshVS_DataMapOfIntegerMaterial.hxx
// ./opencascade/MeshVS_NodalColorPrsBuilder.hxx
// ./opencascade/MeshVS_SequenceOfPrsBuilder.hxx
// ./opencascade/MeshVS_MeshOwner.hxx
// ./opencascade/MeshVS_Tool.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfColorMapOfInteger.hxx
// ./opencascade/MeshVS_CommonSensitiveEntity.hxx
// ./opencascade/MeshVS_MapIteratorOfMapOfTwoNodes.hxx
// ./opencascade/MeshVS_Array1OfSequenceOfInteger.hxx
// ./opencascade/MeshVS_DataSource3D.hxx
// ./opencascade/MeshVS_DisplayModeFlags.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfIntegerAsciiString.hxx
// ./opencascade/MeshVS_HArray1OfSequenceOfInteger.hxx
// ./opencascade/MeshVS_SymmetricPairHasher.hxx
// ./opencascade/MeshVS_SensitiveSegment.hxx
// ./opencascade/MeshVS_TwoNodes.hxx
// ./opencascade/MeshVS_DataMapOfIntegerTwoColors.hxx
// ./opencascade/MeshVS_SensitiveQuad.hxx
// ./opencascade/MeshVS_ColorHasher.hxx
// ./opencascade/MeshVS_VectorPrsBuilder.hxx
// ./opencascade/MeshVS_DataMapOfIntegerColor.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfIntegerMaterial.hxx
// ./opencascade/MeshVS_TextPrsBuilder.hxx
// ./opencascade/MeshVS_SensitivePolyhedron.hxx
// ./opencascade/MeshVS_SensitiveFace.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfIntegerColor.hxx
// ./opencascade/MeshVS_ElementalColorPrsBuilder.hxx
// ./opencascade/MeshVS_MeshSelectionMethod.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfIntegerBoolean.hxx
// ./opencascade/MeshVS_SensitiveMesh.hxx
// ./opencascade/MeshVS_BuilderPriority.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfIntegerVector.hxx
// ./opencascade/MeshVS_DataMapOfIntegerOwner.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfTwoColorsMapOfInteger.hxx
// ./opencascade/MeshVS_MeshPtr.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfIntegerTwoColors.hxx
// ./opencascade/MeshVS_EntityType.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfIntegerMeshEntityOwner.hxx
// ./opencascade/MeshVS_DrawerAttribute.hxx
// ./opencascade/MeshVS_DataMapOfHArray1OfSequenceOfInteger.hxx
// ./opencascade/MeshVS_DataMapIteratorOfDataMapOfHArray1OfSequenceOfInteger.hxx
// ./opencascade/MeshVS_DataMapOfIntegerMeshEntityOwner.hxx
// ./opencascade/MeshVS_TwoColorsHasher.hxx
// ./opencascade/MeshVS_DataMapOfIntegerAsciiString.hxx
// ./opencascade/MeshVS_SelectionModeFlags.hxx
// ./opencascade/MeshVS_MapOfTwoNodes.hxx
// ./opencascade/MeshVS_MeshPrsBuilder.hxx
// ./opencascade/MeshVS_Buffer.hxx

// user-defined post
