#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <StepGeom_Direction.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CurveBoundedSurface.hxx>
#include <StepShape_ToleranceValue.hxx>
#include <StepShape_LimitsAndFits.hxx>
#include <StepShape_EdgeLoop.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepRepr_ShapeAspect.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Direction.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_FaceSurface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Point.hxx>
#include <StepGeom_Curve.hxx>
#include <StepGeom_Surface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_PrecisionQualifier.hxx>
#include <StepShape_TypeQualifier.hxx>
#include <StepShape_ValueFormatTypeQualifier.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_FacetedBrep.hxx>
#include <StepShape_BrepWithVoids.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_Loop.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis1Placement.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_FaceSurface.hxx>
#include <StepRepr_ShapeAspect.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_ConnectedFaceSet.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_ClosedShell.hxx>
#include <StepShape_Loop.hxx>
#include <StepShape_Path.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepRepr_ShapeAspect.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CartesianTransformationOperator3d.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Surface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CurveBoundedSurface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Curve.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepRepr_ShapeAspect.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_Edge.hxx>
#include <StepShape_Path.hxx>
#include <StepShape_Face.hxx>
#include <StepShape_FaceBound.hxx>
#include <StepShape_ClosedShell.hxx>
#include <StepShape_OpenShell.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis1Placement.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CartesianPoint.hxx>
#include <StepGeom_Point.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_Vertex.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepRepr_CompoundRepresentationItem.hxx>
#include <StepRepr_DescriptiveRepresentationItem.hxx>
#include <StepRepr_MeasureRepresentationItem.hxx>
#include <StepGeom_Placement.hxx>
#include <StepGeom_Axis1Placement.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis1Placement.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CurveBoundedSurface.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_FaceSurface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_BooleanResult.hxx>
#include <StepGeom_Surface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis1Placement.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureValueMember.hxx>
#include <StepBasic_Unit.hxx>
#include <StepShape_BoxDomain.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Surface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepRepr_ShapeAspect.hxx>
#include <StepShape_OpenShell.hxx>
#include <StepShape_ClosedShell.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Point.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Pcurve.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_DimensionalLocation.hxx>
#include <StepShape_DimensionalSize.hxx>
#include <StepShape_SolidModel.hxx>
#include <StepShape_HalfSpaceSolid.hxx>
#include <StepShape_BooleanResult.hxx>
#include <StepShape_ShapeDimensionRepresentation.hxx>
#include <StepShape_Sphere.hxx>
#include <StepShape_Block.hxx>
#include <StepShape_RightAngularWedge.hxx>
#include <StepShape_Torus.hxx>
#include <StepShape_RightCircularCone.hxx>
#include <StepShape_RightCircularCylinder.hxx>
#include <StepRepr_ShapeRepresentationRelationship.hxx>
#include <StepRepr_ProductDefinitionShape.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepShape_ShellBasedSurfaceModel.hxx>

// module includes
#include <StepShape_ExtrudedAreaSolid.hxx>
#include <StepShape_PlusMinusTolerance.hxx>
#include <StepShape_ToleranceMethodDefinition.hxx>
#include <StepShape_HArray1OfValueQualifier.hxx>
#include <StepShape_OrientedPath.hxx>
#include <StepShape_DimensionalSizeWithPath.hxx>
#include <StepShape_ExtrudedFaceSolid.hxx>
#include <StepShape_Vertex.hxx>
#include <StepShape_ShapeRepresentationWithParameters.hxx>
#include <StepShape_OrientedFace.hxx>
#include <StepShape_NonManifoldSurfaceShapeRepresentation.hxx>
#include <StepShape_Path.hxx>
#include <StepShape_GeometricSetSelect.hxx>
#include <StepShape_EdgeLoop.hxx>
#include <StepShape_TopologicalRepresentationItem.hxx>
#include <StepShape_GeometricallyBoundedWireframeShapeRepresentation.hxx>
#include <StepShape_FaceBasedSurfaceModel.hxx>
#include <StepShape_Edge.hxx>
#include <StepShape_Block.hxx>
#include <StepShape_HArray1OfOrientedClosedShell.hxx>
#include <StepShape_ValueQualifier.hxx>
#include <StepShape_ShellBasedSurfaceModel.hxx>
#include <StepShape_FacetedBrepAndBrepWithVoids.hxx>
#include <StepShape_Array1OfShell.hxx>
#include <StepShape_ShapeDimensionRepresentation.hxx>
#include <StepShape_FaceBound.hxx>
#include <StepShape_RevolvedFaceSolid.hxx>
#include <StepShape_AdvancedFace.hxx>
#include <StepShape_DimensionalLocationWithPath.hxx>
#include <StepShape_ShapeDefinitionRepresentation.hxx>
#include <StepShape_TransitionalShapeRepresentation.hxx>
#include <StepShape_Array1OfShapeDimensionRepresentationItem.hxx>
#include <StepShape_HArray1OfShapeDimensionRepresentationItem.hxx>
#include <StepShape_SolidModel.hxx>
#include <StepShape_AngleRelator.hxx>
#include <StepShape_ManifoldSolidBrep.hxx>
#include <StepShape_ManifoldSurfaceShapeRepresentation.hxx>
#include <StepShape_LoopAndPath.hxx>
#include <StepShape_OrientedClosedShell.hxx>
#include <StepShape_DimensionalSize.hxx>
#include <StepShape_BrepWithVoids.hxx>
#include <StepShape_BooleanResult.hxx>
#include <StepShape_SolidReplica.hxx>
#include <StepShape_GeometricSet.hxx>
#include <StepShape_HalfSpaceSolid.hxx>
#include <StepShape_AdvancedBrepShapeRepresentation.hxx>
#include <StepShape_HArray1OfConnectedFaceSet.hxx>
#include <StepShape_ConnectedFaceSubSet.hxx>
#include <StepShape_SweptAreaSolid.hxx>
#include <StepShape_HArray1OfConnectedEdgeSet.hxx>
#include <StepShape_EdgeCurve.hxx>
#include <StepShape_ConnectedEdgeSet.hxx>
#include <StepShape_PrecisionQualifier.hxx>
#include <StepShape_DimensionalLocation.hxx>
#include <StepShape_QualifiedRepresentationItem.hxx>
#include <StepShape_ShapeRepresentation.hxx>
#include <StepShape_AngularSize.hxx>
#include <StepShape_HArray1OfFaceBound.hxx>
#include <StepShape_Subface.hxx>
#include <StepShape_Subedge.hxx>
#include <StepShape_EdgeBasedWireframeShapeRepresentation.hxx>
#include <StepShape_ReversibleTopologyItem.hxx>
#include <StepShape_HArray1OfGeometricSetSelect.hxx>
#include <StepShape_EdgeBasedWireframeModel.hxx>
#include <StepShape_GeometricCurveSet.hxx>
#include <StepShape_PolyLoop.hxx>
#include <StepShape_Array1OfGeometricSetSelect.hxx>
#include <StepShape_LimitsAndFits.hxx>
#include <StepShape_CsgShapeRepresentation.hxx>
#include <StepShape_Array1OfOrientedClosedShell.hxx>
#include <StepShape_GeometricallyBoundedSurfaceShapeRepresentation.hxx>
#include <StepShape_Array1OfValueQualifier.hxx>
#include <StepShape_RightCircularCylinder.hxx>
#include <StepShape_TypeQualifier.hxx>
#include <StepShape_Face.hxx>
#include <StepShape_OrientedEdge.hxx>
#include <StepShape_HArray1OfShell.hxx>
#include <StepShape_BoxDomain.hxx>
#include <StepShape_Loop.hxx>
#include <StepShape_VertexPoint.hxx>
#include <StepShape_VertexLoop.hxx>
#include <StepShape_PointRepresentation.hxx>
#include <StepShape_ShapeDimensionRepresentationItem.hxx>
#include <StepShape_Torus.hxx>
#include <StepShape_CsgSolid.hxx>
#include <StepShape_RevolvedAreaSolid.hxx>
#include <StepShape_ToleranceValue.hxx>
#include <StepShape_FacetedBrep.hxx>
#include <StepShape_RightAngularWedge.hxx>
#include <StepShape_SweptFaceSolid.hxx>
#include <StepShape_HArray1OfOrientedEdge.hxx>
#include <StepShape_Array1OfFaceBound.hxx>
#include <StepShape_OpenShell.hxx>
#include <StepShape_CsgSelect.hxx>
#include <StepShape_ConnectedFaceShapeRepresentation.hxx>
#include <StepShape_FaceSurface.hxx>
#include <StepShape_RightCircularCone.hxx>
#include <StepShape_Array1OfOrientedEdge.hxx>
#include <StepShape_ClosedShell.hxx>
#include <StepShape_MeasureRepresentationItemAndQualifiedRepresentationItem.hxx>
#include <StepShape_ValueFormatTypeQualifier.hxx>
#include <StepShape_BoxedHalfSpace.hxx>
#include <StepShape_DirectedDimensionalLocation.hxx>
#include <StepShape_MeasureQualification.hxx>
#include <StepShape_DefinitionalRepresentationAndShapeRepresentation.hxx>
#include <StepShape_FacetedBrepShapeRepresentation.hxx>
#include <StepShape_CompoundShapeRepresentation.hxx>
#include <StepShape_AngularLocation.hxx>
#include <StepShape_HArray1OfFace.hxx>
#include <StepShape_Shell.hxx>
#include <StepShape_OrientedOpenShell.hxx>
#include <StepShape_HArray1OfEdge.hxx>
#include <StepShape_Sphere.hxx>
#include <StepShape_Array1OfFace.hxx>
#include <StepShape_Array1OfConnectedEdgeSet.hxx>
#include <StepShape_SeamEdge.hxx>
#include <StepShape_DimensionalCharacteristic.hxx>
#include <StepShape_BooleanOperand.hxx>
#include <StepShape_Array1OfConnectedFaceSet.hxx>
#include <StepShape_DimensionalCharacteristicRepresentation.hxx>
#include <StepShape_CsgPrimitive.hxx>
#include <StepShape_ContextDependentShapeRepresentation.hxx>
#include <StepShape_Array1OfEdge.hxx>
#include <StepShape_ConnectedFaceSet.hxx>
#include <StepShape_BooleanOperator.hxx>
#include <StepShape_SurfaceModel.hxx>
#include <StepShape_FaceOuterBound.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/StepShape_ExtrudedAreaSolid.hxx
// ./opencascade/StepShape_PlusMinusTolerance.hxx
// ./opencascade/StepShape_ToleranceMethodDefinition.hxx
// ./opencascade/StepShape_HArray1OfValueQualifier.hxx
// ./opencascade/StepShape_OrientedPath.hxx
// ./opencascade/StepShape_DimensionalSizeWithPath.hxx
// ./opencascade/StepShape_ExtrudedFaceSolid.hxx
// ./opencascade/StepShape_Vertex.hxx
// ./opencascade/StepShape_ShapeRepresentationWithParameters.hxx
// ./opencascade/StepShape_OrientedFace.hxx
// ./opencascade/StepShape_NonManifoldSurfaceShapeRepresentation.hxx
// ./opencascade/StepShape_Path.hxx
// ./opencascade/StepShape_GeometricSetSelect.hxx
// ./opencascade/StepShape_EdgeLoop.hxx
// ./opencascade/StepShape_TopologicalRepresentationItem.hxx
// ./opencascade/StepShape_GeometricallyBoundedWireframeShapeRepresentation.hxx
// ./opencascade/StepShape_FaceBasedSurfaceModel.hxx
// ./opencascade/StepShape_Edge.hxx
// ./opencascade/StepShape_Block.hxx
// ./opencascade/StepShape_HArray1OfOrientedClosedShell.hxx
// ./opencascade/StepShape_ValueQualifier.hxx
// ./opencascade/StepShape_ShellBasedSurfaceModel.hxx
// ./opencascade/StepShape_FacetedBrepAndBrepWithVoids.hxx
// ./opencascade/StepShape_Array1OfShell.hxx
// ./opencascade/StepShape_ShapeDimensionRepresentation.hxx
// ./opencascade/StepShape_FaceBound.hxx
// ./opencascade/StepShape_RevolvedFaceSolid.hxx
// ./opencascade/StepShape_AdvancedFace.hxx
// ./opencascade/StepShape_DimensionalLocationWithPath.hxx
// ./opencascade/StepShape_ShapeDefinitionRepresentation.hxx
// ./opencascade/StepShape_TransitionalShapeRepresentation.hxx
// ./opencascade/StepShape_Array1OfShapeDimensionRepresentationItem.hxx
// ./opencascade/StepShape_HArray1OfShapeDimensionRepresentationItem.hxx
// ./opencascade/StepShape_SolidModel.hxx
// ./opencascade/StepShape_AngleRelator.hxx
// ./opencascade/StepShape_ManifoldSolidBrep.hxx
// ./opencascade/StepShape_ManifoldSurfaceShapeRepresentation.hxx
// ./opencascade/StepShape_LoopAndPath.hxx
// ./opencascade/StepShape_OrientedClosedShell.hxx
// ./opencascade/StepShape_DimensionalSize.hxx
// ./opencascade/StepShape_BrepWithVoids.hxx
// ./opencascade/StepShape_BooleanResult.hxx
// ./opencascade/StepShape_SolidReplica.hxx
// ./opencascade/StepShape_GeometricSet.hxx
// ./opencascade/StepShape_HalfSpaceSolid.hxx
// ./opencascade/StepShape_AdvancedBrepShapeRepresentation.hxx
// ./opencascade/StepShape_HArray1OfConnectedFaceSet.hxx
// ./opencascade/StepShape_ConnectedFaceSubSet.hxx
// ./opencascade/StepShape_SweptAreaSolid.hxx
// ./opencascade/StepShape_HArray1OfConnectedEdgeSet.hxx
// ./opencascade/StepShape_EdgeCurve.hxx
// ./opencascade/StepShape_ConnectedEdgeSet.hxx
// ./opencascade/StepShape_PrecisionQualifier.hxx
// ./opencascade/StepShape_DimensionalLocation.hxx
// ./opencascade/StepShape_QualifiedRepresentationItem.hxx
// ./opencascade/StepShape_ShapeRepresentation.hxx
// ./opencascade/StepShape_AngularSize.hxx
// ./opencascade/StepShape_HArray1OfFaceBound.hxx
// ./opencascade/StepShape_Subface.hxx
// ./opencascade/StepShape_Subedge.hxx
// ./opencascade/StepShape_EdgeBasedWireframeShapeRepresentation.hxx
// ./opencascade/StepShape_ReversibleTopologyItem.hxx
// ./opencascade/StepShape_HArray1OfGeometricSetSelect.hxx
// ./opencascade/StepShape_EdgeBasedWireframeModel.hxx
// ./opencascade/StepShape_GeometricCurveSet.hxx
// ./opencascade/StepShape_PolyLoop.hxx
// ./opencascade/StepShape_Array1OfGeometricSetSelect.hxx
// ./opencascade/StepShape_LimitsAndFits.hxx
// ./opencascade/StepShape_CsgShapeRepresentation.hxx
// ./opencascade/StepShape_Array1OfOrientedClosedShell.hxx
// ./opencascade/StepShape_GeometricallyBoundedSurfaceShapeRepresentation.hxx
// ./opencascade/StepShape_Array1OfValueQualifier.hxx
// ./opencascade/StepShape_RightCircularCylinder.hxx
// ./opencascade/StepShape_TypeQualifier.hxx
// ./opencascade/StepShape_Face.hxx
// ./opencascade/StepShape_OrientedEdge.hxx
// ./opencascade/StepShape_HArray1OfShell.hxx
// ./opencascade/StepShape_BoxDomain.hxx
// ./opencascade/StepShape_Loop.hxx
// ./opencascade/StepShape_VertexPoint.hxx
// ./opencascade/StepShape_VertexLoop.hxx
// ./opencascade/StepShape_PointRepresentation.hxx
// ./opencascade/StepShape_ShapeDimensionRepresentationItem.hxx
// ./opencascade/StepShape_Torus.hxx
// ./opencascade/StepShape_CsgSolid.hxx
// ./opencascade/StepShape_RevolvedAreaSolid.hxx
// ./opencascade/StepShape_ToleranceValue.hxx
// ./opencascade/StepShape_FacetedBrep.hxx
// ./opencascade/StepShape_RightAngularWedge.hxx
// ./opencascade/StepShape_SweptFaceSolid.hxx
// ./opencascade/StepShape_HArray1OfOrientedEdge.hxx
// ./opencascade/StepShape_Array1OfFaceBound.hxx
// ./opencascade/StepShape_OpenShell.hxx
// ./opencascade/StepShape_CsgSelect.hxx
// ./opencascade/StepShape_ConnectedFaceShapeRepresentation.hxx
// ./opencascade/StepShape_FaceSurface.hxx
// ./opencascade/StepShape_RightCircularCone.hxx
// ./opencascade/StepShape_Array1OfOrientedEdge.hxx
// ./opencascade/StepShape_ClosedShell.hxx
// ./opencascade/StepShape_MeasureRepresentationItemAndQualifiedRepresentationItem.hxx
// ./opencascade/StepShape_ValueFormatTypeQualifier.hxx
// ./opencascade/StepShape_BoxedHalfSpace.hxx
// ./opencascade/StepShape_DirectedDimensionalLocation.hxx
// ./opencascade/StepShape_MeasureQualification.hxx
// ./opencascade/StepShape_DefinitionalRepresentationAndShapeRepresentation.hxx
// ./opencascade/StepShape_FacetedBrepShapeRepresentation.hxx
// ./opencascade/StepShape_CompoundShapeRepresentation.hxx
// ./opencascade/StepShape_AngularLocation.hxx
// ./opencascade/StepShape_HArray1OfFace.hxx
// ./opencascade/StepShape_Shell.hxx
// ./opencascade/StepShape_OrientedOpenShell.hxx
// ./opencascade/StepShape_HArray1OfEdge.hxx
// ./opencascade/StepShape_Sphere.hxx
// ./opencascade/StepShape_Array1OfFace.hxx
// ./opencascade/StepShape_Array1OfConnectedEdgeSet.hxx
// ./opencascade/StepShape_SeamEdge.hxx
// ./opencascade/StepShape_DimensionalCharacteristic.hxx
// ./opencascade/StepShape_BooleanOperand.hxx
// ./opencascade/StepShape_Array1OfConnectedFaceSet.hxx
// ./opencascade/StepShape_DimensionalCharacteristicRepresentation.hxx
// ./opencascade/StepShape_CsgPrimitive.hxx
// ./opencascade/StepShape_ContextDependentShapeRepresentation.hxx
// ./opencascade/StepShape_Array1OfEdge.hxx
// ./opencascade/StepShape_ConnectedFaceSet.hxx
// ./opencascade/StepShape_BooleanOperator.hxx
// ./opencascade/StepShape_SurfaceModel.hxx
// ./opencascade/StepShape_FaceOuterBound.hxx

// user-defined post
