{% set OCCT_VER = "7.7.1" %}
{% set OCP_TWEAK = "0" %}

package:
  name: ocp
  version: {{OCCT_VER}}.{{OCP_TWEAK}}

source:
  path: ..

build:
  number: 0
  script:
    {% if not os.path.exists('build') %}
    - cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release
    - cmake --build build
    {% endif %}
    - cmake --install build --prefix {{ environ.get('STDLIB_DIR') }}

requirements:
  build:
    - python {{ environ.get('PYTHON_VERSION') }}
    - occt={{ OCCT_VER }}
  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - occt={{ OCCT_VER }}

test:
  imports:
    - OCP
    - OCP.WNT # [win]
    - OCP.Xw # [linux]
    - OCP.Cocoa # [osx]

about:
  summary: Python wrapper for OCCT
