{% set OCCT_VER = "7.5.3" %}
{% set OCP_TWEAK = "0" %}

package:
  name: ocp
  version: {{OCCT_VER}}.{{OCP_TWEAK}}

source:
  path: ..

build:
  string: {{ environ.get('BUILD_STRING') }}_{{ 'py'+environ.get('PYTHON_VERSION') }}
  script:
    {% if not os.path.exists('bld') %}
    - cmake -B bld -S . -G Ninja && cmake --build bld
    {% endif %}
    - cmake --install bld --prefix {{ environ.get('STDLIB_DIR') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake 3.16
    - clangdev
    - python-clang
    - boost=1.74.0
    - occt={{ OCCT_VER }}
    - pybind11>=2.6.*
    - python
    - joblib
    - toml
    - cmake>=3.16
    - ninja
    - click
    - jinja2
    - logzero
    - pandas
    - path
    - pyparsing
    - schema
    - tqdm
    - toposort
  host:
    - python {{ environ.get('PYTHON_VERSION') }}
    - occt {{OCCT_VER}}
  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - occt {{OCCT_VER}}

test:
  requires:
    - python
  imports:
    - OCP

about:
  summary: Python wrapper for OCCT
