package:
  name: ocp
  version: 7.4

source:
  path: ..

build:
  string: {{ environ.get('BUILD_STRING') }}_{{ 'py'+environ.get('PYTHON_VERSION') }}
  script: mkdir -p {{ environ.get('SP_DIR') }} && cp OCP.cp*-*.* {{ environ.get('SP_DIR') }}

requirements:
  host:
    - python {{ environ.get('PYTHON_VERSION') }}
    - occt 7.4.*
  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - occt 7.4.* 

test:
  requires:
    - python 
  imports:
    - OCP

about:
  summary: Python wrapper for OCCT
