{% set OCCT_VER = "7.6.0" %}
{% set OCP_TWEAK = "alpha" %}

package:
  name: ocp
  version: {{OCCT_VER}}.{{OCP_TWEAK}}

source:
  path: ..

build:
  string: {{ environ.get('BUILD_STRING') }}_{{ 'py'+environ.get('PYTHON_VERSION') }}
  script:
    {% if not os.path.exists('build') %}
    - cmake -B build -S . -G Ninja -DN_PROC={{ environ.get('CPU_COUNT') }} && cmake --build build
    {% endif %}
    - cmake --install build --prefix {{ environ.get('STDLIB_DIR') }}

requirements:
  build:
    - cmake 3.16
    - clangdev
    - python-clang
    - boost=1.74.0
    - occt={{ OCCT_VER }}
    - pybind11>=2.6.*
    - python {{ environ.get('PYTHON_VERSION') }}
    - joblib
    - toml
    - cmake>=3.16
    - ninja
    - click
    - jinja2
    - logzero
    - pandas
    - path
    - pyparsing
    - schema
    - tqdm
    - toposort
  host:
    - python {{ environ.get('PYTHON_VERSION') }}
    - occt {{OCCT_VER}}
  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - occt {{OCCT_VER}}
    - {{ pin_compatible('vtk', max_pin='x.x') }}

test:
  requires:
    - python
  imports:
    - OCP

about:
  summary: Python wrapper for OCCT
