package:
  name: ocp
  version: 7.6.0alpha

source:
  path: ..

build:
  string: {{ environ.get('BUILD_STRING') }}_{{ 'py'+environ.get('PYTHON_VERSION') }}

requirements:
  build:
    - cmake 3.16
  host:
    - python {{ environ.get('PYTHON_VERSION') }}
    - occt 7.6.0
  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - occt 7.6.0
    - vtk 9.0.*

test:
  requires:
    - python 
  imports:
    - OCP

about:
  summary: Python wrapper for OCCT
