name: 'Install micromamba'
runs:
  using: 'composite'
  steps:
    - name: install micromamba
      if: ${{ contains(runner.os,'Linux')}}
      shell: bash
      run: "bash <(curl -L https://micro.mamba.pm/install.sh)"

    - name: add to path
      if: ${{ contains(runner.os,'Linux')}}
      shell: bash
      run: echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_PATH

    - name: install mambaforge
      if: ${{ contains(runner.os,'Windows')}}
      shell: bash
      run: choco install mambaforge

    - name: add to path
      if: ${{ contains(runner.os,'Windows')}}
      shell: bash
      echo "PATH=$PATH:/c/tools/mambaforge/Library/bin" >> $GIHUB_PATH

    - name: install micromamba
      if: ${{ contains(runner.os,'Windows')}}
      shell: bash
      run: echo $PATH && mamba install micromamba

    - name: 'Install (MacOS)'
      if: contains(runner.os,'mac')
      shell: bash
      run: brew install micromamba

    - name: 'Check installation'
      shell: bash
      run: which micromamba && micromamba info
