#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <Expr_GeneralFunction.hxx>
#include <Expr_InvalidFunction.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Expr_GeneralExpression.hxx>
#include <Expr_GeneralRelation.hxx>
#include <Expr_GeneralExpression.hxx>
#include <Expr_NumericValue.hxx>
#include <Expr_NamedExpression.hxx>
#include <Expr_NamedConstant.hxx>
#include <Expr_NamedUnknown.hxx>
#include <Expr_UnaryExpression.hxx>
#include <Expr_Absolute.hxx>
#include <Expr_ArcCosine.hxx>
#include <Expr_ArcSine.hxx>
#include <Expr_ArcTangent.hxx>
#include <Expr_ArgCosh.hxx>
#include <Expr_ArgSinh.hxx>
#include <Expr_ArgTanh.hxx>
#include <Expr_Cosh.hxx>
#include <Expr_Cosine.hxx>
#include <Expr_Exponential.hxx>
#include <Expr_LogOf10.hxx>
#include <Expr_LogOfe.hxx>
#include <Expr_Sign.hxx>
#include <Expr_Sine.hxx>
#include <Expr_Sinh.hxx>
#include <Expr_Square.hxx>
#include <Expr_SquareRoot.hxx>
#include <Expr_Tangent.hxx>
#include <Expr_Tanh.hxx>
#include <Expr_UnaryFunction.hxx>
#include <Expr_UnaryMinus.hxx>
#include <Expr_BinaryExpression.hxx>
#include <Expr_BinaryFunction.hxx>
#include <Expr_Difference.hxx>
#include <Expr_Division.hxx>
#include <Expr_Exponentiate.hxx>
#include <Expr_PolyExpression.hxx>
#include <Expr_PolyFunction.hxx>
#include <Expr_Product.hxx>
#include <Expr_Sum.hxx>
#include <Expr_UnknownIterator.hxx>
#include <Expr_GeneralRelation.hxx>
#include <Expr_SingleRelation.hxx>
#include <Expr_Different.hxx>
#include <Expr_Equal.hxx>
#include <Expr_GreaterThan.hxx>
#include <Expr_GreaterThanOrEqual.hxx>
#include <Expr_LessThan.hxx>
#include <Expr_LessThanOrEqual.hxx>
#include <Expr_SystemRelation.hxx>
#include <Expr_RelationIterator.hxx>
#include <Expr_RUIterator.hxx>
#include <Expr_GeneralFunction.hxx>
#include <Expr_NamedFunction.hxx>
#include <Expr_FunctionDerivative.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_DimensionMismatch.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_GeneralExpression.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_InvalidOperand.hxx>
#include <Expr_NamedUnknown.hxx>
#include <Standard_NoMoreObject.hxx>
#include <Standard_NoSuchObject.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_GeneralExpression.hxx>
#include <TCollection_AsciiString.hxx>
#include <Expr_NamedUnknown.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Expr_NamedUnknown.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_OutOfRange.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_GeneralExpression.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_GeneralExpression.hxx>
#include <TCollection_AsciiString.hxx>
#include <Expr_GeneralFunction.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Expr_NotAssigned.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_InvalidAssignment.hxx>
#include <Expr_InvalidOperand.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NoMoreObject.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_GeneralExpression.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_InvalidOperand.hxx>
#include <Expr_NamedUnknown.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_GeneralExpression.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_GeneralExpression.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_GeneralExpression.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_InvalidOperand.hxx>
#include <Expr_NamedUnknown.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Expr_GeneralExpression.hxx>
#include <Standard_OutOfRange.hxx>
#include <Expr_NamedUnknown.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NoMoreObject.hxx>
#include <Expr_GeneralRelation.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Expr_GeneralExpression.hxx>
#include <Expr_NamedUnknown.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedFunction.hxx>
#include <TCollection_AsciiString.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Expr_GeneralFunction.hxx>
#include <Expr_InvalidFunction.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Expr_GeneralExpression.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_InvalidOperand.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>
#include <Standard_NumericError.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_NamedUnknown.hxx>
#include <TCollection_AsciiString.hxx>

// module includes
#include <Expr_BinaryFunction.hxx>
#include <Expr_SequenceOfGeneralExpression.hxx>
#include <Expr.hxx>
#include <Expr_GeneralFunction.hxx>
#include <Expr_SystemRelation.hxx>
#include <Expr_SquareRoot.hxx>
#include <Expr_PolyExpression.hxx>
#include <Expr_RelationIterator.hxx>
#include <Expr_ArcSine.hxx>
#include <Expr_Equal.hxx>
#include <Expr_Array1OfNamedUnknown.hxx>
#include <Expr_MapOfNamedUnknown.hxx>
#include <Expr_Difference.hxx>
#include <Expr_ArcTangent.hxx>
#include <Expr_NamedConstant.hxx>
#include <Expr_InvalidFunction.hxx>
#include <Expr_Operators.hxx>
#include <Expr_ArgCosh.hxx>
#include <Expr_GeneralRelation.hxx>
#include <Expr_Cosine.hxx>
#include <Expr_Different.hxx>
#include <Expr_PolyFunction.hxx>
#include <Expr_NamedUnknown.hxx>
#include <Expr_Absolute.hxx>
#include <Expr_UnknownIterator.hxx>
#include <Expr_GreaterThanOrEqual.hxx>
#include <Expr_NamedExpression.hxx>
#include <Expr_UnaryExpression.hxx>
#include <Expr_GreaterThan.hxx>
#include <Expr_Division.hxx>
#include <Expr_LessThan.hxx>
#include <Expr_LessThanOrEqual.hxx>
#include <Expr_InvalidAssignment.hxx>
#include <Expr_ExprFailure.hxx>
#include <Expr_BinaryExpression.hxx>
#include <Expr_Sinh.hxx>
#include <Expr_LogOf10.hxx>
#include <Expr_SingleRelation.hxx>
#include <Expr_Tanh.hxx>
#include <Expr_RUIterator.hxx>
#include <Expr_Sum.hxx>
#include <Expr_NotEvaluable.hxx>
#include <Expr_Tangent.hxx>
#include <Expr_FunctionDerivative.hxx>
#include <Expr_NotAssigned.hxx>
#include <Expr_NumericValue.hxx>
#include <Expr_Array1OfSingleRelation.hxx>
#include <Expr_SequenceOfGeneralRelation.hxx>
#include <Expr_Cosh.hxx>
#include <Expr_ArcCosine.hxx>
#include <Expr_Product.hxx>
#include <Expr_ArgSinh.hxx>
#include <Expr_UnaryFunction.hxx>
#include <Expr_UnaryMinus.hxx>
#include <Expr_Exponentiate.hxx>
#include <Expr_ArgTanh.hxx>
#include <Expr_LogOfe.hxx>
#include <Expr_Square.hxx>
#include <Expr_NamedFunction.hxx>
#include <Expr_InvalidOperand.hxx>
#include <Expr_Sign.hxx>
#include <Expr_Sine.hxx>
#include <Expr_Array1OfGeneralExpression.hxx>
#include <Expr_GeneralExpression.hxx>
#include <Expr_Exponential.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/Expr_BinaryFunction.hxx
// ./opencascade/Expr_SequenceOfGeneralExpression.hxx
// ./opencascade/Expr.hxx
// ./opencascade/Expr_GeneralFunction.hxx
// ./opencascade/Expr_SystemRelation.hxx
// ./opencascade/Expr_SquareRoot.hxx
// ./opencascade/Expr_PolyExpression.hxx
// ./opencascade/Expr_RelationIterator.hxx
// ./opencascade/Expr_ArcSine.hxx
// ./opencascade/Expr_Equal.hxx
// ./opencascade/Expr_Array1OfNamedUnknown.hxx
// ./opencascade/Expr_MapOfNamedUnknown.hxx
// ./opencascade/Expr_Difference.hxx
// ./opencascade/Expr_ArcTangent.hxx
// ./opencascade/Expr_NamedConstant.hxx
// ./opencascade/Expr_InvalidFunction.hxx
// ./opencascade/Expr_Operators.hxx
// ./opencascade/Expr_ArgCosh.hxx
// ./opencascade/Expr_GeneralRelation.hxx
// ./opencascade/Expr_Cosine.hxx
// ./opencascade/Expr_Different.hxx
// ./opencascade/Expr_PolyFunction.hxx
// ./opencascade/Expr_NamedUnknown.hxx
// ./opencascade/Expr_Absolute.hxx
// ./opencascade/Expr_UnknownIterator.hxx
// ./opencascade/Expr_GreaterThanOrEqual.hxx
// ./opencascade/Expr_NamedExpression.hxx
// ./opencascade/Expr_UnaryExpression.hxx
// ./opencascade/Expr_GreaterThan.hxx
// ./opencascade/Expr_Division.hxx
// ./opencascade/Expr_LessThan.hxx
// ./opencascade/Expr_LessThanOrEqual.hxx
// ./opencascade/Expr_InvalidAssignment.hxx
// ./opencascade/Expr_ExprFailure.hxx
// ./opencascade/Expr_BinaryExpression.hxx
// ./opencascade/Expr_Sinh.hxx
// ./opencascade/Expr_LogOf10.hxx
// ./opencascade/Expr_SingleRelation.hxx
// ./opencascade/Expr_Tanh.hxx
// ./opencascade/Expr_RUIterator.hxx
// ./opencascade/Expr_Sum.hxx
// ./opencascade/Expr_NotEvaluable.hxx
// ./opencascade/Expr_Tangent.hxx
// ./opencascade/Expr_FunctionDerivative.hxx
// ./opencascade/Expr_NotAssigned.hxx
// ./opencascade/Expr_NumericValue.hxx
// ./opencascade/Expr_Array1OfSingleRelation.hxx
// ./opencascade/Expr_SequenceOfGeneralRelation.hxx
// ./opencascade/Expr_Cosh.hxx
// ./opencascade/Expr_ArcCosine.hxx
// ./opencascade/Expr_Product.hxx
// ./opencascade/Expr_ArgSinh.hxx
// ./opencascade/Expr_UnaryFunction.hxx
// ./opencascade/Expr_UnaryMinus.hxx
// ./opencascade/Expr_Exponentiate.hxx
// ./opencascade/Expr_ArgTanh.hxx
// ./opencascade/Expr_LogOfe.hxx
// ./opencascade/Expr_Square.hxx
// ./opencascade/Expr_NamedFunction.hxx
// ./opencascade/Expr_InvalidOperand.hxx
// ./opencascade/Expr_Sign.hxx
// ./opencascade/Expr_Sine.hxx
// ./opencascade/Expr_Array1OfGeneralExpression.hxx
// ./opencascade/Expr_GeneralExpression.hxx
// ./opencascade/Expr_Exponential.hxx

// user-defined post
