#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_Signature.hxx>
#include <IFSelect_SignCounter.hxx>
#include <Interface_Graph.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_CheckIterator.hxx>
#include <Interface_InterfaceModel.hxx>
#include <IFSelect_SignCounter.hxx>
#include <Interface_InterfaceError.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_Graph.hxx>
#include <IFGraph_SubPartsIterator.hxx>
#include <IFSelect_SessionPilot.hxx>
#include <IFSelect_IntParam.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_IntParam.hxx>
#include <Interface_InterfaceError.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_Graph.hxx>
#include <IFGraph_SubPartsIterator.hxx>
#include <IFSelect_WorkSession.hxx>
#include <IFSelect_ContextModif.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_CopyTool.hxx>
#include <Interface_TypedValue.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <Interface_InterfaceModel.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_ShareOut.hxx>
#include <Interface_CheckIterator.hxx>
#include <IFSelect_ShareOutResult.hxx>
#include <IFSelect_WorkLibrary.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_CopyTool.hxx>
#include <Interface_Graph.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_CopyControl.hxx>
#include <IFSelect_Transformer.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <IFSelect_Selection.hxx>
#include <Interface_InterfaceError.hxx>
#include <IFSelect_SelectionIterator.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <IFGraph_SubPartsIterator.hxx>
#include <Standard_OutOfRange.hxx>
#include <Interface_EntityIterator.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <Interface_InterfaceModel.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_InterfaceModel.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_Editor.hxx>
#include <Interface_InterfaceModel.hxx>
#include <IFSelect_ListEditor.hxx>
#include <Message_Messenger.hxx>
#include <Interface_InterfaceModel.hxx>
#include <IFSelect_Signature.hxx>
#include <IFSelect_Selection.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Graph.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_CopyControl.hxx>
#include <Interface_CopyTool.hxx>
#include <Interface_EntityIterator.hxx>
#include <IFSelect_GeneralModifier.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_InterfaceModel.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Protocol.hxx>
#include <IFSelect_ContextWrite.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_CopyTool.hxx>
#include <Message_Messenger.hxx>
#include <IFSelect_IntParam.hxx>
#include <Standard_DomainError.hxx>
#include <Interface_InterfaceModel.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_IntParam.hxx>
#include <Interface_InterfaceError.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_Graph.hxx>
#include <IFGraph_SubPartsIterator.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_SelectDeduct.hxx>
#include <Interface_Graph.hxx>
#include <IFSelect_SelectionIterator.hxx>
#include <IFSelect_EditForm.hxx>
#include <IFSelect_ContextModif.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_CopyTool.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_TypedValue.hxx>
#include <IFSelect_EditForm.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_TypedValue.hxx>
#include <Message_Messenger.hxx>
#include <IFSelect_EditForm.hxx>
#include <IFSelect_ListEditor.hxx>
#include <Interface_InterfaceModel.hxx>
#include <IFSelect_ShareOut.hxx>
#include <IFSelect_WorkLibrary.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_HGraph.hxx>
#include <Interface_GTool.hxx>
#include <IFSelect_ModelCopier.hxx>
#include <IFSelect_Signature.hxx>
#include <Interface_Graph.hxx>
#include <IFSelect_IntParam.hxx>
#include <IFSelect_Selection.hxx>
#include <Interface_EntityIterator.hxx>
#include <IFSelect_SelectionIterator.hxx>
#include <IFSelect_SignCounter.hxx>
#include <IFSelect_Dispatch.hxx>
#include <IFSelect_GeneralModifier.hxx>
#include <IFSelect_Modifier.hxx>
#include <IFSelect_Transformer.hxx>
#include <IFSelect_PacketList.hxx>
#include <Message_Messenger.hxx>
#include <IFSelect_SignatureList.hxx>
#include <IFSelect_WorkSession.hxx>
#include <IFSelect_Signature.hxx>
#include <IFSelect_SignMultiple.hxx>
#include <IFSelect_SignType.hxx>
#include <IFSelect_SignCategory.hxx>
#include <IFSelect_SignValidity.hxx>
#include <IFSelect_SignAncestor.hxx>
#include <IFSelect_ShareOut.hxx>
#include <IFSelect_AppliedModifiers.hxx>
#include <IFSelect_ShareOutResult.hxx>
#include <IFSelect_PacketList.hxx>
#include <IFSelect_Dispatch.hxx>
#include <IFSelect_DispGlobal.hxx>
#include <IFSelect_DispPerOne.hxx>
#include <IFSelect_DispPerCount.hxx>
#include <IFSelect_DispPerSignature.hxx>
#include <IFSelect_DispPerFiles.hxx>
#include <IFSelect_SelectionIterator.hxx>
#include <IFSelect_Selection.hxx>
#include <IFSelect_SelectBase.hxx>
#include <IFSelect_SelectModelRoots.hxx>
#include <IFSelect_SelectModelEntities.hxx>
#include <IFSelect_SelectEntityNumber.hxx>
#include <IFSelect_SelectPointed.hxx>
#include <IFSelect_SelectCombine.hxx>
#include <IFSelect_SelectUnion.hxx>
#include <IFSelect_SelectIntersection.hxx>
#include <IFSelect_SelectControl.hxx>
#include <IFSelect_SelectDiff.hxx>
#include <IFSelect_SelectDeduct.hxx>
#include <IFSelect_SelectShared.hxx>
#include <IFSelect_SelectSharing.hxx>
#include <IFSelect_SelectAnyList.hxx>
#include <IFSelect_SelectInList.hxx>
#include <IFSelect_SelectSuite.hxx>
#include <IFSelect_SelectExtract.hxx>
#include <IFSelect_SelectUnknownEntities.hxx>
#include <IFSelect_SelectErrorEntities.hxx>
#include <IFSelect_SelectIncorrectEntities.hxx>
#include <IFSelect_SelectRoots.hxx>
#include <IFSelect_SelectRootComps.hxx>
#include <IFSelect_SelectRange.hxx>
#include <IFSelect_SelectAnyType.hxx>
#include <IFSelect_SelectType.hxx>
#include <IFSelect_SelectSignature.hxx>
#include <IFSelect_SelectFlag.hxx>
#include <IFSelect_SelectSent.hxx>
#include <IFSelect_SelectExplore.hxx>
#include <IFSelect_SelectSignedShared.hxx>
#include <IFSelect_SelectSignedSharing.hxx>
#include <IFSelect_IntParam.hxx>
#include <IFSelect_SignatureList.hxx>
#include <IFSelect_CheckCounter.hxx>
#include <IFSelect_SignCounter.hxx>
#include <IFSelect_GraphCounter.hxx>
#include <IFSelect_Editor.hxx>
#include <IFSelect_ParamEditor.hxx>
#include <IFSelect_EditForm.hxx>
#include <IFSelect_ListEditor.hxx>
#include <IFSelect_ContextModif.hxx>
#include <IFSelect_ContextWrite.hxx>
#include <IFSelect_Transformer.hxx>
#include <IFSelect_TransformStandard.hxx>
#include <IFSelect_ModelCopier.hxx>
#include <IFSelect_GeneralModifier.hxx>
#include <IFSelect_Modifier.hxx>
#include <IFSelect_ModifReorder.hxx>
#include <IFSelect_ModifEditForm.hxx>
#include <IFSelect_WorkSession.hxx>
#include <IFSelect_WorkLibrary.hxx>
#include <IFSelect_SessionFile.hxx>
#include <IFSelect_SessionDumper.hxx>
#include <IFSelect_BasicDumper.hxx>
#include <IFSelect_Activator.hxx>
#include <IFSelect_SessionPilot.hxx>
#include <IFSelect_Act.hxx>
#include <IFSelect_Functions.hxx>
#include <IFSelect_SessionFile.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Graph.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_CheckIterator.hxx>
#include <Interface_InterfaceModel.hxx>
#include <TCollection_AsciiString.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_Graph.hxx>
#include <IFGraph_SubPartsIterator.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <Interface_InterfaceModel.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_InterfaceModel.hxx>
#include <IFSelect_Selection.hxx>
#include <IFSelect_Dispatch.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_Signature.hxx>
#include <Interface_Graph.hxx>
#include <Interface_EntityIterator.hxx>
#include <IFSelect_IntParam.hxx>
#include <Standard_OutOfRange.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_ContextModif.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_CopyTool.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_SessionFile.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Message_Messenger.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <IFSelect_SelectionIterator.hxx>
#include <TCollection_AsciiString.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_Graph.hxx>
#include <IFGraph_SubPartsIterator.hxx>
#include <TCollection_HAsciiString.hxx>
#include <Interface_InterfaceError.hxx>
#include <IFSelect_Modifier.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_WorkSession.hxx>
#include <IFSelect_Dispatch.hxx>
#include <IFSelect_SelectPointed.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <IFSelect_SelectionIterator.hxx>
#include <IFSelect_Selection.hxx>
#include <Interface_CopyControl.hxx>
#include <IFSelect_Modifier.hxx>
#include <Interface_Graph.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_CheckIterator.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_CopyTool.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <IFSelect_SelectionIterator.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Protocol.hxx>
#include <IFSelect_AppliedModifiers.hxx>
#include <Interface_HGraph.hxx>
#include <IFSelect_GeneralModifier.hxx>
#include <Interface_Graph.hxx>
#include <IFSelect_ShareOut.hxx>
#include <IFSelect_Dispatch.hxx>
#include <Interface_InterfaceError.hxx>
#include <IFSelect_PacketList.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <IFSelect_Signature.hxx>
#include <Interface_Graph.hxx>
#include <Interface_EntityIterator.hxx>
#include <IFSelect_SelectionIterator.hxx>
#include <IFSelect_WorkSession.hxx>
#include <IFSelect_WorkLibrary.hxx>
#include <IFSelect_SignCounter.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <Interface_InterfaceModel.hxx>
#include <TCollection_AsciiString.hxx>

// module includes
#include <IFSelect_SelectIntersection.hxx>
#include <IFSelect_SelectSignature.hxx>
#include <IFSelect_PacketList.hxx>
#include <IFSelect_CheckCounter.hxx>
#include <IFSelect_DispPerSignature.hxx>
#include <IFSelect_Activator.hxx>
#include <IFSelect_SelectEntityNumber.hxx>
#include <IFSelect_DispPerFiles.hxx>
#include <IFSelect_HSeqOfSelection.hxx>
#include <IFSelect_SessionFile.hxx>
#include <IFSelect_Modifier.hxx>
#include <IFSelect_ListEditor.hxx>
#include <IFSelect_SelectRootComps.hxx>
#include <IFSelect_ModelCopier.hxx>
#include <IFSelect_PrintCount.hxx>
#include <IFSelect_SelectPointed.hxx>
#include <IFSelect_Dispatch.hxx>
#include <IFSelect_SelectInList.hxx>
#include <IFSelect_SelectType.hxx>
#include <IFSelect_PrintFail.hxx>
#include <IFSelect_TSeqOfSelection.hxx>
#include <IFSelect_SelectAnyType.hxx>
#include <IFSelect_SelectExtract.hxx>
#include <IFSelect_SelectErrorEntities.hxx>
#include <IFSelect_EditForm.hxx>
#include <IFSelect_SignAncestor.hxx>
#include <IFSelect_SignCounter.hxx>
#include <IFSelect_SelectModelEntities.hxx>
#include <IFSelect_ContextModif.hxx>
#include <IFSelect_SignValidity.hxx>
#include <IFSelect_SelectUnknownEntities.hxx>
#include <IFSelect_WorkLibrary.hxx>
#include <IFSelect_SelectIncorrectEntities.hxx>
#include <IFSelect_RemainMode.hxx>
#include <IFSelect_SelectRange.hxx>
#include <IFSelect_SequenceOfInterfaceModel.hxx>
#include <IFSelect_SelectModelRoots.hxx>
#include <IFSelect_DispPerCount.hxx>
#include <IFSelect_SelectUnion.hxx>
#include <IFSelect_GraphCounter.hxx>
#include <IFSelect_SelectBase.hxx>
#include <IFSelect_ModifEditForm.hxx>
#include <IFSelect_ParamEditor.hxx>
#include <IFSelect_Editor.hxx>
#include <IFSelect_WorkSession.hxx>
#include <IFSelect.hxx>
#include <IFSelect_BasicDumper.hxx>
#include <IFSelect_SelectFlag.hxx>
#include <IFSelect_Transformer.hxx>
#include <IFSelect_Act.hxx>
#include <IFSelect_ReturnStatus.hxx>
#include <IFSelect_DispPerOne.hxx>
#include <IFSelect_SelectRoots.hxx>
#include <IFSelect_SignMultiple.hxx>
#include <IFSelect_IntParam.hxx>
#include <IFSelect_GeneralModifier.hxx>
#include <IFSelect_ActFunc.hxx>
#include <IFSelect_SelectSignedSharing.hxx>
#include <IFSelect_SelectAnyList.hxx>
#include <IFSelect_ModifReorder.hxx>
#include <IFSelect_SessionDumper.hxx>
#include <IFSelect_SelectExplore.hxx>
#include <IFSelect_Signature.hxx>
#include <IFSelect_AppliedModifiers.hxx>
#include <IFSelect_SignatureList.hxx>
#include <IFSelect_SelectShared.hxx>
#include <IFSelect_Selection.hxx>
#include <IFSelect_DispGlobal.hxx>
#include <IFSelect_SequenceOfAppliedModifiers.hxx>
#include <IFSelect_ShareOut.hxx>
#include <IFSelect_Functions.hxx>
#include <IFSelect_SelectDeduct.hxx>
#include <IFSelect_TransformStandard.hxx>
#include <IFSelect_TSeqOfDispatch.hxx>
#include <IFSelect_SignType.hxx>
#include <IFSelect_SequenceOfGeneralModifier.hxx>
#include <IFSelect_SignCategory.hxx>
#include <IFSelect_SelectSharing.hxx>
#include <IFSelect_SelectControl.hxx>
#include <IFSelect_ContextWrite.hxx>
#include <IFSelect_ShareOutResult.hxx>
#include <IFSelect_SelectDiff.hxx>
#include <IFSelect_EditValue.hxx>
#include <IFSelect_SelectionIterator.hxx>
#include <IFSelect_SelectSuite.hxx>
#include <IFSelect_SelectSignedShared.hxx>
#include <IFSelect_SelectCombine.hxx>
#include <IFSelect_SessionPilot.hxx>
#include <IFSelect_SelectSent.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/IFSelect_SelectIntersection.hxx
// ./opencascade/IFSelect_SelectSignature.hxx
// ./opencascade/IFSelect_PacketList.hxx
// ./opencascade/IFSelect_CheckCounter.hxx
// ./opencascade/IFSelect_DispPerSignature.hxx
// ./opencascade/IFSelect_Activator.hxx
// ./opencascade/IFSelect_SelectEntityNumber.hxx
// ./opencascade/IFSelect_DispPerFiles.hxx
// ./opencascade/IFSelect_HSeqOfSelection.hxx
// ./opencascade/IFSelect_SessionFile.hxx
// ./opencascade/IFSelect_Modifier.hxx
// ./opencascade/IFSelect_ListEditor.hxx
// ./opencascade/IFSelect_SelectRootComps.hxx
// ./opencascade/IFSelect_ModelCopier.hxx
// ./opencascade/IFSelect_PrintCount.hxx
// ./opencascade/IFSelect_SelectPointed.hxx
// ./opencascade/IFSelect_Dispatch.hxx
// ./opencascade/IFSelect_SelectInList.hxx
// ./opencascade/IFSelect_SelectType.hxx
// ./opencascade/IFSelect_PrintFail.hxx
// ./opencascade/IFSelect_TSeqOfSelection.hxx
// ./opencascade/IFSelect_SelectAnyType.hxx
// ./opencascade/IFSelect_SelectExtract.hxx
// ./opencascade/IFSelect_SelectErrorEntities.hxx
// ./opencascade/IFSelect_EditForm.hxx
// ./opencascade/IFSelect_SignAncestor.hxx
// ./opencascade/IFSelect_SignCounter.hxx
// ./opencascade/IFSelect_SelectModelEntities.hxx
// ./opencascade/IFSelect_ContextModif.hxx
// ./opencascade/IFSelect_SignValidity.hxx
// ./opencascade/IFSelect_SelectUnknownEntities.hxx
// ./opencascade/IFSelect_WorkLibrary.hxx
// ./opencascade/IFSelect_SelectIncorrectEntities.hxx
// ./opencascade/IFSelect_RemainMode.hxx
// ./opencascade/IFSelect_SelectRange.hxx
// ./opencascade/IFSelect_SequenceOfInterfaceModel.hxx
// ./opencascade/IFSelect_SelectModelRoots.hxx
// ./opencascade/IFSelect_DispPerCount.hxx
// ./opencascade/IFSelect_SelectUnion.hxx
// ./opencascade/IFSelect_GraphCounter.hxx
// ./opencascade/IFSelect_SelectBase.hxx
// ./opencascade/IFSelect_ModifEditForm.hxx
// ./opencascade/IFSelect_ParamEditor.hxx
// ./opencascade/IFSelect_Editor.hxx
// ./opencascade/IFSelect_WorkSession.hxx
// ./opencascade/IFSelect.hxx
// ./opencascade/IFSelect_BasicDumper.hxx
// ./opencascade/IFSelect_SelectFlag.hxx
// ./opencascade/IFSelect_Transformer.hxx
// ./opencascade/IFSelect_Act.hxx
// ./opencascade/IFSelect_ReturnStatus.hxx
// ./opencascade/IFSelect_DispPerOne.hxx
// ./opencascade/IFSelect_SelectRoots.hxx
// ./opencascade/IFSelect_SignMultiple.hxx
// ./opencascade/IFSelect_IntParam.hxx
// ./opencascade/IFSelect_GeneralModifier.hxx
// ./opencascade/IFSelect_ActFunc.hxx
// ./opencascade/IFSelect_SelectSignedSharing.hxx
// ./opencascade/IFSelect_SelectAnyList.hxx
// ./opencascade/IFSelect_ModifReorder.hxx
// ./opencascade/IFSelect_SessionDumper.hxx
// ./opencascade/IFSelect_SelectExplore.hxx
// ./opencascade/IFSelect_Signature.hxx
// ./opencascade/IFSelect_AppliedModifiers.hxx
// ./opencascade/IFSelect_SignatureList.hxx
// ./opencascade/IFSelect_SelectShared.hxx
// ./opencascade/IFSelect_Selection.hxx
// ./opencascade/IFSelect_DispGlobal.hxx
// ./opencascade/IFSelect_SequenceOfAppliedModifiers.hxx
// ./opencascade/IFSelect_ShareOut.hxx
// ./opencascade/IFSelect_Functions.hxx
// ./opencascade/IFSelect_SelectDeduct.hxx
// ./opencascade/IFSelect_TransformStandard.hxx
// ./opencascade/IFSelect_TSeqOfDispatch.hxx
// ./opencascade/IFSelect_SignType.hxx
// ./opencascade/IFSelect_SequenceOfGeneralModifier.hxx
// ./opencascade/IFSelect_SignCategory.hxx
// ./opencascade/IFSelect_SelectSharing.hxx
// ./opencascade/IFSelect_SelectControl.hxx
// ./opencascade/IFSelect_ContextWrite.hxx
// ./opencascade/IFSelect_ShareOutResult.hxx
// ./opencascade/IFSelect_SelectDiff.hxx
// ./opencascade/IFSelect_EditValue.hxx
// ./opencascade/IFSelect_SelectionIterator.hxx
// ./opencascade/IFSelect_SelectSuite.hxx
// ./opencascade/IFSelect_SelectSignedShared.hxx
// ./opencascade/IFSelect_SelectCombine.hxx
// ./opencascade/IFSelect_SessionPilot.hxx
// ./opencascade/IFSelect_SelectSent.hxx

// user-defined post
