#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <Interface_GTool.hxx>
#include <Interface_CheckFailure.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_Graph.hxx>
#include <Interface_HGraph.hxx>
#include <Interface_Check.hxx>
#include <Message_Messenger.hxx>
#include <Interface_CheckIterator.hxx>
#include <Interface_EntityIterator.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_ParamSet.hxx>
#include <Standard_NoSuchObject.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_FileParameter.hxx>
#include <Interface_ParamList.hxx>
#include <Interface_NodeOfGeneralLib.hxx>
#include <Standard_NoSuchObject.hxx>
#include <Interface_GeneralModule.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_GlobalNodeOfGeneralLib.hxx>
#include <Interface_HGraph.hxx>
#include <Standard_DomainError.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_GeneralLib.hxx>
#include <Interface_GTool.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_Graph.hxx>
#include <Interface_EntityIterator.hxx>
#include <Message_Messenger.hxx>
#include <Interface_InterfaceError.hxx>
#include <Standard_DomainError.hxx>
#include <Interface_ReaderModule.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_ReaderLib.hxx>
#include <Interface_NodeOfReaderLib.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_GeneralLib.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_GTool.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_ShareTool.hxx>
#include <Interface_Check.hxx>
#include <Interface_CopyTool.hxx>
#include <TCollection_HAsciiString.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_IntVal.hxx>
#include <Standard_NoMoreObject.hxx>
#include <Interface_Check.hxx>
#include <Interface_GTool.hxx>
#include <Interface_InterfaceMismatch.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_ReportEntity.hxx>
#include <Interface_CheckIterator.hxx>
#include <Interface_GeneralLib.hxx>
#include <Interface_EntityIterator.hxx>
#include <Message_Messenger.hxx>
#include <Interface_GlobalNodeOfReaderLib.hxx>
#include <Interface_ReaderModule.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_ReaderLib.hxx>
#include <Interface_Check.hxx>
#include <Interface_NodeOfReaderLib.hxx>
#include <Standard_NoSuchObject.hxx>
#include <Interface_ReaderModule.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_GlobalNodeOfReaderLib.hxx>
#include <Standard_NoSuchObject.hxx>
#include <Interface_InterfaceMismatch.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_CopyTool.hxx>
#include <Interface_GlobalNodeOfGeneralLib.hxx>
#include <Interface_GeneralModule.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_GeneralLib.hxx>
#include <TCollection_HAsciiString.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_Graph.hxx>
#include <Interface_Check.hxx>
#include <Interface_InterfaceModel.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Standard_OutOfRange.hxx>
#include <Interface_InterfaceError.hxx>
#include <Standard_NullObject.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_FileReaderData.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Message_Messenger.hxx>
#include <Standard_NoSuchObject.hxx>
#include <Interface_Check.hxx>
#include <Interface_GeneralLib.hxx>
#include <Interface_ReaderLib.hxx>
#include <Interface_GeneralLib.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_GTool.hxx>
#include <Interface_EntityIterator.hxx>
#include <Standard_DomainError.hxx>
#include <Interface_FileReaderData.hxx>
#include <Interface_Check.hxx>
#include <Message_Msg.hxx>
#include <Message_Messenger.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_ShareTool.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_SignType.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_GeneralModule.hxx>
#include <Standard_OutOfRange.hxx>
#include <Standard_NullObject.hxx>
#include <Interface_EntityList.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_CopyControl.hxx>
#include <Interface_CopyMap.hxx>
#include <Interface_GeneralModule.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_ParamList.hxx>
#include <Standard_OutOfRange.hxx>
#include <Interface_FileParameter.hxx>
#include <Interface_InterfaceError.hxx>
#include <Message_Messenger.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_GeneralLib.hxx>
#include <Interface_GTool.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_Graph.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_IntVal.hxx>
#include <Message_Messenger.hxx>
#include <Standard_OutOfMemory.hxx>
#include <Interface_Graph.hxx>
#include <Interface_GeneralModule.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_GeneralLib.hxx>
#include <Interface_NodeOfGeneralLib.hxx>
#include <TCollection_AsciiString.hxx>
#include <Interface_InterfaceError.hxx>

// module includes
#include <Interface_CheckTool.hxx>
#include <Interface_FileParameter.hxx>
#include <Interface_InterfaceMismatch.hxx>
#include <Interface_FileReaderData.hxx>
#include <Interface_SequenceOfCheck.hxx>
#include <Interface_GeneralLib.hxx>
#include <Interface_Version.hxx>
#include <Interface_ShareTool.hxx>
#include <Interface_CopyControl.hxx>
#include <Interface_LineBuffer.hxx>
#include <Interface_MSG.hxx>
#include <Interface_CheckFailure.hxx>
#include <Interface_GlobalNodeOfReaderLib.hxx>
#include <Interface_MapAsciiStringHasher.hxx>
#include <Interface_HGraph.hxx>
#include <Interface_Array1OfFileParameter.hxx>
#include <Interface_GeneralModule.hxx>
#include <Interface_CopyMap.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_ParamType.hxx>
#include <Interface_Statics.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Interface_InterfaceError.hxx>
#include <Interface_HArray1OfHAsciiString.hxx>
#include <Interface_NodeOfReaderLib.hxx>
#include <Interface_ReportEntity.hxx>
#include <Interface_Array1OfHAsciiString.hxx>
#include <Interface_ReaderLib.hxx>
#include <Interface_UndefinedContent.hxx>
#include <Interface_NodeOfGeneralLib.hxx>
#include <Interface_CheckStatus.hxx>
#include <Interface_STAT.hxx>
#include <Interface_Protocol.hxx>
#include <Interface_SignType.hxx>
#include <Interface_EntityList.hxx>
#include <Interface_StaticSatisfies.hxx>
#include <Interface_Macros.hxx>
#include <Interface_DataMapOfTransientInteger.hxx>
#include <Interface_ValueInterpret.hxx>
#include <Interface_FileReaderTool.hxx>
#include <Interface_DataState.hxx>
#include <Interface_Graph.hxx>
#include <Interface_DataMapIteratorOfDataMapOfTransientInteger.hxx>
#include <Interface_BitMap.hxx>
#include <Interface_ReaderModule.hxx>
#include <Interface_Check.hxx>
#include <Interface_Category.hxx>
#include <Interface_GTool.hxx>
#include <Interface_EntityCluster.hxx>
#include <Interface_CopyTool.hxx>
#include <Interface_IndexedMapOfAsciiString.hxx>
#include <Interface_ParamSet.hxx>
#include <Interface_Static.hxx>
#include <Interface_ShareFlags.hxx>
#include <Interface_CheckIterator.hxx>
#include <Interface_ParamList.hxx>
#include <Interface_GraphContent.hxx>
#include <Interface_ValueSatisfies.hxx>
#include <Interface_Translates.hxx>
#include <Interface_HSequenceOfCheck.hxx>
#include <Interface_IntList.hxx>
#include <Interface_GlobalNodeOfGeneralLib.hxx>
#include <Interface_VectorOfFileParameter.hxx>
#include <Interface_FloatWriter.hxx>
#include <Interface_IntVal.hxx>
#include <Interface_SignLabel.hxx>
#include <Interface_TypedValue.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/Interface_CheckTool.hxx
// ./opencascade/Interface_FileParameter.hxx
// ./opencascade/Interface_InterfaceMismatch.hxx
// ./opencascade/Interface_FileReaderData.hxx
// ./opencascade/Interface_SequenceOfCheck.hxx
// ./opencascade/Interface_GeneralLib.hxx
// ./opencascade/Interface_Version.hxx
// ./opencascade/Interface_ShareTool.hxx
// ./opencascade/Interface_CopyControl.hxx
// ./opencascade/Interface_LineBuffer.hxx
// ./opencascade/Interface_MSG.hxx
// ./opencascade/Interface_CheckFailure.hxx
// ./opencascade/Interface_GlobalNodeOfReaderLib.hxx
// ./opencascade/Interface_MapAsciiStringHasher.hxx
// ./opencascade/Interface_HGraph.hxx
// ./opencascade/Interface_Array1OfFileParameter.hxx
// ./opencascade/Interface_GeneralModule.hxx
// ./opencascade/Interface_CopyMap.hxx
// ./opencascade/Interface_EntityIterator.hxx
// ./opencascade/Interface_ParamType.hxx
// ./opencascade/Interface_Statics.hxx
// ./opencascade/Interface_InterfaceModel.hxx
// ./opencascade/Interface_InterfaceError.hxx
// ./opencascade/Interface_HArray1OfHAsciiString.hxx
// ./opencascade/Interface_NodeOfReaderLib.hxx
// ./opencascade/Interface_ReportEntity.hxx
// ./opencascade/Interface_Array1OfHAsciiString.hxx
// ./opencascade/Interface_ReaderLib.hxx
// ./opencascade/Interface_UndefinedContent.hxx
// ./opencascade/Interface_NodeOfGeneralLib.hxx
// ./opencascade/Interface_CheckStatus.hxx
// ./opencascade/Interface_STAT.hxx
// ./opencascade/Interface_Protocol.hxx
// ./opencascade/Interface_SignType.hxx
// ./opencascade/Interface_EntityList.hxx
// ./opencascade/Interface_StaticSatisfies.hxx
// ./opencascade/Interface_Macros.hxx
// ./opencascade/Interface_DataMapOfTransientInteger.hxx
// ./opencascade/Interface_ValueInterpret.hxx
// ./opencascade/Interface_FileReaderTool.hxx
// ./opencascade/Interface_DataState.hxx
// ./opencascade/Interface_Graph.hxx
// ./opencascade/Interface_DataMapIteratorOfDataMapOfTransientInteger.hxx
// ./opencascade/Interface_BitMap.hxx
// ./opencascade/Interface_ReaderModule.hxx
// ./opencascade/Interface_Check.hxx
// ./opencascade/Interface_Category.hxx
// ./opencascade/Interface_GTool.hxx
// ./opencascade/Interface_EntityCluster.hxx
// ./opencascade/Interface_CopyTool.hxx
// ./opencascade/Interface_IndexedMapOfAsciiString.hxx
// ./opencascade/Interface_ParamSet.hxx
// ./opencascade/Interface_Static.hxx
// ./opencascade/Interface_ShareFlags.hxx
// ./opencascade/Interface_CheckIterator.hxx
// ./opencascade/Interface_ParamList.hxx
// ./opencascade/Interface_GraphContent.hxx
// ./opencascade/Interface_ValueSatisfies.hxx
// ./opencascade/Interface_Translates.hxx
// ./opencascade/Interface_HSequenceOfCheck.hxx
// ./opencascade/Interface_IntList.hxx
// ./opencascade/Interface_GlobalNodeOfGeneralLib.hxx
// ./opencascade/Interface_VectorOfFileParameter.hxx
// ./opencascade/Interface_FloatWriter.hxx
// ./opencascade/Interface_IntVal.hxx
// ./opencascade/Interface_SignLabel.hxx
// ./opencascade/Interface_TypedValue.hxx

// user-defined post
