#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <TopoDS_Face.hxx>
#include <GeomAdaptor_HSurface.hxx>
#include <GeomInt_LineConstructor.hxx>
#include <IntTools_Context.hxx>
#include <Adaptor3d_TopolTool.hxx>
#include <IntTools_CurveRangeSample.hxx>
#include <Bnd_Box.hxx>
#include <Geom_Curve.hxx>
#include <Geom2d_Curve.hxx>
#include <gp_Pnt.hxx>
#include <Adaptor3d_HSurface.hxx>
#include <IntTools_Range.hxx>
#include <TopoDS_Edge.hxx>
#include <gp_Pnt.hxx>
#include <Geom_Curve.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <IntTools_CArray1OfReal.hxx>
#include <IntTools_Context.hxx>
#include <IntTools_ShrunkRange.hxx>
#include <IntTools_Range.hxx>
#include <IntTools_CommonPrt.hxx>
#include <IntTools_EdgeEdge.hxx>
#include <IntTools_EdgeFace.hxx>
#include <IntTools_FClass2d.hxx>
#include <IntTools_MarkedRangeSet.hxx>
#include <IntTools_BaseRangeSample.hxx>
#include <IntTools_CurveRangeSample.hxx>
#include <IntTools_SurfaceRangeSample.hxx>
#include <IntTools_CurveRangeLocalizeData.hxx>
#include <IntTools_SurfaceRangeLocalizeData.hxx>
#include <IntTools_BeanFaceIntersector.hxx>
#include <IntTools_Curve.hxx>
#include <IntTools_PntOnFace.hxx>
#include <IntTools_PntOn2Faces.hxx>
#include <IntTools_TopolTool.hxx>
#include <IntTools_FaceFace.hxx>
#include <IntTools_Tools.hxx>
#include <IntTools_CArray1OfInteger.hxx>
#include <IntTools_CArray1OfReal.hxx>
#include <IntTools_CurveRangeSampleMapHasher.hxx>
#include <IntTools_SurfaceRangeSampleMapHasher.hxx>
#include <Standard_ConstructionError.hxx>
#include <Standard_OutOfMemory.hxx>
#include <IntTools_Context.hxx>
#include <IntTools_FClass2d.hxx>
#include <GeomAPI_ProjectPointOnSurf.hxx>
#include <GeomAPI_ProjectPointOnCurve.hxx>
#include <TopoDS_Edge.hxx>
#include <IntTools_SurfaceRangeLocalizeData.hxx>
#include <BRepClass3d_SolidClassifier.hxx>
#include <TopoDS_Solid.hxx>
#include <Geom2dHatch_Hatcher.hxx>
#include <TopoDS_Vertex.hxx>
#include <IntTools_Curve.hxx>
#include <Bnd_Box.hxx>
#include <Bnd_OBB.hxx>
#include <IntTools_Context.hxx>
#include <Bnd_Box.hxx>
#include <IntTools_CurveRangeLocalizeData.hxx>
#include <IntTools_SurfaceRangeLocalizeData.hxx>
#include <IntTools_CArray1OfReal.hxx>
#include <IntTools_Range.hxx>
#include <Standard_ConstructionError.hxx>
#include <Standard_OutOfMemory.hxx>
#include <TopoDS_Vertex.hxx>
#include <TopoDS_Wire.hxx>
#include <TopoDS_Face.hxx>
#include <gp_Pnt2d.hxx>
#include <TopoDS_Edge.hxx>
#include <IntTools_CommonPrt.hxx>
#include <gp_Pnt.hxx>
#include <gp_Dir.hxx>
#include <Geom_Curve.hxx>
#include <Bnd_Box.hxx>
#include <IntTools_Range.hxx>
#include <gp_Lin.hxx>
#include <gp_Pln.hxx>
#include <Geom2d_Curve.hxx>
#include <Geom_Surface.hxx>
#include <IntTools_Range.hxx>
#include <IntTools_Context.hxx>
#include <GeomAdaptor_HSurface.hxx>
#include <IntTools_Context.hxx>
#include <Adaptor3d_TopolTool.hxx>
#include <IntTools_SurfaceRangeSample.hxx>

// module includes
#include <IntTools_SequenceOfRanges.hxx>
#include <IntTools_WLineTool.hxx>
#include <IntTools_CurveRangeSampleMapHasher.hxx>
#include <IntTools_EdgeEdge.hxx>
#include <IntTools_Curve.hxx>
#include <IntTools_Range.hxx>
#include <IntTools_DataMapOfCurveSampleBox.hxx>
#include <IntTools_DataMapIteratorOfDataMapOfCurveSampleBox.hxx>
#include <IntTools_Array1OfRoots.hxx>
#include <IntTools_TopolTool.hxx>
#include <IntTools_CurveRangeSample.hxx>
#include <IntTools.hxx>
#include <IntTools_CArray1OfInteger.hxx>
#include <IntTools_ListIteratorOfListOfCurveRangeSample.hxx>
#include <IntTools_EdgeFace.hxx>
#include <IntTools_PntOnFace.hxx>
#include <IntTools_Context.hxx>
#include <IntTools_Array1OfRange.hxx>
#include <IntTools_MapOfCurveSample.hxx>
#include <IntTools_CommonPrt.hxx>
#include <IntTools_ListOfCurveRangeSample.hxx>
#include <IntTools_DataMapOfSurfaceSampleBox.hxx>
#include <IntTools_MapOfSurfaceSample.hxx>
#include <IntTools_BaseRangeSample.hxx>
#include <IntTools_PntOn2Faces.hxx>
#include <IntTools_BeanFaceIntersector.hxx>
#include <IntTools_MarkedRangeSet.hxx>
#include <IntTools_CArray1OfReal.hxx>
#include <IntTools_CurveRangeLocalizeData.hxx>
#include <IntTools_MapIteratorOfMapOfSurfaceSample.hxx>
#include <IntTools_ListOfBox.hxx>
#include <IntTools_SequenceOfCurves.hxx>
#include <IntTools_Tools.hxx>
#include <IntTools_SurfaceRangeSample.hxx>
#include <IntTools_ListIteratorOfListOfSurfaceRangeSample.hxx>
#include <IntTools_MapIteratorOfMapOfCurveSample.hxx>
#include <IntTools_ShrunkRange.hxx>
#include <IntTools_DataMapIteratorOfDataMapOfSurfaceSampleBox.hxx>
#include <IntTools_FaceFace.hxx>
#include <IntTools_ListOfSurfaceRangeSample.hxx>
#include <IntTools_Root.hxx>
#include <IntTools_SequenceOfCommonPrts.hxx>
#include <IntTools_SurfaceRangeLocalizeData.hxx>
#include <IntTools_SequenceOfPntOn2Faces.hxx>
#include <IntTools_SurfaceRangeSampleMapHasher.hxx>
#include <IntTools_FClass2d.hxx>
#include <IntTools_ListIteratorOfListOfBox.hxx>
#include <IntTools_SequenceOfRoots.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/IntTools_SequenceOfRanges.hxx
// ./opencascade/IntTools_WLineTool.hxx
// ./opencascade/IntTools_CurveRangeSampleMapHasher.hxx
// ./opencascade/IntTools_EdgeEdge.hxx
// ./opencascade/IntTools_Curve.hxx
// ./opencascade/IntTools_Range.hxx
// ./opencascade/IntTools_DataMapOfCurveSampleBox.hxx
// ./opencascade/IntTools_DataMapIteratorOfDataMapOfCurveSampleBox.hxx
// ./opencascade/IntTools_Array1OfRoots.hxx
// ./opencascade/IntTools_TopolTool.hxx
// ./opencascade/IntTools_CurveRangeSample.hxx
// ./opencascade/IntTools.hxx
// ./opencascade/IntTools_CArray1OfInteger.hxx
// ./opencascade/IntTools_ListIteratorOfListOfCurveRangeSample.hxx
// ./opencascade/IntTools_EdgeFace.hxx
// ./opencascade/IntTools_PntOnFace.hxx
// ./opencascade/IntTools_Context.hxx
// ./opencascade/IntTools_Array1OfRange.hxx
// ./opencascade/IntTools_MapOfCurveSample.hxx
// ./opencascade/IntTools_CommonPrt.hxx
// ./opencascade/IntTools_ListOfCurveRangeSample.hxx
// ./opencascade/IntTools_DataMapOfSurfaceSampleBox.hxx
// ./opencascade/IntTools_MapOfSurfaceSample.hxx
// ./opencascade/IntTools_BaseRangeSample.hxx
// ./opencascade/IntTools_PntOn2Faces.hxx
// ./opencascade/IntTools_BeanFaceIntersector.hxx
// ./opencascade/IntTools_MarkedRangeSet.hxx
// ./opencascade/IntTools_CArray1OfReal.hxx
// ./opencascade/IntTools_CurveRangeLocalizeData.hxx
// ./opencascade/IntTools_MapIteratorOfMapOfSurfaceSample.hxx
// ./opencascade/IntTools_ListOfBox.hxx
// ./opencascade/IntTools_SequenceOfCurves.hxx
// ./opencascade/IntTools_Tools.hxx
// ./opencascade/IntTools_SurfaceRangeSample.hxx
// ./opencascade/IntTools_ListIteratorOfListOfSurfaceRangeSample.hxx
// ./opencascade/IntTools_MapIteratorOfMapOfCurveSample.hxx
// ./opencascade/IntTools_ShrunkRange.hxx
// ./opencascade/IntTools_DataMapIteratorOfDataMapOfSurfaceSampleBox.hxx
// ./opencascade/IntTools_FaceFace.hxx
// ./opencascade/IntTools_ListOfSurfaceRangeSample.hxx
// ./opencascade/IntTools_Root.hxx
// ./opencascade/IntTools_SequenceOfCommonPrts.hxx
// ./opencascade/IntTools_SurfaceRangeLocalizeData.hxx
// ./opencascade/IntTools_SequenceOfPntOn2Faces.hxx
// ./opencascade/IntTools_SurfaceRangeSampleMapHasher.hxx
// ./opencascade/IntTools_FClass2d.hxx
// ./opencascade/IntTools_ListIteratorOfListOfBox.hxx
// ./opencascade/IntTools_SequenceOfRoots.hxx

// user-defined post
