#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <Quantity_PeriodDefinitionError.hxx>
#include <Quantity_DateDefinitionError.hxx>
#include <Standard_OutOfRange.hxx>
#include <Quantity_Period.hxx>
#include <Quantity_ColorDefinitionError.hxx>

// module includes
#include <Quantity_LuminousIntensity.hxx>
#include <Quantity_MassFlow.hxx>
#include <Quantity_MagneticFieldStrength.hxx>
#include <Quantity_Density.hxx>
#include <Quantity_Period.hxx>
#include <Quantity_Force.hxx>
#include <Quantity_Length.hxx>
#include <Quantity_ElectricCurrent.hxx>
#include <Quantity_MolarConcentration.hxx>
#include <Quantity_Scalaire.hxx>
#include <Quantity_ColorDefinitionError.hxx>
#include <Quantity_DateDefinitionError.hxx>
#include <Quantity_LuminousFlux.hxx>
#include <Quantity_ElectricFieldStrength.hxx>
#include <Quantity_Volume.hxx>
#include <Quantity_ElectricPotential.hxx>
#include <Quantity_Acceleration.hxx>
#include <Quantity_Ratio.hxx>
#include <Quantity_Conductivity.hxx>
#include <Quantity_SoundIntensity.hxx>
#include <Quantity_AmountOfSubstance.hxx>
#include <Quantity_Index.hxx>
#include <Quantity_Velocity.hxx>
#include <Quantity_Illuminance.hxx>
#include <Quantity_LuminousExposition.hxx>
#include <Quantity_Entropy.hxx>
#include <Quantity_Work.hxx>
#include <Quantity_Viscosity.hxx>
#include <Quantity_Parameter.hxx>
#include <Quantity_Date.hxx>
#include <Quantity_Activity.hxx>
#include <Quantity_Constant.hxx>
#include <Quantity_Consumption.hxx>
#include <Quantity_TypeOfColor.hxx>
#include <Quantity_AngularVelocity.hxx>
#include <Quantity_NameOfColor.hxx>
#include <Quantity_Mass.hxx>
#include <Quantity_MomentOfAForce.hxx>
#include <Quantity_Concentration.hxx>
#include <Quantity_Inductance.hxx>
#include <Quantity_Array2OfColor.hxx>
#include <Quantity_Frequency.hxx>
#include <Quantity_MomentOfInertia.hxx>
#include <Quantity_KineticMoment.hxx>
#include <Quantity_MagneticFluxDensity.hxx>
#include <Quantity_DoseEquivalent.hxx>
#include <Quantity_ColorRGBA.hxx>
#include <Quantity_SpecificHeatCapacity.hxx>
#include <Quantity_MolarVolume.hxx>
#include <Quantity_LuminousEfficacity.hxx>
#include <Quantity_ElectricCharge.hxx>
#include <Quantity_Momentum.hxx>
#include <Quantity_Factor.hxx>
#include <Quantity_Capacitance.hxx>
#include <Quantity_Enthalpy.hxx>
#include <Quantity_Resistivity.hxx>
#include <Quantity_AbsorbedDose.hxx>
#include <Quantity_Power.hxx>
#include <Quantity_MolarMass.hxx>
#include <Quantity_Speed.hxx>
#include <Quantity_MagneticFlux.hxx>
#include <Quantity_Coefficient.hxx>
#include <Quantity_Area.hxx>
#include <Quantity_CoefficientOfExpansion.hxx>
#include <Quantity_Color.hxx>
#include <Quantity_Array1OfColor.hxx>
#include <Quantity_Impedance.hxx>
#include <Quantity_Admittance.hxx>
#include <Quantity_Rate.hxx>
#include <Quantity_ColorRGBAHasher.hxx>
#include <Quantity_ElectricCapacitance.hxx>
#include <Quantity_PeriodDefinitionError.hxx>
#include <Quantity_Reluctance.hxx>
#include <Quantity_KinematicViscosity.hxx>
#include <Quantity_ThermalConductivity.hxx>
#include <Quantity_Temperature.hxx>
#include <Quantity_Pressure.hxx>
#include <Quantity_Resistance.hxx>
#include <Quantity_VolumeFlow.hxx>
#include <Quantity_SolidAngle.hxx>
#include <Quantity_Quotient.hxx>
#include <Quantity_Luminance.hxx>
#include <Quantity_Molarity.hxx>
#include <Quantity_HArray1OfColor.hxx>
#include <Quantity_Torque.hxx>
#include <Quantity_AcousticIntensity.hxx>
#include <Quantity_Weight.hxx>
#include <Quantity_PlaneAngle.hxx>
#include <Quantity_Normality.hxx>
#include <Quantity_Energy.hxx>
#include <Quantity_PhysicalQuantity.hxx>
#include <Quantity_SurfaceTension.hxx>
#include <Quantity_Content.hxx>
#include <Quantity_ColorHasher.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/Quantity_LuminousIntensity.hxx
// ./opencascade/Quantity_MassFlow.hxx
// ./opencascade/Quantity_MagneticFieldStrength.hxx
// ./opencascade/Quantity_Density.hxx
// ./opencascade/Quantity_Period.hxx
// ./opencascade/Quantity_Force.hxx
// ./opencascade/Quantity_Length.hxx
// ./opencascade/Quantity_ElectricCurrent.hxx
// ./opencascade/Quantity_MolarConcentration.hxx
// ./opencascade/Quantity_Scalaire.hxx
// ./opencascade/Quantity_ColorDefinitionError.hxx
// ./opencascade/Quantity_DateDefinitionError.hxx
// ./opencascade/Quantity_LuminousFlux.hxx
// ./opencascade/Quantity_ElectricFieldStrength.hxx
// ./opencascade/Quantity_Volume.hxx
// ./opencascade/Quantity_ElectricPotential.hxx
// ./opencascade/Quantity_Acceleration.hxx
// ./opencascade/Quantity_Ratio.hxx
// ./opencascade/Quantity_Conductivity.hxx
// ./opencascade/Quantity_SoundIntensity.hxx
// ./opencascade/Quantity_AmountOfSubstance.hxx
// ./opencascade/Quantity_Index.hxx
// ./opencascade/Quantity_Velocity.hxx
// ./opencascade/Quantity_Illuminance.hxx
// ./opencascade/Quantity_LuminousExposition.hxx
// ./opencascade/Quantity_Entropy.hxx
// ./opencascade/Quantity_Work.hxx
// ./opencascade/Quantity_Viscosity.hxx
// ./opencascade/Quantity_Parameter.hxx
// ./opencascade/Quantity_Date.hxx
// ./opencascade/Quantity_Activity.hxx
// ./opencascade/Quantity_Constant.hxx
// ./opencascade/Quantity_Consumption.hxx
// ./opencascade/Quantity_TypeOfColor.hxx
// ./opencascade/Quantity_AngularVelocity.hxx
// ./opencascade/Quantity_NameOfColor.hxx
// ./opencascade/Quantity_Mass.hxx
// ./opencascade/Quantity_MomentOfAForce.hxx
// ./opencascade/Quantity_Concentration.hxx
// ./opencascade/Quantity_Inductance.hxx
// ./opencascade/Quantity_Array2OfColor.hxx
// ./opencascade/Quantity_Frequency.hxx
// ./opencascade/Quantity_MomentOfInertia.hxx
// ./opencascade/Quantity_KineticMoment.hxx
// ./opencascade/Quantity_MagneticFluxDensity.hxx
// ./opencascade/Quantity_DoseEquivalent.hxx
// ./opencascade/Quantity_ColorRGBA.hxx
// ./opencascade/Quantity_SpecificHeatCapacity.hxx
// ./opencascade/Quantity_MolarVolume.hxx
// ./opencascade/Quantity_LuminousEfficacity.hxx
// ./opencascade/Quantity_ElectricCharge.hxx
// ./opencascade/Quantity_Momentum.hxx
// ./opencascade/Quantity_Factor.hxx
// ./opencascade/Quantity_Capacitance.hxx
// ./opencascade/Quantity_Enthalpy.hxx
// ./opencascade/Quantity_Resistivity.hxx
// ./opencascade/Quantity_AbsorbedDose.hxx
// ./opencascade/Quantity_Power.hxx
// ./opencascade/Quantity_MolarMass.hxx
// ./opencascade/Quantity_Speed.hxx
// ./opencascade/Quantity_MagneticFlux.hxx
// ./opencascade/Quantity_Coefficient.hxx
// ./opencascade/Quantity_Area.hxx
// ./opencascade/Quantity_CoefficientOfExpansion.hxx
// ./opencascade/Quantity_Color.hxx
// ./opencascade/Quantity_Array1OfColor.hxx
// ./opencascade/Quantity_Impedance.hxx
// ./opencascade/Quantity_Admittance.hxx
// ./opencascade/Quantity_Rate.hxx
// ./opencascade/Quantity_ColorRGBAHasher.hxx
// ./opencascade/Quantity_ElectricCapacitance.hxx
// ./opencascade/Quantity_PeriodDefinitionError.hxx
// ./opencascade/Quantity_Reluctance.hxx
// ./opencascade/Quantity_KinematicViscosity.hxx
// ./opencascade/Quantity_ThermalConductivity.hxx
// ./opencascade/Quantity_Temperature.hxx
// ./opencascade/Quantity_Pressure.hxx
// ./opencascade/Quantity_Resistance.hxx
// ./opencascade/Quantity_VolumeFlow.hxx
// ./opencascade/Quantity_SolidAngle.hxx
// ./opencascade/Quantity_Quotient.hxx
// ./opencascade/Quantity_Luminance.hxx
// ./opencascade/Quantity_Molarity.hxx
// ./opencascade/Quantity_HArray1OfColor.hxx
// ./opencascade/Quantity_Torque.hxx
// ./opencascade/Quantity_AcousticIntensity.hxx
// ./opencascade/Quantity_Weight.hxx
// ./opencascade/Quantity_PlaneAngle.hxx
// ./opencascade/Quantity_Normality.hxx
// ./opencascade/Quantity_Energy.hxx
// ./opencascade/Quantity_PhysicalQuantity.hxx
// ./opencascade/Quantity_SurfaceTension.hxx
// ./opencascade/Quantity_Content.hxx
// ./opencascade/Quantity_ColorHasher.hxx

// user-defined post
