#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <StepGeom_CartesianTransformationOperator3d.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CartesianTransformationOperator.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Direction.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CartesianPoint.hxx>
#include <StepGeom_CartesianPoint.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Vector.hxx>
#include <StepGeom_Direction.hxx>
#include <StepGeom_Direction.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CartesianPoint.hxx>
#include <StepGeom_Pcurve.hxx>
#include <StepGeom_Surface.hxx>
#include <StepGeom_Surface.hxx>
#include <StepRepr_DefinitionalRepresentation.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Curve.hxx>
#include <StepGeom_Vector.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Curve.hxx>
#include <StepGeom_BoundaryCurve.hxx>
#include <StepGeom_DegeneratePcurve.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CartesianTransformationOperator.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <StepGeom_Pcurve.hxx>
#include <StepGeom_SurfaceCurve.hxx>
#include <StepGeom_CompositeCurveOnSurface.hxx>
#include <StepGeom_CartesianPoint.hxx>
#include <StepGeom_Vector.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Curve.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_QuasiUniformCurve.hxx>
#include <StepGeom_RationalBSplineCurve.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Surface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_QuasiUniformSurface.hxx>
#include <StepGeom_RationalBSplineSurface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Direction.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CartesianPoint.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis2Placement2d.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_BezierSurface.hxx>
#include <StepGeom_RationalBSplineSurface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_GeometricRepresentationContext.hxx>
#include <StepRepr_GlobalUnitAssignedContext.hxx>
#include <StepRepr_GlobalUncertaintyAssignedContext.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Curve.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_GeometricRepresentationContext.hxx>
#include <StepRepr_GlobalUnitAssignedContext.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Direction.hxx>
#include <StepGeom_CartesianPoint.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_BezierCurve.hxx>
#include <StepGeom_RationalBSplineCurve.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_BSplineCurveWithKnots.hxx>
#include <StepGeom_RationalBSplineCurve.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Curve.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_UniformSurface.hxx>
#include <StepGeom_RationalBSplineSurface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_UniformCurve.hxx>
#include <StepGeom_RationalBSplineCurve.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_BoundedCurve.hxx>
#include <StepGeom_Direction.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CartesianPoint.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Surface.hxx>
#include <StepRepr_DefinitionalRepresentation.hxx>
#include <StepGeom_Axis1Placement.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Curve.hxx>
#include <StepGeom_Direction.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_BSplineSurfaceWithKnots.hxx>
#include <StepGeom_RationalBSplineSurface.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_BoundedSurface.hxx>
#include <StepGeom_Direction.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_CartesianPoint.hxx>
#include <StepGeom_GeometricRepresentationContext.hxx>
#include <StepRepr_ParametricRepresentationContext.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepGeom_Surface.hxx>
#include <StepRepr_DefinitionalRepresentation.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepData_SelectMember.hxx>
#include <StepGeom_CartesianPoint.hxx>

// module includes
#include <StepGeom_SurfaceReplica.hxx>
#include <StepGeom_Direction.hxx>
#include <StepGeom_BSplineSurfaceForm.hxx>
#include <StepGeom_RationalBSplineSurface.hxx>
#include <StepGeom_CurveReplica.hxx>
#include <StepGeom_Axis1Placement.hxx>
#include <StepGeom_Placement.hxx>
#include <StepGeom_VectorOrDirection.hxx>
#include <StepGeom_CartesianTransformationOperator3d.hxx>
#include <StepGeom_Point.hxx>
#include <StepGeom_TrimmingMember.hxx>
#include <StepGeom_PcurveOrSurface.hxx>
#include <StepGeom_Pcurve.hxx>
#include <StepGeom_HArray1OfTrimmingSelect.hxx>
#include <StepGeom_ReparametrisedCompositeCurveSegment.hxx>
#include <StepGeom_SeamCurve.hxx>
#include <StepGeom_SurfaceOfLinearExtrusion.hxx>
#include <StepGeom_SurfaceBoundary.hxx>
#include <StepGeom_Conic.hxx>
#include <StepGeom_UniformCurve.hxx>
#include <StepGeom_BoundedSurface.hxx>
#include <StepGeom_Polyline.hxx>
#include <StepGeom_PointReplica.hxx>
#include <StepGeom_CylindricalSurface.hxx>
#include <StepGeom_CurveOnSurface.hxx>
#include <StepGeom_Line.hxx>
#include <StepGeom_Ellipse.hxx>
#include <StepGeom_Circle.hxx>
#include <StepGeom_Array2OfCartesianPoint.hxx>
#include <StepGeom_BezierSurface.hxx>
#include <StepGeom_BoundaryCurve.hxx>
#include <StepGeom_CompositeCurveSegment.hxx>
#include <StepGeom_ToroidalSurface.hxx>
#include <StepGeom_OrientedSurface.hxx>
#include <StepGeom_QuasiUniformCurveAndRationalBSplineCurve.hxx>
#include <StepGeom_PointOnSurface.hxx>
#include <StepGeom_CompositeCurve.hxx>
#include <StepGeom_QuasiUniformSurfaceAndRationalBSplineSurface.hxx>
#include <StepGeom_BezierCurve.hxx>
#include <StepGeom_Axis2Placement2d.hxx>
#include <StepGeom_TrimmedCurve.hxx>
#include <StepGeom_Array1OfTrimmingSelect.hxx>
#include <StepGeom_Axis2Placement.hxx>
#include <StepGeom_QuasiUniformCurve.hxx>
#include <StepGeom_BSplineCurveWithKnots.hxx>
#include <StepGeom_BezierSurfaceAndRationalBSplineSurface.hxx>
#include <StepGeom_UniformSurface.hxx>
#include <StepGeom_HArray2OfSurfacePatch.hxx>
#include <StepGeom_HArray1OfPcurveOrSurface.hxx>
#include <StepGeom_SurfaceCurve.hxx>
#include <StepGeom_TrimmingPreference.hxx>
#include <StepGeom_HArray2OfCartesianPoint.hxx>
#include <StepGeom_GeomRepContextAndGlobUnitAssCtxAndGlobUncertaintyAssCtx.hxx>
#include <StepGeom_CurveBoundedSurface.hxx>
#include <StepGeom_DegenerateToroidalSurface.hxx>
#include <StepGeom_BSplineCurveForm.hxx>
#include <StepGeom_CompositeCurveOnSurface.hxx>
#include <StepGeom_Array1OfCartesianPoint.hxx>
#include <StepGeom_RectangularCompositeSurface.hxx>
#include <StepGeom_Curve.hxx>
#include <StepGeom_Array1OfSurfaceBoundary.hxx>
#include <StepGeom_PointOnCurve.hxx>
#include <StepGeom_GeometricRepresentationContextAndGlobalUnitAssignedContext.hxx>
#include <StepGeom_HArray1OfCurve.hxx>
#include <StepGeom_CartesianPoint.hxx>
#include <StepGeom_ConicalSurface.hxx>
#include <StepGeom_Hyperbola.hxx>
#include <StepGeom_BSplineSurfaceWithKnots.hxx>
#include <StepGeom_Array1OfPcurveOrSurface.hxx>
#include <StepGeom_Plane.hxx>
#include <StepGeom_CartesianTransformationOperator.hxx>
#include <StepGeom_BSplineSurface.hxx>
#include <StepGeom_RationalBSplineCurve.hxx>
#include <StepGeom_Array1OfCompositeCurveSegment.hxx>
#include <StepGeom_BezierCurveAndRationalBSplineCurve.hxx>
#include <StepGeom_Array1OfCurve.hxx>
#include <StepGeom_HArray1OfBoundaryCurve.hxx>
#include <StepGeom_HArray1OfCartesianPoint.hxx>
#include <StepGeom_BSplineCurveWithKnotsAndRationalBSplineCurve.hxx>
#include <StepGeom_GeometricRepresentationContext.hxx>
#include <StepGeom_SweptSurface.hxx>
#include <StepGeom_HArray1OfSurfaceBoundary.hxx>
#include <StepGeom_UniformSurfaceAndRationalBSplineSurface.hxx>
#include <StepGeom_OffsetSurface.hxx>
#include <StepGeom_Array2OfSurfacePatch.hxx>
#include <StepGeom_UniformCurveAndRationalBSplineCurve.hxx>
#include <StepGeom_SurfaceCurveAndBoundedCurve.hxx>
#include <StepGeom_Vector.hxx>
#include <StepGeom_Array1OfBoundaryCurve.hxx>
#include <StepGeom_EvaluatedDegeneratePcurve.hxx>
#include <StepGeom_Surface.hxx>
#include <StepGeom_SurfaceOfRevolution.hxx>
#include <StepGeom_GeometricRepresentationItem.hxx>
#include <StepGeom_CartesianTransformationOperator2d.hxx>
#include <StepGeom_QuasiUniformSurface.hxx>
#include <StepGeom_HArray1OfCompositeCurveSegment.hxx>
#include <StepGeom_OffsetCurve3d.hxx>
#include <StepGeom_PreferredSurfaceCurveRepresentation.hxx>
#include <StepGeom_BSplineSurfaceWithKnotsAndRationalBSplineSurface.hxx>
#include <StepGeom_BSplineCurve.hxx>
#include <StepGeom_RectangularTrimmedSurface.hxx>
#include <StepGeom_SurfacePatch.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <StepGeom_TransitionCode.hxx>
#include <StepGeom_OuterBoundaryCurve.hxx>
#include <StepGeom_IntersectionCurve.hxx>
#include <StepGeom_GeometricRepresentationContextAndParametricRepresentationContext.hxx>
#include <StepGeom_SphericalSurface.hxx>
#include <StepGeom_Parabola.hxx>
#include <StepGeom_ElementarySurface.hxx>
#include <StepGeom_DegeneratePcurve.hxx>
#include <StepGeom_BoundedCurve.hxx>
#include <StepGeom_KnotType.hxx>
#include <StepGeom_TrimmingSelect.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/StepGeom_SurfaceReplica.hxx
// ./opencascade/StepGeom_Direction.hxx
// ./opencascade/StepGeom_BSplineSurfaceForm.hxx
// ./opencascade/StepGeom_RationalBSplineSurface.hxx
// ./opencascade/StepGeom_CurveReplica.hxx
// ./opencascade/StepGeom_Axis1Placement.hxx
// ./opencascade/StepGeom_Placement.hxx
// ./opencascade/StepGeom_VectorOrDirection.hxx
// ./opencascade/StepGeom_CartesianTransformationOperator3d.hxx
// ./opencascade/StepGeom_Point.hxx
// ./opencascade/StepGeom_TrimmingMember.hxx
// ./opencascade/StepGeom_PcurveOrSurface.hxx
// ./opencascade/StepGeom_Pcurve.hxx
// ./opencascade/StepGeom_HArray1OfTrimmingSelect.hxx
// ./opencascade/StepGeom_ReparametrisedCompositeCurveSegment.hxx
// ./opencascade/StepGeom_SeamCurve.hxx
// ./opencascade/StepGeom_SurfaceOfLinearExtrusion.hxx
// ./opencascade/StepGeom_SurfaceBoundary.hxx
// ./opencascade/StepGeom_Conic.hxx
// ./opencascade/StepGeom_UniformCurve.hxx
// ./opencascade/StepGeom_BoundedSurface.hxx
// ./opencascade/StepGeom_Polyline.hxx
// ./opencascade/StepGeom_PointReplica.hxx
// ./opencascade/StepGeom_CylindricalSurface.hxx
// ./opencascade/StepGeom_CurveOnSurface.hxx
// ./opencascade/StepGeom_Line.hxx
// ./opencascade/StepGeom_Ellipse.hxx
// ./opencascade/StepGeom_Circle.hxx
// ./opencascade/StepGeom_Array2OfCartesianPoint.hxx
// ./opencascade/StepGeom_BezierSurface.hxx
// ./opencascade/StepGeom_BoundaryCurve.hxx
// ./opencascade/StepGeom_CompositeCurveSegment.hxx
// ./opencascade/StepGeom_ToroidalSurface.hxx
// ./opencascade/StepGeom_OrientedSurface.hxx
// ./opencascade/StepGeom_QuasiUniformCurveAndRationalBSplineCurve.hxx
// ./opencascade/StepGeom_PointOnSurface.hxx
// ./opencascade/StepGeom_CompositeCurve.hxx
// ./opencascade/StepGeom_QuasiUniformSurfaceAndRationalBSplineSurface.hxx
// ./opencascade/StepGeom_BezierCurve.hxx
// ./opencascade/StepGeom_Axis2Placement2d.hxx
// ./opencascade/StepGeom_TrimmedCurve.hxx
// ./opencascade/StepGeom_Array1OfTrimmingSelect.hxx
// ./opencascade/StepGeom_Axis2Placement.hxx
// ./opencascade/StepGeom_QuasiUniformCurve.hxx
// ./opencascade/StepGeom_BSplineCurveWithKnots.hxx
// ./opencascade/StepGeom_BezierSurfaceAndRationalBSplineSurface.hxx
// ./opencascade/StepGeom_UniformSurface.hxx
// ./opencascade/StepGeom_HArray2OfSurfacePatch.hxx
// ./opencascade/StepGeom_HArray1OfPcurveOrSurface.hxx
// ./opencascade/StepGeom_SurfaceCurve.hxx
// ./opencascade/StepGeom_TrimmingPreference.hxx
// ./opencascade/StepGeom_HArray2OfCartesianPoint.hxx
// ./opencascade/StepGeom_GeomRepContextAndGlobUnitAssCtxAndGlobUncertaintyAssCtx.hxx
// ./opencascade/StepGeom_CurveBoundedSurface.hxx
// ./opencascade/StepGeom_DegenerateToroidalSurface.hxx
// ./opencascade/StepGeom_BSplineCurveForm.hxx
// ./opencascade/StepGeom_CompositeCurveOnSurface.hxx
// ./opencascade/StepGeom_Array1OfCartesianPoint.hxx
// ./opencascade/StepGeom_RectangularCompositeSurface.hxx
// ./opencascade/StepGeom_Curve.hxx
// ./opencascade/StepGeom_Array1OfSurfaceBoundary.hxx
// ./opencascade/StepGeom_PointOnCurve.hxx
// ./opencascade/StepGeom_GeometricRepresentationContextAndGlobalUnitAssignedContext.hxx
// ./opencascade/StepGeom_HArray1OfCurve.hxx
// ./opencascade/StepGeom_CartesianPoint.hxx
// ./opencascade/StepGeom_ConicalSurface.hxx
// ./opencascade/StepGeom_Hyperbola.hxx
// ./opencascade/StepGeom_BSplineSurfaceWithKnots.hxx
// ./opencascade/StepGeom_Array1OfPcurveOrSurface.hxx
// ./opencascade/StepGeom_Plane.hxx
// ./opencascade/StepGeom_CartesianTransformationOperator.hxx
// ./opencascade/StepGeom_BSplineSurface.hxx
// ./opencascade/StepGeom_RationalBSplineCurve.hxx
// ./opencascade/StepGeom_Array1OfCompositeCurveSegment.hxx
// ./opencascade/StepGeom_BezierCurveAndRationalBSplineCurve.hxx
// ./opencascade/StepGeom_Array1OfCurve.hxx
// ./opencascade/StepGeom_HArray1OfBoundaryCurve.hxx
// ./opencascade/StepGeom_HArray1OfCartesianPoint.hxx
// ./opencascade/StepGeom_BSplineCurveWithKnotsAndRationalBSplineCurve.hxx
// ./opencascade/StepGeom_GeometricRepresentationContext.hxx
// ./opencascade/StepGeom_SweptSurface.hxx
// ./opencascade/StepGeom_HArray1OfSurfaceBoundary.hxx
// ./opencascade/StepGeom_UniformSurfaceAndRationalBSplineSurface.hxx
// ./opencascade/StepGeom_OffsetSurface.hxx
// ./opencascade/StepGeom_Array2OfSurfacePatch.hxx
// ./opencascade/StepGeom_UniformCurveAndRationalBSplineCurve.hxx
// ./opencascade/StepGeom_SurfaceCurveAndBoundedCurve.hxx
// ./opencascade/StepGeom_Vector.hxx
// ./opencascade/StepGeom_Array1OfBoundaryCurve.hxx
// ./opencascade/StepGeom_EvaluatedDegeneratePcurve.hxx
// ./opencascade/StepGeom_Surface.hxx
// ./opencascade/StepGeom_SurfaceOfRevolution.hxx
// ./opencascade/StepGeom_GeometricRepresentationItem.hxx
// ./opencascade/StepGeom_CartesianTransformationOperator2d.hxx
// ./opencascade/StepGeom_QuasiUniformSurface.hxx
// ./opencascade/StepGeom_HArray1OfCompositeCurveSegment.hxx
// ./opencascade/StepGeom_OffsetCurve3d.hxx
// ./opencascade/StepGeom_PreferredSurfaceCurveRepresentation.hxx
// ./opencascade/StepGeom_BSplineSurfaceWithKnotsAndRationalBSplineSurface.hxx
// ./opencascade/StepGeom_BSplineCurve.hxx
// ./opencascade/StepGeom_RectangularTrimmedSurface.hxx
// ./opencascade/StepGeom_SurfacePatch.hxx
// ./opencascade/StepGeom_Axis2Placement3d.hxx
// ./opencascade/StepGeom_TransitionCode.hxx
// ./opencascade/StepGeom_OuterBoundaryCurve.hxx
// ./opencascade/StepGeom_IntersectionCurve.hxx
// ./opencascade/StepGeom_GeometricRepresentationContextAndParametricRepresentationContext.hxx
// ./opencascade/StepGeom_SphericalSurface.hxx
// ./opencascade/StepGeom_Parabola.hxx
// ./opencascade/StepGeom_ElementarySurface.hxx
// ./opencascade/StepGeom_DegeneratePcurve.hxx
// ./opencascade/StepGeom_BoundedCurve.hxx
// ./opencascade/StepGeom_KnotType.hxx
// ./opencascade/StepGeom_TrimmingSelect.hxx

// user-defined post
