#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ApplicationContext.hxx>
#include <StepBasic_Approval.hxx>
#include <StepBasic_ApprovalRole.hxx>
#include <StepBasic_ProductDefinition.hxx>
#include <StepBasic_ProductDefinitionReference.hxx>
#include <StepBasic_ProductDefinitionReferenceWithLocalRepresentation.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ExternalSource.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_IdentificationRole.hxx>
#include <StepBasic_ProductDefinitionRelationship.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ActionMethod.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_Product.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ContractType.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_VolumeUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <StepBasic_SecurityClassification.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ActionAssignment.hxx>
#include <StepBasic_ActionRequestAssignment.hxx>
#include <StepBasic_ApprovalAssignment.hxx>
#include <StepBasic_ApprovalDateTime.hxx>
#include <StepBasic_CertificationAssignment.hxx>
#include <StepBasic_ContractAssignment.hxx>
#include <StepBasic_DocumentReference.hxx>
#include <StepBasic_EffectivityAssignment.hxx>
#include <StepBasic_GroupAssignment.hxx>
#include <StepBasic_NameAssignment.hxx>
#include <StepBasic_SecurityClassificationAssignment.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <StepBasic_LengthUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <StepBasic_Person.hxx>
#include <StepBasic_Organization.hxx>
#include <StepBasic_PersonAndOrganization.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ProductDefinition.hxx>
#include <StepBasic_ActionMethod.hxx>
#include <StepBasic_VersionedActionRequest.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_CertificationType.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ApplicationContext.hxx>
#include <StepBasic_Date.hxx>
#include <StepBasic_LocalTime.hxx>
#include <StepBasic_DateAndTime.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_TimeUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ProductDefinitionFormation.hxx>
#include <StepBasic_ProductDefinitionContext.hxx>
#include <StepBasic_Certification.hxx>
#include <StepBasic_ThermodynamicTemperatureUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <StepBasic_AreaUnit.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureValueMember.hxx>
#include <StepBasic_ExternalSource.hxx>
#include <StepBasic_PersonAndOrganization.hxx>
#include <StepBasic_PersonAndOrganizationRole.hxx>
#include <StepBasic_Document.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <StepBasic_ApprovalStatus.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_Date.hxx>
#include <StepBasic_LocalTime.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ProductCategory.hxx>
#include <StepBasic_Approval.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_Approval.hxx>
#include <StepBasic_MeasureValueMember.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_Date.hxx>
#include <StepBasic_DateRole.hxx>
#include <StepBasic_SolidAngleUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <StepBasic_Organization.hxx>
#include <StepBasic_OrganizationRole.hxx>
#include <StepBasic_Action.hxx>
#include <StepBasic_VolumeUnit.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_VersionedActionRequest.hxx>
#include <StepBasic_Group.hxx>
#include <StepData_SelectMember.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ProductDefinitionFormation.hxx>
#include <StepBasic_ProductDefinitionContext.hxx>
#include <StepBasic_LengthUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_IdentificationRole.hxx>
#include <StepBasic_PlaneAngleUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <StepBasic_Approval.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ProductDefinitionFormation.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepData_SelectMember.hxx>
#include <StepBasic_Product.hxx>
#include <StepBasic_ProductDefinitionFormation.hxx>
#include <StepBasic_ProductDefinition.hxx>
#include <StepBasic_CharacterizedObject.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_DocumentType.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_TimeUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <StepBasic_CoordinatedUniversalTimeOffset.hxx>
#include <StepBasic_Contract.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_DocumentType.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_Document.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ApplicationContext.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MassUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_Group.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_Document.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ExternalSource.hxx>
#include <StepBasic_ExternalSource.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_Product.hxx>
#include <TCollection_HAsciiString.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ObjectRole.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ApplicationContext.hxx>
#include <StepBasic_Person.hxx>
#include <StepBasic_Organization.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_DateAndTime.hxx>
#include <StepBasic_DateTimeRole.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_ApplicationContext.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_NamedUnit.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_Document.hxx>
#include <StepBasic_PlaneAngleUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <StepBasic_SolidAngleUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_RatioUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <StepBasic_Effectivity.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_Document.hxx>
#include <StepBasic_NamedUnit.hxx>
#include <StepBasic_DerivedUnit.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_RatioUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <StepBasic_MassUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <TCollection_HAsciiString.hxx>
#include <StepBasic_SecurityClassificationLevel.hxx>
#include <StepBasic_AreaUnit.hxx>
#include <StepBasic_DimensionalExponents.hxx>

// module includes
#include <StepBasic_ProductContext.hxx>
#include <StepBasic_ApprovalPersonOrganization.hxx>
#include <StepBasic_EulerAngles.hxx>
#include <StepBasic_SizeMember.hxx>
#include <StepBasic_ProductDefinitionOrReference.hxx>
#include <StepBasic_HArray1OfProductContext.hxx>
#include <StepBasic_PlaneAngleUnit.hxx>
#include <StepBasic_CharacterizedObject.hxx>
#include <StepBasic_DigitalDocument.hxx>
#include <StepBasic_HArray1OfPerson.hxx>
#include <StepBasic_LengthMeasureWithUnit.hxx>
#include <StepBasic_ExternalIdentificationAssignment.hxx>
#include <StepBasic_ProductDefinitionEffectivity.hxx>
#include <StepBasic_VolumeUnit.hxx>
#include <StepBasic_Array1OfUncertaintyMeasureWithUnit.hxx>
#include <StepBasic_Action.hxx>
#include <StepBasic_TimeMeasureWithUnit.hxx>
#include <StepBasic_DateRole.hxx>
#include <StepBasic_ProductDefinitionFormationWithSpecifiedSource.hxx>
#include <StepBasic_ExternalSource.hxx>
#include <StepBasic_ProductRelatedProductCategory.hxx>
#include <StepBasic_HArray1OfOrganization.hxx>
#include <StepBasic_ApplicationContext.hxx>
#include <StepBasic_Array1OfProductDefinition.hxx>
#include <StepBasic_Contract.hxx>
#include <StepBasic_ObjectRole.hxx>
#include <StepBasic_DimensionalExponents.hxx>
#include <StepBasic_SiUnitAndVolumeUnit.hxx>
#include <StepBasic_NamedUnit.hxx>
#include <StepBasic_SecurityClassificationAssignment.hxx>
#include <StepBasic_DateTimeRole.hxx>
#include <StepBasic_Array1OfNamedUnit.hxx>
#include <StepBasic_RoleSelect.hxx>
#include <StepBasic_HArray1OfProductDefinition.hxx>
#include <StepBasic_SiUnit.hxx>
#include <StepBasic_ConversionBasedUnitAndLengthUnit.hxx>
#include <StepBasic_PersonOrganizationSelect.hxx>
#include <StepBasic_ProductDefinitionRelationship.hxx>
#include <StepBasic_ActionRequestSolution.hxx>
#include <StepBasic_Product.hxx>
#include <StepBasic_Array1OfPerson.hxx>
#include <StepBasic_Certification.hxx>
#include <StepBasic_DesignContext.hxx>
#include <StepBasic_Effectivity.hxx>
#include <StepBasic_HArray1OfUncertaintyMeasureWithUnit.hxx>
#include <StepBasic_ProductConceptContext.hxx>
#include <StepBasic_DateTimeSelect.hxx>
#include <StepBasic_Array1OfProduct.hxx>
#include <StepBasic_MassMeasureWithUnit.hxx>
#include <StepBasic_DocumentType.hxx>
#include <StepBasic_SiUnitAndTimeUnit.hxx>
#include <StepBasic_ProductDefinitionWithAssociatedDocuments.hxx>
#include <StepBasic_CertificationAssignment.hxx>
#include <StepBasic_SiUnitAndThermodynamicTemperatureUnit.hxx>
#include <StepBasic_ConversionBasedUnitAndAreaUnit.hxx>
#include <StepBasic_RatioMeasureWithUnit.hxx>
#include <StepBasic_UncertaintyMeasureWithUnit.hxx>
#include <StepBasic_ExternallyDefinedItem.hxx>
#include <StepBasic_PersonAndOrganizationAssignment.hxx>
#include <StepBasic_DocumentReference.hxx>
#include <StepBasic_ConversionBasedUnit.hxx>
#include <StepBasic_Approval.hxx>
#include <StepBasic_Source.hxx>
#include <StepBasic_DateAndTime.hxx>
#include <StepBasic_GeneralProperty.hxx>
#include <StepBasic_ProductCategoryRelationship.hxx>
#include <StepBasic_ApprovalAssignment.hxx>
#include <StepBasic_PersonalAddress.hxx>
#include <StepBasic_ApprovalRelationship.hxx>
#include <StepBasic_MeasureWithUnit.hxx>
#include <StepBasic_OrganizationalAddress.hxx>
#include <StepBasic_PlaneAngleMeasureWithUnit.hxx>
#include <StepBasic_DateAssignment.hxx>
#include <StepBasic_ConversionBasedUnitAndSolidAngleUnit.hxx>
#include <StepBasic_OrganizationAssignment.hxx>
#include <StepBasic_ActionAssignment.hxx>
#include <StepBasic_LengthUnit.hxx>
#include <StepBasic_ConversionBasedUnitAndVolumeUnit.hxx>
#include <StepBasic_ContractType.hxx>
#include <StepBasic_ActionRequestAssignment.hxx>
#include <StepBasic_SolidAngleMeasureWithUnit.hxx>
#include <StepBasic_GroupAssignment.hxx>
#include <StepBasic_SourceItem.hxx>
#include <StepBasic_AreaUnit.hxx>
#include <StepBasic_ProductDefinition.hxx>
#include <StepBasic_MassUnit.hxx>
#include <StepBasic_SiUnitAndLengthUnit.hxx>
#include <StepBasic_OrganizationRole.hxx>
#include <StepBasic_HArray1OfNamedUnit.hxx>
#include <StepBasic_DocumentProductEquivalence.hxx>
#include <StepBasic_IdentificationAssignment.hxx>
#include <StepBasic_ConversionBasedUnitAndPlaneAngleUnit.hxx>
#include <StepBasic_ApprovalDateTime.hxx>
#include <StepBasic_ApprovalRole.hxx>
#include <StepBasic_ProductDefinitionFormationRelationship.hxx>
#include <StepBasic_WeekOfYearAndDayDate.hxx>
#include <StepBasic_SecurityClassificationLevel.hxx>
#include <StepBasic_SizeSelect.hxx>
#include <StepBasic_ProductOrFormationOrDefinition.hxx>
#include <StepBasic_SolidAngleUnit.hxx>
#include <StepBasic_DocumentFile.hxx>
#include <StepBasic_ProductCategory.hxx>
#include <StepBasic_ConversionBasedUnitAndTimeUnit.hxx>
#include <StepBasic_LocalTime.hxx>
#include <StepBasic_ContractAssignment.hxx>
#include <StepBasic_Document.hxx>
#include <StepBasic_Date.hxx>
#include <StepBasic_HArray1OfApproval.hxx>
#include <StepBasic_DocumentProductAssociation.hxx>
#include <StepBasic_ApplicationContextElement.hxx>
#include <StepBasic_Group.hxx>
#include <StepBasic_Address.hxx>
#include <StepBasic_SiUnitAndMassUnit.hxx>
#include <StepBasic_Person.hxx>
#include <StepBasic_VersionedActionRequest.hxx>
#include <StepBasic_HArray1OfDocument.hxx>
#include <StepBasic_RatioUnit.hxx>
#include <StepBasic_GroupRelationship.hxx>
#include <StepBasic_ApprovalStatus.hxx>
#include <StepBasic_DocumentUsageConstraint.hxx>
#include <StepBasic_SiUnitName.hxx>
#include <StepBasic_ProductDefinitionReference.hxx>
#include <StepBasic_ProductDefinitionReferenceWithLocalRepresentation.hxx>
#include <StepBasic_ProductDefinitionFormation.hxx>
#include <StepBasic_ActionMethod.hxx>
#include <StepBasic_MechanicalContext.hxx>
#include <StepBasic_NameAssignment.hxx>
#include <StepBasic_MeasureValueMember.hxx>
#include <StepBasic_OrdinalDate.hxx>
#include <StepBasic_ThermodynamicTemperatureUnit.hxx>
#include <StepBasic_RoleAssociation.hxx>
#include <StepBasic_PhysicallyModeledProductDefinition.hxx>
#include <StepBasic_ProductDefinitionContext.hxx>
#include <StepBasic_PersonAndOrganization.hxx>
#include <StepBasic_HArray1OfDerivedUnitElement.hxx>
#include <StepBasic_PersonAndOrganizationRole.hxx>
#include <StepBasic_ProductType.hxx>
#include <StepBasic_CalendarDate.hxx>
#include <StepBasic_DateAndTimeAssignment.hxx>
#include <StepBasic_Array1OfDerivedUnitElement.hxx>
#include <StepBasic_ApplicationProtocolDefinition.hxx>
#include <StepBasic_Organization.hxx>
#include <StepBasic_DerivedUnitElement.hxx>
#include <StepBasic_TimeUnit.hxx>
#include <StepBasic_Array1OfDocument.hxx>
#include <StepBasic_DocumentRepresentationType.hxx>
#include <StepBasic_Array1OfProductContext.hxx>
#include <StepBasic_CoordinatedUniversalTimeOffset.hxx>
#include <StepBasic_Array1OfOrganization.hxx>
#include <StepBasic_SiUnitAndPlaneAngleUnit.hxx>
#include <StepBasic_Array1OfApproval.hxx>
#include <StepBasic_DerivedUnit.hxx>
#include <StepBasic_SiPrefix.hxx>
#include <StepBasic_SiUnitAndSolidAngleUnit.hxx>
#include <StepBasic_IdentificationRole.hxx>
#include <StepBasic_SiUnitAndRatioUnit.hxx>
#include <StepBasic_EffectivityAssignment.hxx>
#include <StepBasic_AheadOrBehind.hxx>
#include <StepBasic_DocumentRelationship.hxx>
#include <StepBasic_Unit.hxx>
#include <StepBasic_CertificationType.hxx>
#include <StepBasic_ConversionBasedUnitAndRatioUnit.hxx>
#include <StepBasic_ConversionBasedUnitAndMassUnit.hxx>
#include <StepBasic_SecurityClassification.hxx>
#include <StepBasic_SiUnitAndAreaUnit.hxx>
#include <StepBasic_HArray1OfProduct.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/StepBasic_ProductContext.hxx
// ./opencascade/StepBasic_ApprovalPersonOrganization.hxx
// ./opencascade/StepBasic_EulerAngles.hxx
// ./opencascade/StepBasic_SizeMember.hxx
// ./opencascade/StepBasic_ProductDefinitionOrReference.hxx
// ./opencascade/StepBasic_HArray1OfProductContext.hxx
// ./opencascade/StepBasic_PlaneAngleUnit.hxx
// ./opencascade/StepBasic_CharacterizedObject.hxx
// ./opencascade/StepBasic_DigitalDocument.hxx
// ./opencascade/StepBasic_HArray1OfPerson.hxx
// ./opencascade/StepBasic_LengthMeasureWithUnit.hxx
// ./opencascade/StepBasic_ExternalIdentificationAssignment.hxx
// ./opencascade/StepBasic_ProductDefinitionEffectivity.hxx
// ./opencascade/StepBasic_VolumeUnit.hxx
// ./opencascade/StepBasic_Array1OfUncertaintyMeasureWithUnit.hxx
// ./opencascade/StepBasic_Action.hxx
// ./opencascade/StepBasic_TimeMeasureWithUnit.hxx
// ./opencascade/StepBasic_DateRole.hxx
// ./opencascade/StepBasic_ProductDefinitionFormationWithSpecifiedSource.hxx
// ./opencascade/StepBasic_ExternalSource.hxx
// ./opencascade/StepBasic_ProductRelatedProductCategory.hxx
// ./opencascade/StepBasic_HArray1OfOrganization.hxx
// ./opencascade/StepBasic_ApplicationContext.hxx
// ./opencascade/StepBasic_Array1OfProductDefinition.hxx
// ./opencascade/StepBasic_Contract.hxx
// ./opencascade/StepBasic_ObjectRole.hxx
// ./opencascade/StepBasic_DimensionalExponents.hxx
// ./opencascade/StepBasic_SiUnitAndVolumeUnit.hxx
// ./opencascade/StepBasic_NamedUnit.hxx
// ./opencascade/StepBasic_SecurityClassificationAssignment.hxx
// ./opencascade/StepBasic_DateTimeRole.hxx
// ./opencascade/StepBasic_Array1OfNamedUnit.hxx
// ./opencascade/StepBasic_RoleSelect.hxx
// ./opencascade/StepBasic_HArray1OfProductDefinition.hxx
// ./opencascade/StepBasic_SiUnit.hxx
// ./opencascade/StepBasic_ConversionBasedUnitAndLengthUnit.hxx
// ./opencascade/StepBasic_PersonOrganizationSelect.hxx
// ./opencascade/StepBasic_ProductDefinitionRelationship.hxx
// ./opencascade/StepBasic_ActionRequestSolution.hxx
// ./opencascade/StepBasic_Product.hxx
// ./opencascade/StepBasic_Array1OfPerson.hxx
// ./opencascade/StepBasic_Certification.hxx
// ./opencascade/StepBasic_DesignContext.hxx
// ./opencascade/StepBasic_Effectivity.hxx
// ./opencascade/StepBasic_HArray1OfUncertaintyMeasureWithUnit.hxx
// ./opencascade/StepBasic_ProductConceptContext.hxx
// ./opencascade/StepBasic_DateTimeSelect.hxx
// ./opencascade/StepBasic_Array1OfProduct.hxx
// ./opencascade/StepBasic_MassMeasureWithUnit.hxx
// ./opencascade/StepBasic_DocumentType.hxx
// ./opencascade/StepBasic_SiUnitAndTimeUnit.hxx
// ./opencascade/StepBasic_ProductDefinitionWithAssociatedDocuments.hxx
// ./opencascade/StepBasic_CertificationAssignment.hxx
// ./opencascade/StepBasic_SiUnitAndThermodynamicTemperatureUnit.hxx
// ./opencascade/StepBasic_ConversionBasedUnitAndAreaUnit.hxx
// ./opencascade/StepBasic_RatioMeasureWithUnit.hxx
// ./opencascade/StepBasic_UncertaintyMeasureWithUnit.hxx
// ./opencascade/StepBasic_ExternallyDefinedItem.hxx
// ./opencascade/StepBasic_PersonAndOrganizationAssignment.hxx
// ./opencascade/StepBasic_DocumentReference.hxx
// ./opencascade/StepBasic_ConversionBasedUnit.hxx
// ./opencascade/StepBasic_Approval.hxx
// ./opencascade/StepBasic_Source.hxx
// ./opencascade/StepBasic_DateAndTime.hxx
// ./opencascade/StepBasic_GeneralProperty.hxx
// ./opencascade/StepBasic_ProductCategoryRelationship.hxx
// ./opencascade/StepBasic_ApprovalAssignment.hxx
// ./opencascade/StepBasic_PersonalAddress.hxx
// ./opencascade/StepBasic_ApprovalRelationship.hxx
// ./opencascade/StepBasic_MeasureWithUnit.hxx
// ./opencascade/StepBasic_OrganizationalAddress.hxx
// ./opencascade/StepBasic_PlaneAngleMeasureWithUnit.hxx
// ./opencascade/StepBasic_DateAssignment.hxx
// ./opencascade/StepBasic_ConversionBasedUnitAndSolidAngleUnit.hxx
// ./opencascade/StepBasic_OrganizationAssignment.hxx
// ./opencascade/StepBasic_ActionAssignment.hxx
// ./opencascade/StepBasic_LengthUnit.hxx
// ./opencascade/StepBasic_ConversionBasedUnitAndVolumeUnit.hxx
// ./opencascade/StepBasic_ContractType.hxx
// ./opencascade/StepBasic_ActionRequestAssignment.hxx
// ./opencascade/StepBasic_SolidAngleMeasureWithUnit.hxx
// ./opencascade/StepBasic_GroupAssignment.hxx
// ./opencascade/StepBasic_SourceItem.hxx
// ./opencascade/StepBasic_AreaUnit.hxx
// ./opencascade/StepBasic_ProductDefinition.hxx
// ./opencascade/StepBasic_MassUnit.hxx
// ./opencascade/StepBasic_SiUnitAndLengthUnit.hxx
// ./opencascade/StepBasic_OrganizationRole.hxx
// ./opencascade/StepBasic_HArray1OfNamedUnit.hxx
// ./opencascade/StepBasic_DocumentProductEquivalence.hxx
// ./opencascade/StepBasic_IdentificationAssignment.hxx
// ./opencascade/StepBasic_ConversionBasedUnitAndPlaneAngleUnit.hxx
// ./opencascade/StepBasic_ApprovalDateTime.hxx
// ./opencascade/StepBasic_ApprovalRole.hxx
// ./opencascade/StepBasic_ProductDefinitionFormationRelationship.hxx
// ./opencascade/StepBasic_WeekOfYearAndDayDate.hxx
// ./opencascade/StepBasic_SecurityClassificationLevel.hxx
// ./opencascade/StepBasic_SizeSelect.hxx
// ./opencascade/StepBasic_ProductOrFormationOrDefinition.hxx
// ./opencascade/StepBasic_SolidAngleUnit.hxx
// ./opencascade/StepBasic_DocumentFile.hxx
// ./opencascade/StepBasic_ProductCategory.hxx
// ./opencascade/StepBasic_ConversionBasedUnitAndTimeUnit.hxx
// ./opencascade/StepBasic_LocalTime.hxx
// ./opencascade/StepBasic_ContractAssignment.hxx
// ./opencascade/StepBasic_Document.hxx
// ./opencascade/StepBasic_Date.hxx
// ./opencascade/StepBasic_HArray1OfApproval.hxx
// ./opencascade/StepBasic_DocumentProductAssociation.hxx
// ./opencascade/StepBasic_ApplicationContextElement.hxx
// ./opencascade/StepBasic_Group.hxx
// ./opencascade/StepBasic_Address.hxx
// ./opencascade/StepBasic_SiUnitAndMassUnit.hxx
// ./opencascade/StepBasic_Person.hxx
// ./opencascade/StepBasic_VersionedActionRequest.hxx
// ./opencascade/StepBasic_HArray1OfDocument.hxx
// ./opencascade/StepBasic_RatioUnit.hxx
// ./opencascade/StepBasic_GroupRelationship.hxx
// ./opencascade/StepBasic_ApprovalStatus.hxx
// ./opencascade/StepBasic_DocumentUsageConstraint.hxx
// ./opencascade/StepBasic_SiUnitName.hxx
// ./opencascade/StepBasic_ProductDefinitionReference.hxx
// ./opencascade/StepBasic_ProductDefinitionReferenceWithLocalRepresentation.hxx
// ./opencascade/StepBasic_ProductDefinitionFormation.hxx
// ./opencascade/StepBasic_ActionMethod.hxx
// ./opencascade/StepBasic_MechanicalContext.hxx
// ./opencascade/StepBasic_NameAssignment.hxx
// ./opencascade/StepBasic_MeasureValueMember.hxx
// ./opencascade/StepBasic_OrdinalDate.hxx
// ./opencascade/StepBasic_ThermodynamicTemperatureUnit.hxx
// ./opencascade/StepBasic_RoleAssociation.hxx
// ./opencascade/StepBasic_PhysicallyModeledProductDefinition.hxx
// ./opencascade/StepBasic_ProductDefinitionContext.hxx
// ./opencascade/StepBasic_PersonAndOrganization.hxx
// ./opencascade/StepBasic_HArray1OfDerivedUnitElement.hxx
// ./opencascade/StepBasic_PersonAndOrganizationRole.hxx
// ./opencascade/StepBasic_ProductType.hxx
// ./opencascade/StepBasic_CalendarDate.hxx
// ./opencascade/StepBasic_DateAndTimeAssignment.hxx
// ./opencascade/StepBasic_Array1OfDerivedUnitElement.hxx
// ./opencascade/StepBasic_ApplicationProtocolDefinition.hxx
// ./opencascade/StepBasic_Organization.hxx
// ./opencascade/StepBasic_DerivedUnitElement.hxx
// ./opencascade/StepBasic_TimeUnit.hxx
// ./opencascade/StepBasic_Array1OfDocument.hxx
// ./opencascade/StepBasic_DocumentRepresentationType.hxx
// ./opencascade/StepBasic_Array1OfProductContext.hxx
// ./opencascade/StepBasic_CoordinatedUniversalTimeOffset.hxx
// ./opencascade/StepBasic_Array1OfOrganization.hxx
// ./opencascade/StepBasic_SiUnitAndPlaneAngleUnit.hxx
// ./opencascade/StepBasic_Array1OfApproval.hxx
// ./opencascade/StepBasic_DerivedUnit.hxx
// ./opencascade/StepBasic_SiPrefix.hxx
// ./opencascade/StepBasic_SiUnitAndSolidAngleUnit.hxx
// ./opencascade/StepBasic_IdentificationRole.hxx
// ./opencascade/StepBasic_SiUnitAndRatioUnit.hxx
// ./opencascade/StepBasic_EffectivityAssignment.hxx
// ./opencascade/StepBasic_AheadOrBehind.hxx
// ./opencascade/StepBasic_DocumentRelationship.hxx
// ./opencascade/StepBasic_Unit.hxx
// ./opencascade/StepBasic_CertificationType.hxx
// ./opencascade/StepBasic_ConversionBasedUnitAndRatioUnit.hxx
// ./opencascade/StepBasic_ConversionBasedUnitAndMassUnit.hxx
// ./opencascade/StepBasic_SecurityClassification.hxx
// ./opencascade/StepBasic_SiUnitAndAreaUnit.hxx
// ./opencascade/StepBasic_HArray1OfProduct.hxx

// user-defined post
