#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations

// module includes
#include <TColStd_Array1OfAsciiString.hxx>
#include <TColStd_DataMapIteratorOfDataMapOfIntegerReal.hxx>
#include <TColStd_HArray1OfBoolean.hxx>
#include <TColStd_HArray1OfByte.hxx>
#include <TColStd_MapIteratorOfMapOfInteger.hxx>
#include <TColStd_HSequenceOfAsciiString.hxx>
#include <TColStd_MapTransientHasher.hxx>
#include <TColStd_MapIteratorOfMapOfReal.hxx>
#include <TColStd_HArray1OfCharacter.hxx>
#include <TColStd_Array1OfByte.hxx>
#include <TColStd_HArray2OfCharacter.hxx>
#include <TColStd_DataMapOfIntegerInteger.hxx>
#include <TColStd_SequenceOfBoolean.hxx>
#include <TColStd_HSequenceOfTransient.hxx>
#include <TColStd_MapOfReal.hxx>
#include <TColStd_Array1OfInteger.hxx>
#include <TColStd_HArray2OfReal.hxx>
#include <TColStd_MapOfInteger.hxx>
#include <TColStd_HSequenceOfReal.hxx>
#include <TColStd_SequenceOfAddress.hxx>
#include <TColStd_HArray1OfTransient.hxx>
#include <TColStd_MapIteratorOfPackedMapOfInteger.hxx>
#include <TColStd_SequenceOfAsciiString.hxx>
#include <TColStd_SequenceOfInteger.hxx>
#include <TColStd_Array1OfBoolean.hxx>
#include <TColStd_DataMapOfAsciiStringInteger.hxx>
#include <TColStd_SequenceOfHAsciiString.hxx>
#include <TColStd_IndexedMapOfTransient.hxx>
#include <TColStd_HArray1OfInteger.hxx>
#include <TColStd_HArray1OfAsciiString.hxx>
#include <TColStd_DataMapIteratorOfDataMapOfIntegerInteger.hxx>
#include <TColStd_MapOfAsciiString.hxx>
#include <TColStd_IndexedDataMapOfTransientTransient.hxx>
#include <TColStd_DataMapOfTransientTransient.hxx>
#include <TColStd_ListIteratorOfListOfReal.hxx>
#include <TColStd_Array1OfListOfInteger.hxx>
#include <TColStd_HArray1OfListOfInteger.hxx>
#include <TColStd_DataMapIteratorOfDataMapOfTransientTransient.hxx>
#include <TColStd_HArray2OfTransient.hxx>
#include <TColStd_Array1OfReal.hxx>
#include <TColStd_HSequenceOfHAsciiString.hxx>
#include <TColStd_ListIteratorOfListOfInteger.hxx>
#include <TColStd_IndexedDataMapOfStringString.hxx>
#include <TColStd_HArray1OfExtendedString.hxx>
#include <TColStd_Array1OfCharacter.hxx>
#include <TColStd_SequenceOfExtendedString.hxx>
#include <TColStd_ListOfAsciiString.hxx>
#include <TColStd_Array2OfTransient.hxx>
#include <TColStd_Array1OfTransient.hxx>
#include <TColStd_PackedMapOfInteger.hxx>
#include <TColStd_DataMapIteratorOfDataMapOfStringInteger.hxx>
#include <TColStd_Array2OfBoolean.hxx>
#include <TColStd_DataMapIteratorOfDataMapOfIntegerTransient.hxx>
#include <TColStd_ListOfTransient.hxx>
#include <TColStd_SequenceOfReal.hxx>
#include <TColStd_DataMapIteratorOfDataMapOfAsciiStringInteger.hxx>
#include <TColStd_MapIntegerHasher.hxx>
#include <TColStd_HArray2OfBoolean.hxx>
#include <TColStd_ListIteratorOfListOfTransient.hxx>
#include <TColStd_ListOfReal.hxx>
#include <TColStd_Array1OfExtendedString.hxx>
#include <TColStd_DataMapOfStringInteger.hxx>
#include <TColStd_HSequenceOfHExtendedString.hxx>
#include <TColStd_HArray2OfInteger.hxx>
#include <TColStd_DataMapOfIntegerListOfInteger.hxx>
#include <TColStd_MapRealHasher.hxx>
#include <TColStd_MapIteratorOfMapOfTransient.hxx>
#include <TColStd_DataMapOfIntegerTransient.hxx>
#include <TColStd_SequenceOfHExtendedString.hxx>
#include <TColStd_DataMapIteratorOfDataMapOfIntegerListOfInteger.hxx>
#include <TColStd_IndexedMapOfReal.hxx>
#include <TColStd_MapIteratorOfMapOfAsciiString.hxx>
#include <TColStd_Array2OfInteger.hxx>
#include <TColStd_ListOfInteger.hxx>
#include <TColStd_MapOfTransient.hxx>
#include <TColStd_HPackedMapOfInteger.hxx>
#include <TColStd_IndexedMapOfInteger.hxx>
#include <TColStd_Array2OfReal.hxx>
#include <TColStd_ListIteratorOfListOfAsciiString.hxx>
#include <TColStd_DataMapOfIntegerReal.hxx>
#include <TColStd_Array2OfCharacter.hxx>
#include <TColStd_HSequenceOfExtendedString.hxx>
#include <TColStd_HSequenceOfInteger.hxx>
#include <TColStd_HArray1OfReal.hxx>
#include <TColStd_SequenceOfTransient.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/TColStd_Array1OfAsciiString.hxx
// ./opencascade/TColStd_DataMapIteratorOfDataMapOfIntegerReal.hxx
// ./opencascade/TColStd_HArray1OfBoolean.hxx
// ./opencascade/TColStd_HArray1OfByte.hxx
// ./opencascade/TColStd_MapIteratorOfMapOfInteger.hxx
// ./opencascade/TColStd_HSequenceOfAsciiString.hxx
// ./opencascade/TColStd_MapTransientHasher.hxx
// ./opencascade/TColStd_MapIteratorOfMapOfReal.hxx
// ./opencascade/TColStd_HArray1OfCharacter.hxx
// ./opencascade/TColStd_Array1OfByte.hxx
// ./opencascade/TColStd_HArray2OfCharacter.hxx
// ./opencascade/TColStd_DataMapOfIntegerInteger.hxx
// ./opencascade/TColStd_SequenceOfBoolean.hxx
// ./opencascade/TColStd_HSequenceOfTransient.hxx
// ./opencascade/TColStd_MapOfReal.hxx
// ./opencascade/TColStd_Array1OfInteger.hxx
// ./opencascade/TColStd_HArray2OfReal.hxx
// ./opencascade/TColStd_MapOfInteger.hxx
// ./opencascade/TColStd_HSequenceOfReal.hxx
// ./opencascade/TColStd_SequenceOfAddress.hxx
// ./opencascade/TColStd_HArray1OfTransient.hxx
// ./opencascade/TColStd_MapIteratorOfPackedMapOfInteger.hxx
// ./opencascade/TColStd_SequenceOfAsciiString.hxx
// ./opencascade/TColStd_SequenceOfInteger.hxx
// ./opencascade/TColStd_Array1OfBoolean.hxx
// ./opencascade/TColStd_DataMapOfAsciiStringInteger.hxx
// ./opencascade/TColStd_SequenceOfHAsciiString.hxx
// ./opencascade/TColStd_IndexedMapOfTransient.hxx
// ./opencascade/TColStd_HArray1OfInteger.hxx
// ./opencascade/TColStd_HArray1OfAsciiString.hxx
// ./opencascade/TColStd_DataMapIteratorOfDataMapOfIntegerInteger.hxx
// ./opencascade/TColStd_MapOfAsciiString.hxx
// ./opencascade/TColStd_IndexedDataMapOfTransientTransient.hxx
// ./opencascade/TColStd_DataMapOfTransientTransient.hxx
// ./opencascade/TColStd_ListIteratorOfListOfReal.hxx
// ./opencascade/TColStd_Array1OfListOfInteger.hxx
// ./opencascade/TColStd_HArray1OfListOfInteger.hxx
// ./opencascade/TColStd_DataMapIteratorOfDataMapOfTransientTransient.hxx
// ./opencascade/TColStd_HArray2OfTransient.hxx
// ./opencascade/TColStd_Array1OfReal.hxx
// ./opencascade/TColStd_HSequenceOfHAsciiString.hxx
// ./opencascade/TColStd_ListIteratorOfListOfInteger.hxx
// ./opencascade/TColStd_IndexedDataMapOfStringString.hxx
// ./opencascade/TColStd_HArray1OfExtendedString.hxx
// ./opencascade/TColStd_Array1OfCharacter.hxx
// ./opencascade/TColStd_SequenceOfExtendedString.hxx
// ./opencascade/TColStd_ListOfAsciiString.hxx
// ./opencascade/TColStd_Array2OfTransient.hxx
// ./opencascade/TColStd_Array1OfTransient.hxx
// ./opencascade/TColStd_PackedMapOfInteger.hxx
// ./opencascade/TColStd_DataMapIteratorOfDataMapOfStringInteger.hxx
// ./opencascade/TColStd_Array2OfBoolean.hxx
// ./opencascade/TColStd_DataMapIteratorOfDataMapOfIntegerTransient.hxx
// ./opencascade/TColStd_ListOfTransient.hxx
// ./opencascade/TColStd_SequenceOfReal.hxx
// ./opencascade/TColStd_DataMapIteratorOfDataMapOfAsciiStringInteger.hxx
// ./opencascade/TColStd_MapIntegerHasher.hxx
// ./opencascade/TColStd_HArray2OfBoolean.hxx
// ./opencascade/TColStd_ListIteratorOfListOfTransient.hxx
// ./opencascade/TColStd_ListOfReal.hxx
// ./opencascade/TColStd_Array1OfExtendedString.hxx
// ./opencascade/TColStd_DataMapOfStringInteger.hxx
// ./opencascade/TColStd_HSequenceOfHExtendedString.hxx
// ./opencascade/TColStd_HArray2OfInteger.hxx
// ./opencascade/TColStd_DataMapOfIntegerListOfInteger.hxx
// ./opencascade/TColStd_MapRealHasher.hxx
// ./opencascade/TColStd_MapIteratorOfMapOfTransient.hxx
// ./opencascade/TColStd_DataMapOfIntegerTransient.hxx
// ./opencascade/TColStd_SequenceOfHExtendedString.hxx
// ./opencascade/TColStd_DataMapIteratorOfDataMapOfIntegerListOfInteger.hxx
// ./opencascade/TColStd_IndexedMapOfReal.hxx
// ./opencascade/TColStd_MapIteratorOfMapOfAsciiString.hxx
// ./opencascade/TColStd_Array2OfInteger.hxx
// ./opencascade/TColStd_ListOfInteger.hxx
// ./opencascade/TColStd_MapOfTransient.hxx
// ./opencascade/TColStd_HPackedMapOfInteger.hxx
// ./opencascade/TColStd_IndexedMapOfInteger.hxx
// ./opencascade/TColStd_Array2OfReal.hxx
// ./opencascade/TColStd_ListIteratorOfListOfAsciiString.hxx
// ./opencascade/TColStd_DataMapOfIntegerReal.hxx
// ./opencascade/TColStd_Array2OfCharacter.hxx
// ./opencascade/TColStd_HSequenceOfExtendedString.hxx
// ./opencascade/TColStd_HSequenceOfInteger.hxx
// ./opencascade/TColStd_HArray1OfReal.hxx
// ./opencascade/TColStd_SequenceOfTransient.hxx

// user-defined post
