#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <Standard_NoMoreObject.hxx>
#include <TopoDS_Shape.hxx>
#include <TNaming_TranslateTool.hxx>
#include <TopLoc_Location.hxx>
#include <TNaming_NamedShape.hxx>
#include <TopoDS_Shape.hxx>
#include <TNaming_NamedShape.hxx>
#include <TNaming_UsedShapes.hxx>
#include <TNaming_NamedShape.hxx>
#include <Standard_ConstructionError.hxx>
#include <TDF_Label.hxx>
#include <TopoDS_Shape.hxx>
#include <TNaming_UsedShapes.hxx>
#include <TDF_Label.hxx>
#include <TopoDS_Shape.hxx>
#include <TNaming_Localizer.hxx>
#include <TNaming_OldShapeIterator.hxx>
#include <TNaming_UsedShapes.hxx>
#include <TNaming_Localizer.hxx>
#include <TNaming_DeltaOnModification.hxx>
#include <TNaming_NamedShape.hxx>
#include <Standard_NoMoreObject.hxx>
#include <Standard_NoSuchObject.hxx>
#include <TNaming_Tool.hxx>
#include <TNaming_Localizer.hxx>
#include <TNaming_Naming.hxx>
#include <TopoDS_Shape.hxx>
#include <TNaming_UsedShapes.hxx>
#include <TDF_Label.hxx>
#include <TNaming_Iterator.hxx>
#include <TNaming_NamedShape.hxx>
#include <Standard_NoMoreObject.hxx>
#include <Standard_NoSuchObject.hxx>
#include <TNaming_Tool.hxx>
#include <TopoDS_Shape.hxx>
#include <TNaming_UsedShapes.hxx>
#include <TDF_Label.hxx>
#include <TNaming_Builder.hxx>
#include <TNaming_Iterator.hxx>
#include <TNaming_NewShapeIterator.hxx>
#include <TNaming_OldShapeIterator.hxx>
#include <Standard_GUID.hxx>
#include <TopoDS_Shape.hxx>
#include <TDF_DeltaOnModification.hxx>
#include <TDF_DeltaOnRemoval.hxx>
#include <TDF_RelocationTable.hxx>
#include <TDF_DataSet.hxx>
#include <TDF_AttributeDelta.hxx>
#include <Standard_NoMoreObject.hxx>
#include <Standard_NoSuchObject.hxx>
#include <TNaming_Tool.hxx>
#include <TNaming_Name.hxx>
#include <TNaming_Naming.hxx>
#include <TopoDS_Shape.hxx>
#include <TNaming_UsedShapes.hxx>
#include <TDF_Label.hxx>
#include <TNaming_Iterator.hxx>
#include <TNaming_NamedShape.hxx>
#include <TNaming_NamedShape.hxx>
#include <TopoDS_Shape.hxx>
#include <TNaming_NamedShape.hxx>
#include <TDF_Label.hxx>
#include <TNaming_NamedShape.hxx>
#include <TNaming_NamedShape.hxx>
#include <Standard_NoMoreObject.hxx>
#include <Standard_NoSuchObject.hxx>
#include <TNaming_NewShapeIterator.hxx>
#include <TNaming_OldShapeIterator.hxx>
#include <TNaming_NamedShape.hxx>
#include <TDF_Label.hxx>
#include <TopoDS_Shape.hxx>
#include <TDF_RelocationTable.hxx>
#include <Standard_GUID.hxx>
#include <TDF_RelocationTable.hxx>
#include <TDF_DataSet.hxx>
#include <TDF_IDFilter.hxx>
#include <TDF_Label.hxx>
#include <TNaming_NamedShape.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Wire.hxx>
#include <TopoDS_Solid.hxx>
#include <TopoDS_Shell.hxx>
#include <TNaming_CopyShape.hxx>
#include <TNaming_TranslateTool.hxx>
#include <TNaming_Translator.hxx>
#include <TNaming_NamedShape.hxx>
#include <TNaming_UsedShapes.hxx>
#include <TNaming_Builder.hxx>
#include <TNaming_Tool.hxx>
#include <TNaming_Iterator.hxx>
#include <TNaming_NewShapeIterator.hxx>
#include <TNaming_OldShapeIterator.hxx>
#include <TNaming_SameShapeIterator.hxx>
#include <TNaming_Name.hxx>
#include <TNaming_Naming.hxx>
#include <TNaming_Selector.hxx>
#include <TNaming_DeltaOnRemoval.hxx>
#include <TNaming_DeltaOnModification.hxx>
#include <TNaming_RefShape.hxx>
#include <TNaming_Scope.hxx>
#include <TNaming_Identifier.hxx>
#include <TNaming_Localizer.hxx>
#include <TNaming_ShapesSet.hxx>
#include <TNaming_IteratorOnShapesSet.hxx>
#include <TNaming_NamingTool.hxx>
#include <TNaming_Builder.hxx>
#include <Standard_GUID.hxx>
#include <TDF_AttributeDelta.hxx>
#include <TDF_DeltaOnAddition.hxx>
#include <TDF_DeltaOnRemoval.hxx>
#include <TDF_RelocationTable.hxx>
#include <TDF_DataSet.hxx>
#include <TNaming_RefShape.hxx>

// module includes
#include <TNaming_IteratorOnShapesSet.hxx>
#include <TNaming_CopyShape.hxx>
#include <TNaming_PtrAttribute.hxx>
#include <TNaming_Scope.hxx>
#include <TNaming_ListIteratorOfListOfNamedShape.hxx>
#include <TNaming_Builder.hxx>
#include <TNaming_NamedShapeHasher.hxx>
#include <TNaming_Localizer.hxx>
#include <TNaming_ShapesSet.hxx>
#include <TNaming_TranslateTool.hxx>
#include <TNaming_ListOfNamedShape.hxx>
#include <TNaming_ListOfMapOfShape.hxx>
#include <TNaming_Tool.hxx>
#include <TNaming_Identifier.hxx>
#include <TNaming_DeltaOnRemoval.hxx>
#include <TNaming_ListIteratorOfListOfMapOfShape.hxx>
#include <TNaming_MapIteratorOfMapOfNamedShape.hxx>
#include <TNaming_DataMapOfShapePtrRefShape.hxx>
#include <TNaming_OldShapeIterator.hxx>
#include <TNaming_ListIteratorOfListOfIndexedDataMapOfShapeListOfShape.hxx>
#include <TNaming_SameShapeIterator.hxx>
#include <TNaming_NamedShape.hxx>
#include <TNaming_NewShapeIterator.hxx>
#include <TNaming_DataMapIteratorOfDataMapOfShapePtrRefShape.hxx>
#include <TNaming_DeltaOnModification.hxx>
#include <TNaming_Selector.hxx>
#include <TNaming_Translator.hxx>
#include <TNaming_RefShape.hxx>
#include <TNaming_NamingTool.hxx>
#include <TNaming_Iterator.hxx>
#include <TNaming_NameType.hxx>
#include <TNaming_Name.hxx>
#include <TNaming_Naming.hxx>
#include <TNaming_DataMapOfShapeShapesSet.hxx>
#include <TNaming_MapOfNamedShape.hxx>
#include <TNaming_Evolution.hxx>
#include <TNaming_NCollections.hxx>
#include <TNaming.hxx>
#include <TNaming_DataMapIteratorOfDataMapOfShapeShapesSet.hxx>
#include <TNaming_ListOfIndexedDataMapOfShapeListOfShape.hxx>
#include <TNaming_UsedShapes.hxx>
#include <TNaming_PtrNode.hxx>
#include <TNaming_PtrRefShape.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/TNaming_IteratorOnShapesSet.hxx
// ./opencascade/TNaming_CopyShape.hxx
// ./opencascade/TNaming_PtrAttribute.hxx
// ./opencascade/TNaming_Scope.hxx
// ./opencascade/TNaming_ListIteratorOfListOfNamedShape.hxx
// ./opencascade/TNaming_Builder.hxx
// ./opencascade/TNaming_NamedShapeHasher.hxx
// ./opencascade/TNaming_Localizer.hxx
// ./opencascade/TNaming_ShapesSet.hxx
// ./opencascade/TNaming_TranslateTool.hxx
// ./opencascade/TNaming_ListOfNamedShape.hxx
// ./opencascade/TNaming_ListOfMapOfShape.hxx
// ./opencascade/TNaming_Tool.hxx
// ./opencascade/TNaming_Identifier.hxx
// ./opencascade/TNaming_DeltaOnRemoval.hxx
// ./opencascade/TNaming_ListIteratorOfListOfMapOfShape.hxx
// ./opencascade/TNaming_MapIteratorOfMapOfNamedShape.hxx
// ./opencascade/TNaming_DataMapOfShapePtrRefShape.hxx
// ./opencascade/TNaming_OldShapeIterator.hxx
// ./opencascade/TNaming_ListIteratorOfListOfIndexedDataMapOfShapeListOfShape.hxx
// ./opencascade/TNaming_SameShapeIterator.hxx
// ./opencascade/TNaming_NamedShape.hxx
// ./opencascade/TNaming_NewShapeIterator.hxx
// ./opencascade/TNaming_DataMapIteratorOfDataMapOfShapePtrRefShape.hxx
// ./opencascade/TNaming_DeltaOnModification.hxx
// ./opencascade/TNaming_Selector.hxx
// ./opencascade/TNaming_Translator.hxx
// ./opencascade/TNaming_RefShape.hxx
// ./opencascade/TNaming_NamingTool.hxx
// ./opencascade/TNaming_Iterator.hxx
// ./opencascade/TNaming_NameType.hxx
// ./opencascade/TNaming_Name.hxx
// ./opencascade/TNaming_Naming.hxx
// ./opencascade/TNaming_DataMapOfShapeShapesSet.hxx
// ./opencascade/TNaming_MapOfNamedShape.hxx
// ./opencascade/TNaming_Evolution.hxx
// ./opencascade/TNaming_NCollections.hxx
// ./opencascade/TNaming.hxx
// ./opencascade/TNaming_DataMapIteratorOfDataMapOfShapeShapesSet.hxx
// ./opencascade/TNaming_ListOfIndexedDataMapOfShapeListOfShape.hxx
// ./opencascade/TNaming_UsedShapes.hxx
// ./opencascade/TNaming_PtrNode.hxx
// ./opencascade/TNaming_PtrRefShape.hxx

// user-defined post
