#pragma once

// pybind 11 related includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Standard Handle
#include <Standard_Handle.hxx>

// includes to resolve forward declarations
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_Point.hxx>
#include <TopOpeBRepDS_Curve.hxx>
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_Surface.hxx>
#include <TopoDS_Edge.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <Geom_Curve.hxx>
#include <Geom2d_Curve.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom2d_BSplineCurve.hxx>
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopoDS_Edge.hxx>
#include <Geom_Curve.hxx>
#include <TopOpeBRepDS_Interference.hxx>
#include <Geom2d_Curve.hxx>
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_CurveIterator.hxx>
#include <TopOpeBRepDS_PointIterator.hxx>
#include <TopOpeBRepDS_SurfaceIterator.hxx>
#include <Geom2d_Curve.hxx>
#include <TCollection_AsciiString.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <Standard_NoMoreObject.hxx>
#include <Standard_NoSuchObject.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Vertex.hxx>
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopOpeBRepDS_Curve.hxx>
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <Geom2d_Curve.hxx>
#include <TopOpeBRepDS_Interference.hxx>
#include <TopOpeBRepDS_Curve.hxx>
#include <TopOpeBRepDS_SurfaceExplorer.hxx>
#include <TopOpeBRepDS_CurveExplorer.hxx>
#include <TopOpeBRepDS_PointExplorer.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Shape.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopOpeBRepDS_GapTool.hxx>
#include <TopOpeBRepDS_Association.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Edge.hxx>
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_Curve.hxx>
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_Interference.hxx>
#include <TopOpeBRepDS_InterferenceIterator.hxx>
#include <TopOpeBRepDS_TKI.hxx>
#include <TopOpeBRepDS_Transition.hxx>
#include <TopOpeBRepDS_CurvePointInterference.hxx>
#include <TopOpeBRepDS_SurfaceCurveInterference.hxx>
#include <TopOpeBRepDS_SolidSurfaceInterference.hxx>
#include <TopOpeBRepDS_ShapeShapeInterference.hxx>
#include <TopOpeBRepDS_EdgeVertexInterference.hxx>
#include <TopOpeBRepDS_FaceEdgeInterference.hxx>
#include <TopOpeBRepDS_Surface.hxx>
#include <TopOpeBRepDS_Curve.hxx>
#include <TopOpeBRepDS_Point.hxx>
#include <TopOpeBRepDS_GeometryData.hxx>
#include <TopOpeBRepDS_SurfaceData.hxx>
#include <TopOpeBRepDS_CurveData.hxx>
#include <TopOpeBRepDS_PointData.hxx>
#include <TopOpeBRepDS_ShapeData.hxx>
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_SurfaceIterator.hxx>
#include <TopOpeBRepDS_CurveIterator.hxx>
#include <TopOpeBRepDS_PointIterator.hxx>
#include <TopOpeBRepDS_SurfaceExplorer.hxx>
#include <TopOpeBRepDS_CurveExplorer.hxx>
#include <TopOpeBRepDS_PointExplorer.hxx>
#include <TopOpeBRepDS_InterferenceTool.hxx>
#include <TopOpeBRepDS_BuildTool.hxx>
#include <TopOpeBRepDS_Dumper.hxx>
#include <TopOpeBRepDS_Marker.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopOpeBRepDS_EdgeInterferenceTool.hxx>
#include <TopOpeBRepDS_Edge3dInterferenceTool.hxx>
#include <TopOpeBRepDS_FaceInterferenceTool.hxx>
#include <TopOpeBRepDS_Filter.hxx>
#include <TopOpeBRepDS_Reducer.hxx>
#include <TopOpeBRepDS_TOOL.hxx>
#include <TopOpeBRepDS_FIR.hxx>
#include <TopOpeBRepDS_EIR.hxx>
#include <TopOpeBRepDS_Check.hxx>
#include <TopOpeBRepDS_GapFiller.hxx>
#include <TopOpeBRepDS_GapTool.hxx>
#include <TopOpeBRepDS_Association.hxx>
#include <TopOpeBRepDS_ListOfShapeOn1State.hxx>
#include <TopOpeBRepDS_Explorer.hxx>
#include <TopOpeBRepDS_ShapeWithState.hxx>
#include <TopOpeBRepDS_Interference.hxx>
#include <Geom_Surface.hxx>
#include <TopoDS_Shape.hxx>
#include <TopOpeBRepDS_Interference.hxx>
#include <TopOpeBRepDS_Point.hxx>
#include <TopOpeBRepDS_Interference.hxx>
#include <TopOpeBRepDS_Transition.hxx>
#include <Geom2d_Curve.hxx>

// module includes
#include <TopOpeBRepDS_DataMapOfShapeState.hxx>
#include <TopOpeBRepDS_MapOfIntegerShapeData.hxx>
#include <TopOpeBRepDS_SurfaceExplorer.hxx>
#include <TopOpeBRepDS_Transition.hxx>
#include <TopOpeBRepDS_BuildTool.hxx>
#include <TopOpeBRepDS_Check.hxx>
#include <TopOpeBRepDS_Kind.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfMapOfSurface.hxx>
#include <TopOpeBRepDS_TKI.hxx>
#include <TopOpeBRepDS_Dumper.hxx>
#include <TopOpeBRepDS_ShapeData.hxx>
#include <TopOpeBRepDS_TOOL.hxx>
#include <TopOpeBRepDS_Curve.hxx>
#include <TopOpeBRepDS_PointExplorer.hxx>
#include <TopOpeBRepDS_Association.hxx>
#include <TopOpeBRepDS_MapOfShapeData.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopOpeBRepDS_DataMapOfShapeListOfShapeOn1State.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfDataMapOfInterferenceListOfInterference.hxx>
#include <TopOpeBRepDS_Marker.hxx>
#include <TopOpeBRepDS_Array1OfDataMapOfIntegerListOfInterference.hxx>
#include <TopOpeBRepDS_DataMapOfIntegerListOfInterference.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfDataMapOfIntegerListOfInterference.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfMapOfIntegerShapeData.hxx>
#include <TopOpeBRepDS_DataMapOfInterferenceListOfInterference.hxx>
#include <TopOpeBRepDS_repvg.hxx>
#include <TopOpeBRepDS_DRAW.hxx>
#include <TopOpeBRepDS_EXPORT.hxx>
#include <TopOpeBRepDS_CurveIterator.hxx>
#include <TopOpeBRepDS_Interference.hxx>
#include <TopOpeBRepDS_Explorer.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfDataMapOfInterferenceShape.hxx>
#include <TopOpeBRepDS_CurveData.hxx>
#include <TopOpeBRepDS_GapTool.hxx>
#include <TopOpeBRepDS_SurfaceData.hxx>
#include <TopOpeBRepDS_Reducer.hxx>
#include <TopOpeBRepDS_MapOfPoint.hxx>
#include <TopOpeBRepDS_ShapeSurface.hxx>
#include <TopOpeBRepDS_GeometryData.hxx>
#include <TopOpeBRepDS_SurfaceCurveInterference.hxx>
#include <TopOpeBRepDS_PointIterator.hxx>
#include <TopOpeBRepDS_FaceInterferenceTool.hxx>
#include <TopOpeBRepDS_connex.hxx>
#include <TopOpeBRepDS_EdgeVertexInterference.hxx>
#include <TopOpeBRepDS_SolidSurfaceInterference.hxx>
#include <TopOpeBRepDS_ListOfShapeOn1State.hxx>
#include <TopOpeBRepDS_SurfaceIterator.hxx>
#include <TopOpeBRepDS_ListIteratorOfListOfInterference.hxx>
#include <TopOpeBRepDS_DoubleMapIteratorOfDoubleMapOfIntegerShape.hxx>
#include <TopOpeBRepDS_DataStructure.hxx>
#include <TopOpeBRepDS_MapOfCurve.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfShapeSurface.hxx>
#include <TopOpeBRepDS_define.hxx>
#include <TopOpeBRepDS_ListOfInterference.hxx>
#include <TopOpeBRepDS_Point.hxx>
#include <TopOpeBRepDS_HArray1OfDataMapOfIntegerListOfInterference.hxx>
#include <TopOpeBRepDS_IndexedDataMapOfShapeWithState.hxx>
#include <TopOpeBRepDS_Filter.hxx>
#include <TopOpeBRepDS_MapOfSurface.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfDataMapOfShapeState.hxx>
#include <TopOpeBRepDS_ShapeShapeInterference.hxx>
#include <TopOpeBRepDS_EIR.hxx>
#include <TopOpeBRepDS_FIR.hxx>
#include <TopOpeBRepDS_ShapeWithState.hxx>
#include <TopOpeBRepDS_GapFiller.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfMapOfCurve.hxx>
#include <TopOpeBRepDS_CurvePointInterference.hxx>
#include <TopOpeBRepDS_FaceEdgeInterference.hxx>
#include <TopOpeBRepDS_ProcessInterferencesTool.hxx>
#include <TopOpeBRepDS_DoubleMapOfIntegerShape.hxx>
#include <TopOpeBRepDS_CheckStatus.hxx>
#include <TopOpeBRepDS_PointData.hxx>
#include <TopOpeBRepDS_DataMapOfInterferenceShape.hxx>
#include <TopOpeBRepDS_IndexedDataMapOfVertexPoint.hxx>
#include <TopOpeBRepDS_CurveExplorer.hxx>
#include <TopOpeBRepDS_samdom.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfMapOfPoint.hxx>
#include <TopOpeBRepDS_PDataStructure.hxx>
#include <TopOpeBRepDS.hxx>
#include <TopOpeBRepDS_Edge3dInterferenceTool.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfDataMapOfShapeListOfShapeOn1State.hxx>
#include <TopOpeBRepDS_Surface.hxx>
#include <TopOpeBRepDS_DataMapIteratorOfDataMapOfCheckStatus.hxx>
#include <TopOpeBRepDS_Config.hxx>
#include <TopOpeBRepDS_InterferenceIterator.hxx>
#include <TopOpeBRepDS_DataMapOfCheckStatus.hxx>
#include <TopOpeBRepDS_EdgeInterferenceTool.hxx>
#include <TopOpeBRepDS_InterferenceTool.hxx>

// user-defined pre
#include "OCP_specific.inc"

// Class template handling functions
// ./opencascade/TopOpeBRepDS_DataMapOfShapeState.hxx
// ./opencascade/TopOpeBRepDS_MapOfIntegerShapeData.hxx
// ./opencascade/TopOpeBRepDS_SurfaceExplorer.hxx
// ./opencascade/TopOpeBRepDS_Transition.hxx
// ./opencascade/TopOpeBRepDS_BuildTool.hxx
// ./opencascade/TopOpeBRepDS_Check.hxx
// ./opencascade/TopOpeBRepDS_Kind.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfMapOfSurface.hxx
// ./opencascade/TopOpeBRepDS_TKI.hxx
// ./opencascade/TopOpeBRepDS_Dumper.hxx
// ./opencascade/TopOpeBRepDS_ShapeData.hxx
// ./opencascade/TopOpeBRepDS_TOOL.hxx
// ./opencascade/TopOpeBRepDS_Curve.hxx
// ./opencascade/TopOpeBRepDS_PointExplorer.hxx
// ./opencascade/TopOpeBRepDS_Association.hxx
// ./opencascade/TopOpeBRepDS_MapOfShapeData.hxx
// ./opencascade/TopOpeBRepDS_HDataStructure.hxx
// ./opencascade/TopOpeBRepDS_DataMapOfShapeListOfShapeOn1State.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfDataMapOfInterferenceListOfInterference.hxx
// ./opencascade/TopOpeBRepDS_Marker.hxx
// ./opencascade/TopOpeBRepDS_Array1OfDataMapOfIntegerListOfInterference.hxx
// ./opencascade/TopOpeBRepDS_DataMapOfIntegerListOfInterference.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfDataMapOfIntegerListOfInterference.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfMapOfIntegerShapeData.hxx
// ./opencascade/TopOpeBRepDS_DataMapOfInterferenceListOfInterference.hxx
// ./opencascade/TopOpeBRepDS_repvg.hxx
// ./opencascade/TopOpeBRepDS_DRAW.hxx
// ./opencascade/TopOpeBRepDS_EXPORT.hxx
// ./opencascade/TopOpeBRepDS_CurveIterator.hxx
// ./opencascade/TopOpeBRepDS_Interference.hxx
// ./opencascade/TopOpeBRepDS_Explorer.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfDataMapOfInterferenceShape.hxx
// ./opencascade/TopOpeBRepDS_CurveData.hxx
// ./opencascade/TopOpeBRepDS_GapTool.hxx
// ./opencascade/TopOpeBRepDS_SurfaceData.hxx
// ./opencascade/TopOpeBRepDS_Reducer.hxx
// ./opencascade/TopOpeBRepDS_MapOfPoint.hxx
// ./opencascade/TopOpeBRepDS_ShapeSurface.hxx
// ./opencascade/TopOpeBRepDS_GeometryData.hxx
// ./opencascade/TopOpeBRepDS_SurfaceCurveInterference.hxx
// ./opencascade/TopOpeBRepDS_PointIterator.hxx
// ./opencascade/TopOpeBRepDS_FaceInterferenceTool.hxx
// ./opencascade/TopOpeBRepDS_connex.hxx
// ./opencascade/TopOpeBRepDS_EdgeVertexInterference.hxx
// ./opencascade/TopOpeBRepDS_SolidSurfaceInterference.hxx
// ./opencascade/TopOpeBRepDS_ListOfShapeOn1State.hxx
// ./opencascade/TopOpeBRepDS_SurfaceIterator.hxx
// ./opencascade/TopOpeBRepDS_ListIteratorOfListOfInterference.hxx
// ./opencascade/TopOpeBRepDS_DoubleMapIteratorOfDoubleMapOfIntegerShape.hxx
// ./opencascade/TopOpeBRepDS_DataStructure.hxx
// ./opencascade/TopOpeBRepDS_MapOfCurve.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfShapeSurface.hxx
// ./opencascade/TopOpeBRepDS_define.hxx
// ./opencascade/TopOpeBRepDS_ListOfInterference.hxx
// ./opencascade/TopOpeBRepDS_Point.hxx
// ./opencascade/TopOpeBRepDS_HArray1OfDataMapOfIntegerListOfInterference.hxx
// ./opencascade/TopOpeBRepDS_IndexedDataMapOfShapeWithState.hxx
// ./opencascade/TopOpeBRepDS_Filter.hxx
// ./opencascade/TopOpeBRepDS_MapOfSurface.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfDataMapOfShapeState.hxx
// ./opencascade/TopOpeBRepDS_ShapeShapeInterference.hxx
// ./opencascade/TopOpeBRepDS_EIR.hxx
// ./opencascade/TopOpeBRepDS_FIR.hxx
// ./opencascade/TopOpeBRepDS_ShapeWithState.hxx
// ./opencascade/TopOpeBRepDS_GapFiller.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfMapOfCurve.hxx
// ./opencascade/TopOpeBRepDS_CurvePointInterference.hxx
// ./opencascade/TopOpeBRepDS_FaceEdgeInterference.hxx
// ./opencascade/TopOpeBRepDS_ProcessInterferencesTool.hxx
// ./opencascade/TopOpeBRepDS_DoubleMapOfIntegerShape.hxx
// ./opencascade/TopOpeBRepDS_CheckStatus.hxx
// ./opencascade/TopOpeBRepDS_PointData.hxx
// ./opencascade/TopOpeBRepDS_DataMapOfInterferenceShape.hxx
// ./opencascade/TopOpeBRepDS_IndexedDataMapOfVertexPoint.hxx
// ./opencascade/TopOpeBRepDS_CurveExplorer.hxx
// ./opencascade/TopOpeBRepDS_samdom.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfMapOfPoint.hxx
// ./opencascade/TopOpeBRepDS_PDataStructure.hxx
// ./opencascade/TopOpeBRepDS.hxx
// ./opencascade/TopOpeBRepDS_Edge3dInterferenceTool.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfDataMapOfShapeListOfShapeOn1State.hxx
// ./opencascade/TopOpeBRepDS_Surface.hxx
// ./opencascade/TopOpeBRepDS_DataMapIteratorOfDataMapOfCheckStatus.hxx
// ./opencascade/TopOpeBRepDS_Config.hxx
// ./opencascade/TopOpeBRepDS_InterferenceIterator.hxx
// ./opencascade/TopOpeBRepDS_DataMapOfCheckStatus.hxx
// ./opencascade/TopOpeBRepDS_EdgeInterferenceTool.hxx
// ./opencascade/TopOpeBRepDS_InterferenceTool.hxx

// user-defined post
